/**
 * Names of the explanatory diagrams available to lesson content (rendered as inline SVG by
 * src/components/diagrams). Content validation fails if a lesson references a name not listed here.
 * Each description doubles as the default alt text.
 */
export const diagramCatalog = {
  "fdm-printer": "A filament 3D printer: spool feeds filament to a heated nozzle that moves over a build plate.",
  "layers-stack": "An object split into thin horizontal layers stacked from the build plate upward.",
  "subtractive-vs-additive": "Left: a block with material cut away (subtractive). Right: material added layer by layer (additive).",
  "xyz-axes": "Three arrows: X (red) left–right, Y (green) front–back, Z (blue) up.",
  "view-controls": "Mouse map: right-drag orbits, middle-drag or shift+right-drag pans, scroll wheel zooms; the view cube resets the view.",
  "selection": "Click selects one shape, shift-click adds shapes, dragging a box selects everything inside it.",
  "workplane": "A grid workplane placed on the sloped face of a wedge so a new shape sits flat on that face.",
  "nudge-keys": "Arrow keys nudge a shape 1 mm on X/Y; shift+arrow nudges 10 mm; ctrl+up/down raises or lowers on Z.",
  "move-z": "A shape lifted above the workplane; the cone handle on top drags it up or down; D drops it to the workplane.",
  "scale-handles": "Corner handles resize two directions at once, side handles resize one direction, the top handle changes height; shift keeps proportions.",
  "exact-dimension": "Clicking a dimension number opens a box where you type an exact value in millimetres.",
  "rotate-handles": "Curved arrows around a selected shape rotate it around X, Y or Z; dragging near the arrow snaps to 22.5° steps.",
  "group-hole": "A solid box plus a hole cylinder, grouped, makes a box with a cylindrical opening.",
  "solid-vs-hole": "The same cylinder shown as a solid (adds material) and as a hole (removes material).",
  "align-handles": "The align tool shows dots along each axis; clicking the middle dot centres the selected shapes on each other.",
  "duplicate-pattern": "Duplicate-and-repeat: copy, move once, then repeat makes evenly spaced copies along a line or around a circle.",
  "mirror-axis": "A shape flipped across a mirror line to create its symmetric partner.",
  "text-raised-recessed": "Raised text sits on top of a surface; recessed text is a hole shape cut into the surface.",
  "die-net": "An unfolded die showing that opposite faces always add up to seven.",
  "ruler-tool": "The ruler placed at a corner shows distances from that point; typing a value moves the shape exactly.",
  "caliper-parts": "Digital calipers: outside jaws, inside jaws, depth rod, zero button and display.",
  "measure-critical": "A real object with its critical dimension (the one that must fit) highlighted.",
  "clearance-fit": "A peg inside a hole with a small gap around it — the clearance.",
  "tolerance-range": "A target size with a range above and below it that still counts as acceptable.",
  "fit-types": "Three fits: tight/press fit, sliding fit and loose fit, shown with different gaps.",
  "prototype-critical": "Instead of printing a whole part, print only the thin slice that contains the hole you are testing.",
  "wall-thickness": "Cross-sections of thin, medium and thick walls compared to the width of a 0.4 mm nozzle line.",
  "overhang-angles": "Overhangs at 20°, 45° and 70° from vertical; up to about 45° prints well, steeper ones droop.",
  "bridge-span": "Filament stretched between two pillars: short bridges hold, long bridges sag.",
  "supports": "Support material printed under an overhang and removed after printing.",
  "self-supporting": "Replacing a flat overhang with a 45° chamfer so the part supports itself.",
  "orientation-strength": "A hook printed standing (layers across the hook — weak) versus printed flat (layers along the hook — strong).",
  "hook-standing": "A hook standing upright on the build plate with layer lines running across its stem.",
  "hook-flat": "A hook lying flat on its side with layer lines running along the whole hook.",
  "hook-upside-down": "A hook upside down on its curved tip, balanced on a small contact area.",
  "infill-patterns": "Cut-away views of 10%, 20% and 50% infill inside a part with solid walls.",
  "walls-perimeters": "Cross-section showing perimeters (outer walls) and infill in the middle.",
  "material-compare": "A solid block and a hollowed block of the same outside size, with material used for each.",
  "failure-stringing": "Thin wisps of plastic stretched between two towers (stringing).",
  "failure-warping": "Corners of a print curling up off the build plate (warping).",
  "failure-spaghetti": "A print knocked loose, with filament piled like spaghetti.",
  "failure-layer-shift": "A print with its upper layers shifted sideways from the lower layers.",
  "failure-elephant-foot": "The bottom layers bulging outward wider than the rest (elephant's foot).",
  "failure-under-extrusion": "Gaps and thin lines where too little plastic came out (under-extrusion).",
  "first-layer": "First-layer quality: nozzle too high (round lines), just right (flat lines), too low (scraped, transparent).",
  "support-scars": "Rough marks left on a surface where support material was removed.",
  "phone-stand-symptoms": "The CAD ER patient: a phone stand labelled with five symptoms.",
  "design-cycle": "The design cycle: understand → define → ideate → prototype → test → revise, looping back.",
  "follow-to-design": "Five steps: Follow, Modify, Combine, Solve, Design.",
  "constraint-vs-wish": "Constraints (must, measurable) compared with wishes (nice to have).",
  "sketch-concepts": "Three quick, different sketches for the same problem before choosing one.",
} as const;

export type DiagramName = keyof typeof diagramCatalog;
export const diagramNames = Object.keys(diagramCatalog) as DiagramName[];
