import type { ModelAssetInput, LicenseId } from "./schema";
import manifest from "./generated/model-manifest.json";

/**
 * Model asset registry (spec §16–20).
 *
 * ORIGINAL assets are generated by scripts/generate-models.ts and bundled. Their license is configurable
 * here before publication (CC BY 4.0 by default; set to "CC0-1.0" to dedicate them to the public domain).
 *
 * EXTERNAL assets are recorded with their source page and the license reported for them, but are NOT bundled
 * until a platform administrator verifies the license on the source page, places the original file under
 * public/models/external/, fills `localFilePath`, and sets `sourceVerifiedAt`. Until then the UI links out to the
 * source. A downloadable model is not automatically redistributable (spec §17).
 */
export const ORIGINAL_ASSET_LICENSE: LicenseId = "CC-BY-4.0";
const ORIGINAL_CREATOR = "3D Design Academy";
const GENERATOR = "scripts/generate-models.ts";

type ManifestEntry = { file: string; size: [number, number, number]; anchors: Record<string, [number, number, number]>; notes: string };
export const modelManifest = manifest as unknown as Record<string, ManifestEntry>;

function original(
  id: string,
  title: string,
  educationalPurpose: string,
  purposeBullets: string[],
  lessonIds: string[],
): ModelAssetInput {
  const m = modelManifest[id];
  if (!m) throw new Error(`Model ${id} missing from manifest — run npm run models:generate`);
  const cc0 = ORIGINAL_ASSET_LICENSE === "CC0-1.0";
  return {
    id,
    title,
    creator: ORIGINAL_CREATOR,
    sourcePlatform: "3D Design Academy",
    originalFileName: `${id}.stl`,
    localFilePath: m.file,
    format: "stl",
    license: ORIGINAL_ASSET_LICENSE,
    licenseVersion: cc0 ? "1.0" : "4.0",
    attributionRequired: !cc0,
    commercialUseAllowed: true,
    remixAllowed: true,
    sourceVerifiedAt: "2026-10-02",
    educationalPurpose,
    purposeBullets,
    lessonIds,
    attributionText: cc0
      ? `“${title}” by 3D Design Academy, dedicated to the public domain (CC0 1.0).`
      : `“${title}” by 3D Design Academy, licensed CC BY 4.0.`,
    generatorSource: GENERATOR,
    original: true,
    dimensionsMm: m.size,
  };
}

function external(a: Omit<ModelAssetInput, "original" | "sourceVerifiedAt" | "format"> & { format?: "stl" }): ModelAssetInput {
  return { format: "stl", ...a, original: false, sourceVerifiedAt: null };
}

export const modelAssetInputs: ModelAssetInput[] = [
  // ───── Original course assets (bundled) ─────
  original("misplaced-shapes", "Misplaced Shapes", "Practice orbit, pan, zoom, select and move by rescuing scattered shapes.", ["Navigation", "Selecting", "Moving on X/Y/Z"], ["navigating-tinkercad", "moving-objects", "workspace-rescue"]),
  original("toolbox-parts", "Toolbox Parts", "Parts that only fit in the tray after they are rotated flat.", ["Rotation", "Workplane", "Exact placement"], ["rotating-objects", "workspace-rescue"]),
  original("broken-die", "Broken Die", "A die built incorrectly — wrong size, through-holes and a floating feature.", ["Exact dimensions", "Holes vs. solids", "Grouping"], ["boss-die", "exact-dimensions"]),
  original("bad-phone-stand", "Bad Phone Stand (CAD ER patient)", "A phone stand with five deliberate design faults to diagnose and repair.", ["Stability", "Fit", "Supports", "Layer strength", "Material use"], ["cad-er"]),
  original("orientation-hook", "Orientation Hook", "The same hook prints weak or strong depending on how it sits on the plate.", ["Layer direction", "Anisotropic strength"], ["orientation", "strength", "layers"]),
  original("excessive-support-object", "T-Bracket (needs support)", "A shape whose flat arms need support in its default orientation.", ["Overhangs", "Supports"], ["supports", "overhangs"]),
  original("redesigned-support-object", "T-Bracket (redesigned)", "The same part with 45° chamfers so it supports itself.", ["Self-supporting angles", "Design for printing"], ["supports", "overhangs", "material-efficiency"]),
  original("peg-10mm", "Peg — 10.0 mm", "A 10 mm reference peg for fit testing.", ["Clearance", "Tolerance"], ["tolerances", "make-it-fit"]),
  original("hole-10mm", "Hole — 10.0 mm", "A 10.0 mm hole: zero designed clearance.", ["Clearance", "Machine variation"], ["tolerances"]),
  original("hole-10-2mm", "Hole — 10.2 mm", "A 10.2 mm hole: 0.1 mm clearance per side.", ["Clearance", "Machine variation"], ["tolerances"]),
  original("hole-10-4mm", "Hole — 10.4 mm", "A 10.4 mm hole: 0.2 mm clearance per side.", ["Clearance", "Machine variation"], ["tolerances"]),
  original("thin-wall-test", "Thin Wall Test", "Six walls from 0.4 to 3.0 mm: which ones print, and which are strong?", ["Wall thickness", "Nozzle size"], ["print-failures", "strength", "material-efficiency"]),
  original("mystery-fit-object", "Mystery Fit Object", "An unfamiliar object to measure and design a fitted cap for.", ["Measurement", "Holes for real objects", "Clearance"], ["make-it-fit", "measuring-real-objects", "calipers"]),
  original("axis-cube-20mm", "Axis Cube 20 mm", "A 20 mm calibration cube with notches marking X, Y and Z.", ["Dimensions", "Calibration", "X/Y/Z axes"], ["ruler", "measuring-real-objects", "layers", "what-is-3d-printing"]),
  original("overhang-test", "Overhang Angle Test", "Fins at 20°–70° from vertical show where overhangs start to fail.", ["Overhangs", "45° rule of thumb"], ["overhangs"]),
  original("bridge-test", "Bridge Span Test", "Bridges of 10, 20, 40 and 60 mm between pillars.", ["Bridging", "Cooling"], ["bridging"]),
  original("misaligned-stack", "Misaligned Stack", "Four cylinders that should share a centre line.", ["Align tool"], ["align"]),
  original("half-bracket", "Half Bracket", "Half of a symmetric bracket — mirror it to complete the part.", ["Mirror", "Group"], ["mirror"]),
  original("wedge-block", "Wedge Block", "A wedge with a sloped face for workplane practice.", ["Workplane"], ["workplanes"]),

  // ───── External, openly licensed diagnostic models (link-out until verified) ─────
  external({
    id: "ext-calibration-cube-kingtut",
    title: "Calibration Cube",
    creator: "KingTut",
    sourcePlatform: "Printables",
    sourcePage: "https://www.printables.com/model/591501-calibration-calibration-cube",
    originalFileName: "(see source page)",
    license: "public-domain",
    attributionRequired: false,
    commercialUseAllowed: true,
    remixAllowed: true,
    educationalPurpose: "Dimensions, print calibration, measurement and X/Y/Z discussion.",
    purposeBullets: ["Dimensions", "Calibration", "Measurement"],
    lessonIds: ["ruler", "measuring-real-objects", "layers"],
    attributionText: "“Calibration Cube” by KingTut on Printables.",
  }),
  external({
    id: "ext-tolerance-test-viceroysyrup",
    title: "Tolerance Test 0–3 / 0.05 Steps",
    creator: "ViceroySyrup",
    sourcePlatform: "Printables",
    originalFileName: "(see source page)",
    license: "public-domain",
    attributionRequired: false,
    commercialUseAllowed: true,
    remixAllowed: true,
    educationalPurpose: "Clearance, tolerance and machine-to-machine variation.",
    purposeBullets: ["Clearance", "Tolerance"],
    lessonIds: ["tolerances", "make-it-fit"],
    attributionText: "“Tolerance Test 0–3 / 0.05 Steps” by ViceroySyrup on Printables.",
  }),
  external({
    id: "ext-quick-bridging-test-aravon",
    title: "Quick Bridging Test",
    creator: "Aravon",
    sourcePlatform: "Printables",
    sourcePage: "https://www.printables.com/model/32697-quick-bridging-test",
    originalFileName: "(see source page)",
    license: "public-domain",
    attributionRequired: false,
    commercialUseAllowed: true,
    remixAllowed: true,
    educationalPurpose: "Bridges, cooling and unsupported spans.",
    purposeBullets: ["Bridging", "Cooling"],
    lessonIds: ["bridging", "overhangs"],
    attributionText: "“Quick Bridging Test” by Aravon on Printables.",
  }),
  external({
    id: "ext-all-in-one-tester-morejoncarlos",
    title: "All-in-One Printer Tester",
    creator: "morejoncarlos",
    sourcePlatform: "Printables",
    originalFileName: "(see source page)",
    license: "public-domain",
    attributionRequired: false,
    commercialUseAllowed: true,
    remixAllowed: true,
    educationalPurpose: "Support, scale, overhang and general print diagnostics.",
    purposeBullets: ["Overhangs", "Supports", "Diagnostics"],
    lessonIds: ["overhangs", "supports", "print-failures"],
    attributionText: "“All-in-One Printer Tester” by morejoncarlos on Printables.",
  }),
  external({
    id: "ext-support-removal-test-unclejessy",
    title: "Support Removal Test",
    creator: "Uncle Jessy",
    sourcePlatform: "Printables",
    sourcePage: "https://www.printables.com/model/1038477-support-removal-test-no-more-stuck-supports",
    originalFileName: "(see source page)",
    license: "public-domain",
    attributionRequired: false,
    commercialUseAllowed: true,
    remixAllowed: true,
    educationalPurpose: "Support interface distance and support removal experiments.",
    purposeBullets: ["Supports", "Slicer settings"],
    lessonIds: ["supports"],
    attributionText: "“Support Removal Test” by Uncle Jessy on Printables.",
  }),
  external({
    id: "ext-snapfit-box-keosovandara",
    title: "Snapfit Box",
    creator: "ly keosovandara",
    sourcePlatform: "Printables",
    originalFileName: "(see source page)",
    license: "public-domain",
    attributionRequired: false,
    commercialUseAllowed: true,
    remixAllowed: true,
    educationalPurpose: "Tolerances, mating parts and snap-fit mechanisms.",
    purposeBullets: ["Mating parts", "Snap fits"],
    lessonIds: ["tolerances", "make-it-fit"],
    attributionText: "“Snapfit Box” by ly keosovandara on Printables.",
  }),
];
