/**
 * Supporting prints on Printables.com, suggested per lesson for the teacher guide and print kit.
 * These are LINKS ONLY: files are not bundled. Each page was opened to confirm it exists (October 2026), but the
 * license wasn't readable automatically, so teachers check it on the page before sharing files beyond their class.
 */
export type PrintablesPick = { lessonId: string; title: string; url: string; creator: string; printInfo: string; use: string };

export const printablesPicks: PrintablesPick[] = [
  {"lessonId": "what-is-3d-printing", "title": "XYZ-10mm Calibration Cube", "url": "https://www.printables.com/model/32539-xyz-10mm-calibration-cube", "creator": "Halit", "printInfo": "10 mm cube with X/Y/Z letters; very fast, no supports", "use": "Print one live at the start of class so students watch it build layer by layer, then pass it around to feel the layer lines."},
  {"lessonId": "print-detective", "title": "Bridging / overhang / curling / retraction / thin walls torture test", "url": "https://www.printables.com/model/13998-bridging-overhang-curling-retraction-thin-walls-to", "creator": "Mirar", "printInfo": "Small all-in-one torture test", "use": "One evidence piece showing bridge sag, overhang droop, curling, stringing and thin walls for detectives to find and name."},
  {"lessonId": "print-detective", "title": "3D Printer Multimodel Test and Troubleshooting Kit", "url": "https://www.printables.com/model/293328-3d-printer-multimodel-test-and-troubleshooting-kit", "creator": "SparkLink Development", "printInfo": "10 separate tests (supports, bridging, stringing, tolerance, overhang, text…); includes a PDF analysis guide", "use": "Set up extra Print Detective stations, one failure type each, and use the creator's PDF as an answer key."},
  {"lessonId": "moving-objects", "title": "XYZ-10mm Calibration Cube", "url": "https://www.printables.com/model/32539-xyz-10mm-calibration-cube", "creator": "Halit", "printInfo": "10 mm cube, X/Y/Z on its faces", "use": "Students hold a cube next to the Tinkercad workplane and match its X, Y and Z faces to the directions they move objects."},
  {"lessonId": "rotating-objects", "title": "Tube Tree Print Orientation Test", "url": "https://www.printables.com/model/1136254-tube-tree-print-orientation-test", "creator": "D. Eichenbaum", "printInfo": "Six cylinders at 0°–90°; no supports; can be scaled to 50%", "use": "The same cylinder rotated to six labelled angles, so students see what “pick the axis, then the angle” produces."},
  {"lessonId": "text", "title": "Text Size Test Prints", "url": "https://www.printables.com/model/476654-text-size-test-prints", "creator": "kaje", "printInfo": "Plates with raised text from 0.5 mm to 3 mm high (0.4 mm nozzle)", "use": "Students find the smallest text that's still readable, then keep their Tinkercad text above that size."},
  {"lessonId": "text", "title": "All direction Text/Logo Emboss Deboss Test", "url": "https://www.printables.com/model/143901-all-direction-textlogo-emboss-deboss-test", "creator": "hexben.3d", "printInfo": "About 4.5 h, 38 g at 0.15 mm — print once and keep", "use": "The same text embossed and debossed on top, side and bottom faces, to compare which combinations print cleanly."},
  {"lessonId": "calipers", "title": "XYZ-10mm Calibration Cube", "url": "https://www.printables.com/model/32539-xyz-10mm-calibration-cube", "creator": "Halit", "printInfo": "10 mm cube; fast", "use": "Students measure X, Y and Z to 0.1 mm and compare their readings with the 10.0 mm design size."},
  {"lessonId": "tolerances", "title": "Clearance Tolerance Test", "url": "https://www.printables.com/model/116911-clearance-tolerance-test", "creator": "3DMakerNoob", "printInfo": "Compact clearance test", "use": "Students see which gaps move freely and which fuse shut — why a 10 mm peg needs a hole a little bigger than 10 mm."},
  {"lessonId": "tolerances", "title": "Print in Place Tolerance Tester", "url": "https://www.printables.com/model/254416-print-in-place-tolerance-tester", "creator": "OGRE_Cubes", "printInfo": "Sliders and pegs with stepped gaps", "use": "Students try to free each peg to find the smallest gap that still moves on your printer."},
  {"lessonId": "make-it-fit", "title": "Print in Place Tolerance Tester", "url": "https://www.printables.com/model/254416-print-in-place-tolerance-tester", "creator": "OGRE_Cubes", "printInfo": "Sliders and pegs with stepped gaps", "use": "The class reference for choosing a clearance before students design parts that fit together."},
  {"lessonId": "orientation", "title": "Wall Hook (Strong print orientation)", "url": "https://www.printables.com/model/567068-wall-hook-strong-print-orientation", "creator": "Alex Bergesen", "printInfo": "About 15 min, 3 g; no supports", "use": "Print one hook as intended and one turned 90° on its side, then load both to see which layer direction snaps."},
  {"lessonId": "strength", "title": "CNC Kitchen Test Hook", "url": "https://www.printables.com/model/99053-cnc-kitchen-test-hook", "creator": "CNC Kitchen", "printInfo": "Standard strength-test hook", "use": "Print copies with different walls, infill or orientation and hang weights until they fail."},
  {"lessonId": "strength", "title": "Layer Strength Testing Jig and Test Chips", "url": "https://www.printables.com/model/1010844-layer-strength-testing-jig-and-test-chips", "creator": "bwschulz", "printInfo": "About 30 min, 5 g", "use": "Students split chips along their layer lines to see that layer bonding is a print's weak direction."},
  {"lessonId": "overhangs", "title": "Overhang and Bridging Test Model", "url": "https://www.printables.com/model/363919-overhang-and-bridging-test-model", "creator": "Layershift3d", "printInfo": "90° overhang and bridging test", "use": "Show an overhang printed on “thin air” and talk about when an overhang needs help."},
  {"lessonId": "overhangs", "title": "Tube Tree Print Orientation Test", "url": "https://www.printables.com/model/1136254-tube-tree-print-orientation-test", "creator": "D. Eichenbaum", "printInfo": "Six cylinders from 0° to 90°; no supports", "use": "Students compare surfaces across the angles to find where quality drops — the 45° rule in their hands."},
  {"lessonId": "bridging", "title": "Mini Printer Test (Overhang, Bridge and String)", "url": "https://www.printables.com/model/315884-mini-printer-test-overhang-bridge-and-string", "creator": "dusty", "printInfo": "Small, fast combined test", "use": "Bridges of several lengths so students see sag grow as the span gets longer."},
  {"lessonId": "supports", "title": "Supports Test — Normal and Tree Supports", "url": "https://www.printables.com/model/1019886-supports-test-normal-and-tree-supports-simultaneou", "creator": "Fuorissimo", "printInfo": "Slice with Tree Support → Hybrid; PDF guide included", "use": "Compare normal and tree supports, then remove them to show the scars each leaves behind."},
  {"lessonId": "material-efficiency", "title": "Infill samples", "url": "https://www.printables.com/model/228285-infill-samples", "creator": "Swichtden", "printInfo": "About 5 h, 66 g — print once and keep", "use": "Open-face samples of infill patterns and densities, so students see how much plastic each setting uses inside."},
  {"lessonId": "print-failures", "title": "Simple stringing/retraction test", "url": "https://www.printables.com/model/450792-simple-3d-printer-stringingretraction-test", "creator": "JT Labs", "printInfo": "Small tower test with a PDF guide", "use": "Print once with retraction turned down and once with good settings for a side-by-side lesson on cause and fix."},
];
