import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "align",
  number: 12,
  title: "Align",
  subtitle: "Line things up exactly — no eyeballing",
  domain: "B",
  kind: "lesson",
  summary: "Use the Align tool to centre shapes on each other or line up their edges, then fix a stack that is off-centre.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["B4"],
  prerequisites: ["holes"],
  vocabulary: [
    { term: "Align", definition: "Moving shapes so their centres or edges line up on X, Y or Z." },
    { term: "Centre line", definition: "An imaginary line through the middle of a shape that other shapes can share." },
    { term: "Reference shape", definition: "The shape that stays still while the others move to line up with it." },
    { term: "Flush", definition: "Two edges or faces lined up perfectly, with no step between them." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Close enough isn't centred.",
          hook: "A hole that is 0.5 mm off-centre makes a lopsided wheel. Your eyes can't see 0.5 mm. The Align tool can.",
          visual: { diagram: "align-handles" },
        },
        {
          id: "explain",
          type: "text",
          body: "Select two or more shapes and press **L**. Dots appear along each axis. Each axis has three dots: one edge, the **centre**, and the other edge. Click a dot and the shapes line up there.",
        },
        {
          id: "stack-view",
          type: "modelViewer",
          modelId: "misaligned-stack",
          caption: "Four cylinders that should share one centre line. Orbit around it — none of them do.",
          showDimensions: true,
        },
        {
          id: "show-me",
          type: "showMe",
          title: "Centre a hole in a box",
          steps: [
            { text: "Place a Box (30 × 30 × 10 mm) and a Cylinder hole (8 × 8 × 12 mm) somewhere near it.", diagram: "solid-vs-hole" },
            { text: "Select both shapes (Shift+click or drag a selection box).", diagram: "selection" },
            { text: "Press L. Dots appear around the selection.", diagram: "align-handles", keys: "L" },
            { text: "Click the middle dot on the X axis, then the middle dot on the Y axis. The hole is now centred." },
            { text: "Group (Ctrl+G) to cut the hole.", diagram: "group-hole", keys: "Ctrl+G" },
          ],
        },
        {
          id: "callout-reference",
          type: "callout",
          tone: "tip",
          title: "Choose which shape stays still",
          body: "After pressing L, click one of the selected shapes. That shape becomes the reference and stays put; the others move to it.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "A small cube sits on a big box. You select both, press L, and click the middle dot on X only. What happens?",
          visual: { diagram: "align-handles" },
          options: [
            { id: "a", text: "They line up left–right, but front–back stays the same." },
            { id: "b", text: "The cube moves to the exact centre of the box in every direction.", misconceptionId: "align-all-axes" },
            { id: "c", text: "The cube sinks into the box.", misconceptionId: "align-z-auto" },
          ],
          expectedOptionId: "a",
          reveal: "Each dot only works on one axis. X centre lines them up left–right. You need the Y centre dot as well to centre them completely. Z only changes if you click a Z dot.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        { id: "files", type: "modelDownload", modelIds: ["misaligned-stack"], showImportSteps: true },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Straighten the stack",
          steps: [
            "Create a new design and import the Misaligned Stack.",
            "If the stack imports as one piece, ungroup it (Ctrl+Shift+G) so you can move each cylinder.",
            "Select all four cylinders, press L, and centre them on X and on Y.",
            "Orbit to check from the front and the side. Every cylinder should share the same centre line.",
          ],
        },
        {
          id: "pick-reference",
          type: "hotspot",
          prompt: "You want the stack centred on its biggest, lowest cylinder so the base doesn't move. Click the best reference shape.",
          modelId: "misaligned-stack",
          hotspots: [
            { id: "bottom", label: "Bottom cylinder", position: [0, 0, 3], radius: 12, correct: true, feedback: "Test result: good choice. The base is the widest part and sits on the workplane, so everything else should move to it." },
            { id: "middle", label: "Middle cylinder", position: [4, -3, 9], radius: 9, correct: false, feedback: "That works mathematically, but the base would slide around to meet it. Which shape would you rather keep still?" },
            { id: "top", label: "Top cylinder", position: [-5, 6, 15], radius: 8, correct: false, feedback: "If the top is the reference, the whole base moves under it. Which part sets the footprint?" },
            { id: "post", label: "Post", position: [8, 2, 23], radius: 6, correct: false, feedback: "The post is the smallest part. Using it as the reference drags the big pieces around." },
          ],
          explanation: "Pick the shape whose position already matters — usually the base. Click it after pressing L to make it the reference.",
          competencyId: "B4",
          check: "practice",
        },
        {
          id: "edge-mc",
          type: "multipleChoice",
          prompt: "You want a 10 mm cube to sit flush with the right edge of a 50 mm box (not centred). Which dot do you click on the X axis?",
          visual: { diagram: "align-handles" },
          options: [
            { id: "a", text: "The dot at the right end of the X axis" },
            { id: "b", text: "The middle dot on the X axis", misconceptionId: "align-centre-only" },
            { id: "c", text: "Any Z dot" },
          ],
          correctOptionIds: ["a"],
          explanation: "The end dots line up edges. The right-end dot makes the right faces of both shapes flush.",
          competencyId: "B4",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Target practice",
          prompt: "Make a target: three cylinders (40, 26 and 12 mm wide, each 2 mm taller than the one below) that share one centre line.",
          requirements: ["All three centred on X and Y", "Bottom cylinder did not move", "Single grouped model"],
          skills: ["B4", "B2"],
        },
        {
          id: "micro-mc",
          type: "multipleChoice",
          prompt: "You aligned on X and Y, but the small cylinder is hidden inside the big one. What happened?",
          options: [
            { id: "a", text: "All three cylinders sit on the workplane, so the shorter ones are buried. Make each taller or raise it." },
            { id: "b", text: "Align deletes shapes that overlap.", misconceptionId: "align-deletes" },
            { id: "c", text: "You needed to click the middle dot twice." },
          ],
          correctOptionIds: ["a"],
          explanation: "X and Y alignment never changes height. Check Z: each cylinder must stick up above the one below it.",
          competencyId: "B4",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Lighthouse",
          prompt: "Build a lighthouse on a 40 × 40 × 5 mm base: a 24 mm cylinder tower 40 mm tall, a 30 mm wide balcony disc 3 mm thick near the top, and a cone roof. Drill a 6 mm hole straight down the middle of the tower. Add a 10 × 10 × 8 mm shed flush with the back-right corner of the base. No steps — choose your own alignments.",
          requirements: [
            "Tower, balcony, roof and hole share one centre line",
            "Shed is flush with the back edge and the right edge of the base",
            "Hole is centred and does not cut through the base",
            "Single grouped model",
          ],
          skills: ["B4", "B3", "B2"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a class design link or two screenshots: one from the top view and one from the front.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["B4"],
          checklist: ["Top view shows the circles sharing one centre", "Shed edges line up with the base", "Everything is one group"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "When would you line up edges instead of centres? Give a real object as an example.",
          sentenceStarters: ["I would line up edges when…", "For example, a…"],
          competencyIds: ["B4"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students learn that Align works one axis at a time, choose between centre and edge alignment, and pick a reference shape on purpose.",
    preparation: [
      "Import the Misaligned Stack into Tinkercad yourself once to check whether it arrives as one piece (students may need to ungroup it).",
      "Have a projector ready to demonstrate one axis at a time.",
    ],
    equipment: ["Student devices with Tinkercad", "Projector"],
    misconceptions: [
      { id: "align-all-axes", text: "One click on Align centres shapes in every direction.", response: "Demo clicking only the X centre dot, then orbit to show Y is unchanged." },
      { id: "align-z-auto", text: "Align also changes height automatically.", response: "Point out that the Z dots are separate; nothing moves on Z unless you click one." },
      { id: "align-centre-only", text: "Align can only centre shapes.", response: "Show the end dots: they make edges flush. Ask for an object that needs flush edges (a drawer front, a shelf)." },
      { id: "align-deletes", text: "Shapes hidden after aligning have been deleted.", response: "Switch to wireframe-style thinking: orbit, or select the hidden shape from a drag box to prove it is still there." },
    ],
    discussionQuestions: [
      "Why is the base the best reference for the stack?",
      "Name an object where things must be centred, and one where edges must be flush.",
    ],
    troubleshooting: [
      "No dots appear: at least two shapes (or a grouped object plus a shape) must be selected before pressing L.",
      "Wrong shape moved: press Ctrl+Z, press L again, and click the shape that should stay still before clicking a dot.",
      "Shape jumped far away: the student clicked an end dot instead of the middle one.",
    ],
    answerGuidance: [
      "Stack: centre all four on X and Y with the bottom cylinder as reference.",
      "Lighthouse: tower, balcony, cone and hole centred on X and Y; balcony raised to roughly 34–37 mm; hole starts above the base floor (e.g. raised 2 mm) or stops inside the base; shed aligned with the back (max Y) and right (max X) end dots.",
    ],
    alternatives: { touchDevice: "Use the Align button in the top toolbar instead of the L key; tap the dots." },
  },
};
