import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "boss-die",
  number: 17,
  title: "Boss Battle: The Mystery Die",
  subtitle: "No tutorial. Just you, a cube and six faces.",
  domain: "B",
  kind: "boss",
  summary: "Debug a broken die, then design a perfect 20 mm die with recessed numbering on all six faces — without step-by-step directions.",
  estimatedMinutes: 100,
  printLevel: "prototype",
  competencyIds: ["B2", "B3", "B4", "B5", "A9", "A10", "A11"],
  prerequisites: ["text"],
  vocabulary: [
    { term: "Pip", definition: "One of the dots on a die face." },
    { term: "Recess", definition: "A dip cut into a surface that stops before going through." },
    { term: "Penetrate", definition: "To cut all the way through an object, leaving an open hole." },
    { term: "Opposite faces", definition: "Two faces on opposite sides of a cube, such as top and bottom." },
  ],
  sections: [
    {
      phase: "discover",
      title: "The mission",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "The Mystery Die",
          hook: "Somebody built a die. It looks almost right. It isn't. Find out what's broken — then build one that's perfect. No tutorial this time.",
          visual: { modelId: "broken-die" },
        },
        {
          id: "brief",
          type: "text",
          body: "Your die must be **exactly 20 × 20 × 20 mm**, with **recessed** numbering on all **six** faces. No pip may cut through the cube. Everything ends up as **one grouped model**, and you prove the size with a screenshot.",
        },
        {
          id: "die-net",
          type: "diagram",
          name: "die-net",
          caption: "Optional extra constraint: on a real die, opposite faces add up to 7 (1–6, 2–5, 3–4).",
          alt: "An unfolded die. Faces 1 and 6, 2 and 5, and 3 and 4 sit opposite each other.",
        },
        {
          id: "callout-timer",
          type: "callout",
          tone: "idea",
          title: "About the timer",
          body: "The boss card shows how long you've been working. It's for your awareness only — speed does not change your grade.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You cut a pip with a cylinder hole that is 25 mm tall. What happens to your 20 mm die?",
          options: [
            { id: "a", text: "The pip goes all the way through and comes out the other side." },
            { id: "b", text: "It makes a neat 1 mm dip.", misconceptionId: "hole-height-ignored" },
            { id: "c", text: "Nothing — holes only cut what's touching the top.", misconceptionId: "holes-only-surface" },
          ],
          expectedOptionId: "a",
          reveal: "A hole removes material everywhere it overlaps. A 25 mm hole through a 20 mm cube penetrates. For a recess, the hole must only overlap the cube by the depth you want, for example 1–2 mm.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Warm-up: debug the broken die",
      blocks: [
        { id: "files", type: "modelDownload", modelIds: ["broken-die"], showImportSteps: true },
        {
          id: "broken-view",
          type: "modelViewer",
          modelId: "broken-die",
          caption: "The broken die. Orbit it and look at every face. Count what's wrong.",
          showDimensions: true,
        },
        {
          id: "find-through",
          type: "hotspot",
          prompt: "Which flaw breaks the rule 'recesses may not penetrate the cube'?",
          modelId: "broken-die",
          hotspots: [
            { id: "through", label: "Pip that runs through the cube", position: [10.5, 10, 20], radius: 6, correct: true, feedback: "Test result: found it. This pip hole is taller than the cube, so it cuts right through to the other side." },
            { id: "floating", label: "Floating pip", position: [5, -6, 10], radius: 6, correct: false, feedback: "That's a real problem too — it isn't touching the cube at all, so it cuts nothing. But it doesn't go through. Keep looking." },
            { id: "raised", label: "Raised feature", position: [6, 6, 20.5], radius: 6, correct: false, feedback: "Also broken: it sticks up instead of cutting in (it's Solid, not Hole). But it doesn't penetrate." },
            { id: "corner", label: "Cube corner", position: [21, 20, 19.4], radius: 6, correct: false, feedback: "The corner shows a size problem (21 × 20 × 19.4 mm), not a hole that goes through." },
          ],
          explanation: "The broken die has four separate faults: wrong size, a through-hole, a floating pip and a raised feature — and nothing is grouped. Each one breaks a different requirement.",
          competencyId: "B3",
          check: "practice",
        },
        {
          id: "fault-match",
          type: "matching",
          prompt: "Match each fault on the broken die to the fix.",
          pairs: [
            { id: "size", left: "Cube is 21 × 20 × 19.4 mm", right: "Type exact dimensions: 20 × 20 × 20" },
            { id: "through", left: "Pip goes through the cube", right: "Make the hole overlap only 1–2 mm" },
            { id: "float", left: "Pip floats beside the cube", right: "Move it onto a face (a workplane helps)" },
            { id: "raised", left: "Feature sticks up", right: "Switch it from Solid to Hole and sink it in" },
            { id: "loose", left: "Nothing is grouped", right: "Select everything and group" },
          ],
          explanation: "Every requirement in the boss challenge matches one of these faults. Use this as your checklist.",
          competencyId: "B2",
          check: "practice",
        },
        {
          id: "height-fix",
          type: "measurement",
          prompt: "The broken cube is 19.4 mm tall. How many mm taller must it become?",
          answer: 0.6,
          tolerance: 0,
          unit: "mm",
          explanation: "20 − 19.4 = 0.6 mm. Dragging a handle by eye rarely lands on this — type the value.",
          competencyId: "A9",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Plan your attack",
      blocks: [
        {
          id: "depth-check",
          type: "measurement",
          prompt: "Your cube sits on the workplane. You want pips on the top face recessed 1.5 mm deep. Where should the bottom of each pip hole be?",
          answer: 18.5,
          tolerance: 0,
          unit: "mm (Z)",
          hint: "The top face is at Z = 20 mm.",
          explanation: "20 − 1.5 = 18.5 mm. The hole should also reach above 20 mm so it cleanly opens the top face.",
          competencyId: "B3",
          check: "skill",
        },
        {
          id: "side-faces",
          type: "multipleChoice",
          prompt: "Which approach works for putting pips on the side faces? (Choose every one that works.)",
          options: [
            { id: "a", text: "Put a workplane on the side face and place hole shapes on it." },
            { id: "b", text: "Build the pips on top, then rotate the cube (or the pips) 90° so they face the side." },
            { id: "c", text: "Pips can only go on the top face.", misconceptionId: "top-only" },
          ],
          correctOptionIds: ["a", "b"],
          explanation: "Both work. A workplane (W) lets you build straight onto any face. Rotating in 90° steps also works if you check positions afterwards.",
          competencyId: "A11",
          check: "skill",
        },
        {
          id: "plan-order",
          type: "ordering",
          prompt: "Put these checks in a sensible order for finishing your die.",
          items: [
            { id: "size", text: "Set the cube to exactly 20 × 20 × 20 mm" },
            { id: "pips", text: "Add recessed pips on all six faces" },
            { id: "inspect", text: "Orbit every face: no pip goes through, none float" },
            { id: "group", text: "Group everything into one model" },
            { id: "verify", text: "Click the group and screenshot its 20 × 20 × 20 dimensions" },
          ],
          explanation: "Verify after grouping: a stray solid shape would make the group read larger than 20 mm, so the final screenshot doubles as a last check.",
          competencyId: "A9",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Boss battle",
      blocks: [
        {
          id: "boss",
          type: "challenge",
          kind: "boss",
          title: "The Mystery Die",
          prompt: "Design a die. No tutorial, no steps — use everything you've learned. When you think you're done, check it against every requirement.",
          requirements: [
            "Exactly 20 × 20 × 20 mm",
            "Six faces numbered 1–6 with recessed geometry (pips, numbers or your own design)",
            "Recesses are 1–2 mm deep and none penetrate the cube",
            "Single grouped model with no stray shapes",
            "Dimensions verified with a screenshot",
            "Optional constraint: opposite faces add up to 7",
          ],
          skills: ["A9", "A10", "A11", "B2", "B3", "B4", "B5"],
          showTimer: true,
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Open your workspace",
          steps: [
            "Create a new design and name it 'Mystery Die' with your initials.",
            "You may reuse parts of the broken die, or start fresh.",
          ],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your die as a class design link or STL, plus a screenshot of the grouped die showing 20 × 20 × 20 mm.",
          accepts: ["design_url", "stl", "screenshot"],
          competencyIds: ["A9", "B2", "B3", "B4", "B5", "A10", "A11"],
          checklist: [
            "Screenshot shows 20.00 × 20.00 × 20.00 mm on the grouped die",
            "All six faces have recessed numbering",
            "No recess goes through the cube",
            "Everything is one group",
          ],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Debrief",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "What was the hardest part of building without instructions? What did you do when you got stuck?",
          sentenceStarters: ["The hardest part was…", "When I got stuck, I…", "Next time I would…"],
          minWords: 20,
          competencyIds: ["A11", "B3"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "A no-tutorial boss challenge that combines exact dimensions, holes, alignment, duplication, rotation, workplanes and grouping. The broken-die warm-up gives students a checklist without giving them steps.",
    preparation: [
      "Import the Broken Die into Tinkercad once so you know what students will see (it arrives ungrouped).",
      "Decide whether finished dice will be printed. If yes, collect STLs and batch-print the best-verified designs.",
      "Plan for two class periods: warm-up + planning in the first, the boss build in the second.",
    ],
    equipment: ["Student devices with Tinkercad", "Optional: a real die to pass around", "Optional: 3D printer for selected dice"],
    misconceptions: [
      { id: "hole-height-ignored", text: "A hole's height doesn't matter — it only cuts a little dip.", response: "Ungroup the broken die's through-pip and read its height (taller than 20 mm)." },
      { id: "holes-only-surface", text: "Holes only cut the surface they touch.", response: "Hole shapes subtract their whole volume. Orbit underneath the broken die to show the exit hole." },
      { id: "top-only", text: "You can only add features to the top face.", response: "Remind students of the Workplane lesson: W places a workplane on any face." },
    ],
    discussionQuestions: [
      "Which fault on the broken die would you never have spotted without orbiting?",
      "How did you verify your die was exactly 20 mm without trusting your eyes?",
    ],
    printableObjects: ["Students' finished dice (20 mm cubes) — optional, for selected verified designs"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls, no supports needed for 1–2 mm recesses on the top and sides. Recesses on the bottom face may sag slightly; that is normal and a good discussion point. Adjust for your printer.",
    troubleshooting: [
      "Group is larger than 20 mm: a stray solid (for example a pip left as Solid, or the broken die's raised feature) is in the group. Ungroup, drag a selection box around the area and look for extra shapes.",
      "A face looks blank after grouping: the pips on that face are floating just off the surface. Ungroup and move them so they overlap the face.",
      "Pips look misaligned: suggest the Align tool (L) on each set of pips, or typed positions.",
    ],
    answerGuidance: [
      "Typical solution: 20 mm cube; pip = cylinder hole about 3.5–4 mm wide, 1.5 mm overlapping the face; duplicate pips; use workplanes or 90° rotations for side faces; group; screenshot dimensions.",
      "Numbers instead of pips are fine if they are recessed and readable (letters at least 5–6 mm tall).",
      "Use the boss-die rubric: dimensions (A9), recessed numbering (B3, B4, A10, A11), single group (B2, B5). Time taken is not a criterion.",
      "Opposite faces adding to 7 is optional; acknowledge students who meet it.",
    ],
    rubricId: "boss-die",
    alternatives: {
      noPrinter: "The boss is fully assessable digitally from the dimension screenshot and design link.",
      touchDevice: "Workplane, Align and Group are available from the toolbar; typed dimensions avoid fiddly dragging.",
    },
  },
};
