import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "boss-nametag",
  number: 17,
  title: "Boss Battle: The Name Tag",
  subtitle: "One tag. Five rules. No tutorial.",
  domain: "B",
  kind: "boss",
  summary: "Spot what's wrong with a broken name tag, then design your own 50 mm keychain tag with a raised name and a key-ring hole — without step-by-step directions.",
  estimatedMinutes: 90,
  printLevel: "prototype",
  competencyIds: ["A9", "B2", "B3", "B4", "B10"],
  prerequisites: ["text"],
  vocabulary: [
    { term: "Spec", definition: "Short for specification: the exact rules a design must meet." },
    { term: "Raised", definition: "Sticking up from a surface, like letters on a sign." },
    { term: "Margin", definition: "The plastic left between a hole and the edge of the part." },
    { term: "Floating", definition: "Not touching the part. A floating piece prints as a separate scrap, or not at all." },
  ],
  sections: [
    {
      phase: "discover",
      title: "The mission",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "The Name Tag",
          hook: "Design a keychain name tag for your backpack. It has to match the spec exactly. First, find out why this one fails.",
          visual: { modelId: "broken-tag" },
        },
        {
          id: "brief",
          type: "text",
          body: "**The spec — your tag must have:**\n\n1. A tag exactly **50 × 20 × 3 mm**\n2. Your name or gamer tag **raised 1 mm**, letters at least **6 mm** tall\n3. The name **centered** on the tag\n4. A **5 mm key-ring hole** with at least **2 mm** of plastic around it\n5. Everything **grouped** into one part\n\nThat's it. How you build it is up to you.",
        },
        {
          id: "callout-timer",
          type: "callout",
          tone: "idea",
          title: "About the timer",
          body: "The boss card shows how long you've been working. It's for your awareness only — speed does not change your grade.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "Your letters sit at Z = 4 mm, but the tag is only 3 mm thick. You group and print. What happens?",
          options: [
            { id: "a", text: "The letters aren't touching the tag, so they print as loose scraps (or fail)." },
            { id: "b", text: "Grouping glues them on, so it prints fine.", misconceptionId: "group-glues" },
            { id: "c", text: "The printer fills the 1 mm gap automatically.", misconceptionId: "printer-fills-gaps" },
          ],
          expectedOptionId: "a",
          reveal: "Grouping doesn't move anything. Parts only join if they touch or overlap. Put the bottom of the letters at Z = 3 mm — right on top of the tag.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Warm-up: why does this tag fail?",
      blocks: [
        {
          id: "broken-view",
          type: "modelViewer",
          modelId: "broken-tag",
          caption: "The broken tag. Orbit around it and compare it with the spec.",
          showDimensions: true,
        },
        {
          id: "find-tear",
          type: "hotspot",
          prompt: "A key ring would rip right out of this tag. Click the reason.",
          modelId: "broken-tag",
          hotspots: [
            { id: "hole", label: "Key-ring hole", position: [1.5, 10, 3], radius: 5, correct: true, feedback: "Found it. The hole cuts through the edge, so there's no plastic to hold the ring. Keep at least 2 mm between the hole and the edge." },
            { id: "name", label: "Name letters", position: [27, 10, 5], radius: 6, correct: false, feedback: "Those letters are a problem too — they float above the tag — but they don't make the ring rip out. Keep looking." },
            { id: "end", label: "Far end of the tag", position: [56, 10, 3], radius: 5, correct: false, feedback: "This end shows a size problem (the tag is 56 mm, not 50). That won't rip the ring out, though." },
          ],
          explanation: "The broken tag has four faults: it's 56 mm long, the hole breaks the edge, the name floats 1 mm above the tag and isn't centered. Each one breaks a rule in the spec.",
          competencyId: "B3",
          check: "practice",
        },
        {
          id: "fault-match",
          type: "matching",
          prompt: "Match each fault to its fix.",
          pairs: [
            { id: "size", left: "Tag is 56 mm long", right: "Type the length: 50" },
            { id: "hole", left: "Hole breaks the edge", right: "Move the hole in so 2 mm of plastic is left" },
            { id: "float", left: "Letters float above the tag", right: "Set the letters' bottom to Z = 3 mm" },
            { id: "center", left: "Name is off to one side", right: "Select tag + name, then Align to center" },
          ],
          explanation: "These four fixes are your checklist for the boss.",
          competencyId: "B4",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Plan your build",
      blocks: [
        {
          id: "hole-x",
          type: "measurement",
          prompt: "The tag's left edge is at X = 0. Your key-ring hole is 5 mm wide and needs 2 mm of plastic to its left. Where should the hole's left edge go?",
          answer: 2,
          tolerance: 0,
          unit: "mm (X)",
          hint: "The margin is the gap between the tag's edge and the hole's edge.",
          explanation: "2 mm. The hole then spans X = 2 to 7 mm, leaving 2 mm of plastic between it and the edge.",
          competencyId: "B3",
          check: "skill",
        },
        {
          id: "center-how",
          type: "multipleChoice",
          prompt: "Your name has to be centered on the tag — but the hole is at one end. What's the best way?",
          options: [
            { id: "a", text: "Select the tag and the name, click Align (L), then click the middle dots for X and Y." },
            { id: "b", text: "Drag the name until it looks about right.", misconceptionId: "eyeball-center" },
            { id: "c", text: "Group them first — grouping centers things.", misconceptionId: "group-glues" },
          ],
          correctOptionIds: ["a"],
          explanation: "Align centers shapes exactly. Do it before you add the hole, or select only the tag and the name, so the hole doesn't change what counts as the middle.",
          competencyId: "B4",
          check: "skill",
        },
        {
          id: "plan-order",
          type: "ordering",
          prompt: "Put the build in a sensible order.",
          items: [
            { id: "tag", text: "Make the tag: 50 × 20 × 3 mm" },
            { id: "name", text: "Add your name: 6 mm+ tall, 1 mm high, bottom at Z = 3" },
            { id: "align", text: "Align the name to the center of the tag" },
            { id: "hole", text: "Add the 5 mm key-ring hole, 2 mm from the edge" },
            { id: "group", text: "Group everything and check it reads 50 × 20 × 4 mm" },
          ],
          explanation: "Align before the hole, so centering uses just the tag and name. After grouping, the size should read 50 × 20 × 4 mm (3 mm tag + 1 mm letters). Anything bigger means a stray shape.",
          competencyId: "A9",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Boss battle",
      blocks: [
        {
          id: "boss",
          type: "challenge",
          kind: "boss",
          title: "The Name Tag",
          prompt: "Design your keychain name tag. No tutorial, no steps — just the spec. When you think you're done, check every rule.",
          requirements: [
            "Tag exactly 50 × 20 × 3 mm",
            "Name raised 1 mm and touching the tag; letters at least 6 mm tall",
            "Name centered on the tag",
            "5 mm key-ring hole with at least 2 mm of plastic around it",
            "Everything grouped; the group reads 50 × 20 × 4 mm",
            "Bonus: add a small icon on both sides of your name using Mirror",
          ],
          skills: ["A9", "B2", "B3", "B4", "B10"],
          showTimer: true,
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Open your workspace",
          steps: ["Create a new design and name it 'Name Tag' with your initials.", "Keep the spec open in this tab so you can check it."],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your tag as a class design link or STL, plus a screenshot of the grouped tag showing its size.",
          accepts: ["design_url", "stl", "screenshot"],
          competencyIds: ["A9", "B2", "B3", "B4", "B10"],
          checklist: [
            "Screenshot shows 50 × 20 × 4 mm on the grouped tag",
            "Name is raised, readable and centered",
            "Key-ring hole has plastic all the way around it",
            "Everything is one group",
          ],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Debrief",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Which rule in the spec was hardest to meet? How did you check that you'd met it?",
          sentenceStarters: ["The hardest rule was…", "I checked it by…", "Next time I would…"],
          minWords: 20,
          competencyIds: ["A9", "B4"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "A no-tutorial boss challenge with one clear goal: build a keychain tag to a five-rule spec. It combines exact dimensions, raised text, Align, holes and grouping. The broken-tag warm-up turns the spec into a checklist without giving steps.",
    preparation: [
      "Open the Broken Tag model once so you know what students will see.",
      "Have key rings or split rings ready if you'll print tags — students love getting them back.",
      "Plan for about two class periods: warm-up and planning, then the build.",
    ],
    equipment: ["Student devices with Tinkercad", "Optional: 3D printer and key rings", "Optional: a printed example tag to pass around"],
    misconceptions: [
      { id: "group-glues", text: "Grouping glues parts together even if they don't touch.", response: "Group the broken tag and show that the letters still float 1 mm above it." },
      { id: "printer-fills-gaps", text: "The printer fills small gaps.", response: "The printer prints exactly what's in the file. A floating part prints in mid-air, or not at all." },
      { id: "eyeball-center", text: "Dragging until it looks centered is good enough.", response: "Drag a shape to 'center', then use Align and read how far it moved." },
    ],
    discussionQuestions: [
      "Why does a key-ring hole need plastic around it? What would happen with only 0.5 mm?",
      "How could you prove your name is centered without trusting your eyes?",
    ],
    printableObjects: ["Students' finished name tags (about 15–20 minutes each; good for batch printing)"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15–20% infill, 3 walls, no supports. Print flat with the name facing up. A filament swap at 3 mm (pause at layer height) makes a two-color tag. Adjust for your printer.",
    troubleshooting: [
      "Group is taller than 4 mm: the letters are floating or too tall. Ungroup and set the letters' bottom to Z = 3 and height to 1 mm.",
      "Group is wider than 50 mm: a stray shape or the hole sticks out past the end. Ungroup and look for extra shapes.",
      "Name isn't centered after Align: the hole was included in the selection. Ungroup and align only the tag and the name.",
      "Long names don't fit at 6 mm: shorten to initials or a nickname rather than shrinking letters below 6 mm.",
    ],
    answerGuidance: [
      "Typical solution: 50 × 20 × 3 mm box; text about 8 mm tall and 1 mm high with its bottom at Z = 3; Align tag and text to center; 5 mm cylinder hole at X = 2–7 mm, centered on Y, cutting through; group; screenshot 50 × 20 × 4 mm.",
      "Recessed names are acceptable if the student explains the choice, though the spec asks for raised.",
      "Use the boss-nametag rubric: size (A9), name (B10, B4), hole (B3), single group (B2). Time taken is not a criterion.",
      "The mirrored icons are a bonus; acknowledge students who do them.",
    ],
    rubricId: "boss-nametag",
    alternatives: {
      noPrinter: "The boss is fully assessable digitally from the size screenshot and design link.",
      touchDevice: "Align and Group are on the toolbar; typed dimensions avoid fiddly dragging.",
    },
  },
};
