import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "bridging",
  number: 27,
  title: "Bridging",
  subtitle: "Stretching plastic across a gap",
  domain: "D",
  kind: "lesson",
  summary: "Learn when a printer can stretch plastic across a gap between two supports, and how span length changes the result.",
  estimatedMinutes: 45,
  printLevel: "prototype",
  competencyIds: ["D3"],
  prerequisites: ["overhangs"],
  vocabulary: [
    { term: "Bridge", definition: "A flat section printed across open air, held up at both ends." },
    { term: "Span", definition: "The distance a bridge has to cross between its supports." },
    { term: "Sag", definition: "When the middle of a bridge droops down." },
    { term: "Cooling", definition: "Air from the printer's fan that hardens plastic quickly so it holds its shape." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Overhang vs. bridge",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "A flat ledge fails. A flat bridge often doesn't.",
          hook: "Last lesson, flat overhangs drooped. But a flat roof held up at BOTH ends can print across open air — if the gap isn't too long.",
          visual: { diagram: "bridge-span" },
        },
        {
          id: "explain",
          type: "text",
          body: "When a gap has support on both sides, the printer stretches strands of plastic straight across, like a rope. The fan cools them before they sag. Short **spans** work well. Long spans sag in the middle.",
        },
        { id: "viewer", type: "modelViewer", modelId: "bridge-test", caption: "Four bridges: 10, 20, 40 and 60 mm spans on 12 mm pillars.", showLayers: true },
        {
          id: "predict",
          type: "prediction",
          prompt: "Your teacher prints the Bridge Span Test. Which is the shortest span you think will visibly sag?",
          options: [
            { id: "s10", text: "10 mm", misconceptionId: "no-bridges" },
            { id: "s20", text: "20 mm" },
            { id: "s40", text: "40 mm" },
            { id: "s60", text: "60 mm" },
          ],
          revealTitle: "Check the print",
          reveal: "Many school printers bridge 10–20 mm cleanly, show some sag around 40 mm and more at 60 mm. Fan speed, print speed, temperature and plastic all change the result — so your printer's answer is the one that counts.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Read the test",
      blocks: [
        {
          id: "hotspot",
          type: "hotspot",
          prompt: "Click the bridge that is MOST likely to sag on a typical printer.",
          modelId: "bridge-test",
          hotspots: [
            { id: "b10", label: "10 mm span", position: [11, 4, 13], radius: 6, correct: false, feedback: "A short span — the strands barely have time to sag." },
            { id: "b20", label: "20 mm span", position: [16, 18, 13], radius: 6, correct: false, feedback: "Usually fine on a printer with good cooling." },
            { id: "b40", label: "40 mm span", position: [26, 32, 13], radius: 6, correct: false, feedback: "May sag a little. Not the worst one here." },
            { id: "b60", label: "60 mm span", position: [36, 46, 13], radius: 6, correct: true, feedback: "The longest span has the most time to cool slowly and droop in the middle." },
          ],
          explanation: "The longer the span, the heavier the unsupported strand and the longer it stays soft — so sag grows with span.",
          competencyId: "D3",
          check: "practice",
        },
        {
          id: "mc-bridge-or-overhang",
          type: "multipleChoice",
          prompt: "Which of these is a BRIDGE (supported at both ends)?",
          options: [
            { id: "a", text: "The crossbar of a capital H printed standing up" },
            { id: "b", text: "The top bar of a capital T printed standing up", misconceptionId: "bridge-equals-overhang" },
            { id: "c", text: "A shelf sticking out of a wall on one side only", misconceptionId: "bridge-equals-overhang" },
          ],
          correctOptionIds: ["a"],
          explanation: "A bridge needs support at BOTH ends. The T's arms and a one-sided shelf are overhangs — they only connect on one side.",
          competencyId: "D3",
          check: "skill",
        },
        {
          id: "mc-fix",
          type: "multipleChoice",
          prompt: "A 70 mm wide shelf on two legs sags in the middle when printed. Which design change is most likely to fix it without supports?",
          options: [
            { id: "a", text: "Add a third leg in the middle so each span is about 35 mm or less." },
            { id: "b", text: "Make the shelf thicker — the bottom layer still has to cross 70 mm.", misconceptionId: "thicker-bridge" },
            { id: "c", text: "Make the legs taller." },
          ],
          correctOptionIds: ["a"],
          explanation: "The first layer of the shelf is the one that bridges, so thickness doesn't shorten the span. A middle support halves it. An arch-shaped underside is another fix.",
          competencyId: "D3",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Mini bridge",
          prompt: "Build two pillars and a roof between them, with a span short enough that you expect it to print cleanly.",
          requirements: ["Pillars at least 10 mm tall", "Span between 10 and 25 mm", "Roof 2 mm thick, touching both pillars", "Single grouped model"],
          skills: ["D3", "A9", "B2"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Build the mini bridge",
          steps: ["Create a new design.", "Use the ruler to set the gap between the pillars exactly.", "Make sure the roof sits on top of both pillars, not floating above them."],
        },
        {
          id: "optional-test",
          type: "text",
          title: "Want a second test?",
          body: "This optional community bridging test is a link to the original creator's page.",
        },
        { id: "ext-files", type: "modelDownload", modelIds: ["ext-quick-bridging-test-aravon"], showImportSteps: false, required: false },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "The cable gate",
          prompt: "Design a desk cable organizer: a block with a tunnel underneath that cables pass through. It must print with no supports in the orientation you choose.",
          requirements: [
            "Tunnel opening at least 50 mm wide and 10 mm tall",
            "No single unsupported span longer than 25 mm — or the underside is shaped so it doesn't need to bridge (for example an arch or 45° slopes)",
            "Explain your choice: extra pillars, an arch, a different orientation, or something else",
            "Single grouped model sitting on the workplane",
          ],
          skills: ["D3", "D2", "B3"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a front-view screenshot and explain how your design avoids a long sagging bridge.",
          accepts: ["screenshot", "design_url", "stl"],
          competencyIds: ["D3"],
          checklist: ["Tunnel size visible", "Longest span stated", "Strategy explained"],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "What's the difference between an overhang and a bridge? Give an example of each from real life.",
          sentenceStarters: ["An overhang is…", "A bridge is…", "In real life…"],
          competencyIds: ["D3"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students distinguish bridges from overhangs, predict how span length affects sag, and design spans that print without supports.",
    preparation: [
      "If possible, print the Bridge Span Test before class (about 30–40 minutes) so students can check their prediction.",
      "Optional: print one at low fan speed and one at full fan speed to show the effect of cooling.",
    ],
    equipment: ["Student devices with Tinkercad", "Optional: printed Bridge Span Test"],
    misconceptions: [
      { id: "no-bridges", text: "Printers can't print anything over open air.", response: "Show the 10 mm bridge: clean, with no support. Support on both ends changes everything." },
      { id: "bridge-equals-overhang", text: "Any part sticking out over air is the same problem.", response: "Sort examples on the board: connected on one side (overhang) vs. both sides (bridge)." },
      { id: "thicker-bridge", text: "A thicker bridge won't sag.", response: "Slice it and show layer one: it still crosses the full span alone. Later layers just sit on a sagged first layer." },
    ],
    discussionQuestions: ["Why does the fan matter so much for bridges?", "Where have you seen arches used instead of flat spans?"],
    printableObjects: ["bridge-test (teacher demo)", "Optional: student cable gates"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2 walls, supports OFF, part-cooling fan at full for bridges — adjust for your printer.",
    troubleshooting: [
      "Every bridge sags, even 10 mm: check the cooling fan is running and print speed isn't extremely slow.",
      "Roof floating above pillars in Tinkercad: select it and lower it until it touches, or use the ruler to set its height exactly.",
    ],
    answerGuidance: [
      "Prediction: no single correct answer; record class results.",
      "Hotspot: 60 mm span.",
      "Bridge example: H crossbar. Fix: add a middle leg.",
      "Cable gate: e.g. a 54 mm tunnel split by a centre pillar into two spans of about 25 mm, an arched tunnel, or 45° sloped tunnel roof.",
    ],
    alternatives: {
      noPrinter: "Demonstrate with a strand of hot glue or a strip of spaghetti between two books: short spans hold, long spans droop.",
      touchDevice: "Tap dimension values to set the span exactly.",
    },
  },
};
