import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "cad-er",
  number: 31,
  title: "CAD ER",
  subtitle: "Diagnose and repair a broken design",
  domain: "E",
  kind: "challenge",
  summary: "A phone stand arrives with five symptoms. Diagnose each cause, write a testable hypothesis, repair the model and document honest results.",
  estimatedMinutes: 135,
  printLevel: "prototype",
  competencyIds: ["E1", "E2", "E3", "E4", "E5", "E6", "E7"],
  prerequisites: ["print-failures"],
  vocabulary: [
    { term: "Symptom", definition: "What you can see going wrong, like a stand tipping over." },
    { term: "Cause", definition: "The design feature that makes the symptom happen." },
    { term: "Hypothesis", definition: "A testable prediction: if I change this, then that will happen, because…" },
    { term: "Centre of mass", definition: "The balance point of an object. If it sits outside the base, the object tips." },
    { term: "Repair", definition: "Changing an existing design to fix a problem without starting over." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Patient intake",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "PATIENT: PHONE STAND",
          hook: "Admitted with five symptoms. It tips over, the phone won't go in, it needs support, it snaps, and it eats filament. You are the CAD doctor on duty.",
          visual: { diagram: "phone-stand-symptoms", alt: "A phone stand with five labelled problem areas." },
        },
        {
          id: "explain",
          type: "text",
          body: "Doctors don't treat symptoms by guessing. They find the **cause**, predict what a treatment will do, treat, then check. You will do the same with CAD.",
        },
        {
          id: "chart",
          type: "diagram",
          name: "phone-stand-symptoms",
          caption: "The patient chart: five reported symptoms.",
          alt: "Phone stand with labels: falls backward, slot too narrow, needs support, weak at layer line, too much material.",
        },
        {
          id: "viewer",
          type: "modelViewer",
          modelId: "bad-phone-stand",
          caption: "Orbit the patient. It is 72 × 70 × 95 mm. Look at it from the side first.",
          showDimensions: true,
          showLayers: true,
        },
        {
          id: "predict-tip",
          type: "prediction",
          prompt: "The stand falls backward as soon as you set a phone in it. What is the most likely cause?",
          visual: { modelId: "bad-phone-stand" },
          options: [
            { id: "a", text: "The tall backrest leans so far back that the balance point is behind the base." },
            { id: "b", text: "The phone is too heavy for any printed stand.", misconceptionId: "too-heavy" },
            { id: "c", text: "The base needs to be heavier, so it should be solid.", misconceptionId: "solid-is-stable" },
          ],
          expectedOptionId: "a",
          reveal: "Stability comes from where the weight sits, not how much plastic there is. The backrest top is at X = 70 mm, past the back of the base. Move weight forward or extend the base backward.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Triage",
      blocks: [
        {
          id: "find-causes",
          type: "hotspot",
          prompt: "Click every region that causes one of the five symptoms. One region is healthy.",
          hint: "Match each symptom to a place on the stand. Only one region has nothing wrong.",
          modelId: "bad-phone-stand",
          hotspots: [
            { id: "slot", label: "Phone slot", position: [15, 35, 20], radius: 6, correct: true, feedback: "Diagnosis: the slot is only 6 mm wide. Most phones in a case are 9–12 mm thick." },
            { id: "neck", label: "Neck under the slot", position: [18.6, 35, 15.5], radius: 6, correct: true, feedback: "Diagnosis: this neck is 1.2 mm thick, right where one layer meets the next. Layers pull apart easily here." },
            { id: "shelf", label: "Shelf on the backrest", position: [55, 35, 61.5], radius: 10, correct: true, feedback: "Diagnosis: a flat shelf sticking out in mid-air. The printer needs support under it — and it does nothing for the phone." },
            { id: "backrest-top", label: "Top of the backrest", position: [70, 35, 95], radius: 12, correct: true, feedback: "Diagnosis: the backrest leans back so far that the balance point ends up behind the base." },
            { id: "base", label: "Base", position: [30, 35, 7], radius: 12, correct: true, feedback: "Diagnosis: the base is a solid 14 mm block. Most of that plastic adds print time, not stability." },
            { id: "front", label: "Front edge", position: [0, 35, 7], radius: 10, correct: false, feedback: "Test result: the front edge is healthy. It sits flat on the plate and keeps the phone from sliding. Look elsewhere." },
          ],
          explanation: "Five regions are sick: slot (fit), neck (strength), shelf (support), backrest (stability) and base (material). The front edge is fine — good doctors also notice what does not need treatment.",
          competencyId: "E1",
          check: "skill",
        },
        {
          id: "match-causes",
          type: "matching",
          prompt: "Match each symptom to the design cause.",
          hint: "Read each symptom, then look at the stand and find the part that explains it.",
          pairs: [
            { id: "tips", left: "Falls backward", right: "Balance point sits behind the base" },
            { id: "fit", left: "Phone won't go in", right: "Slot narrower than the phone" },
            { id: "support", left: "Needs support", right: "Flat shelf hanging in mid-air" },
            { id: "snap", left: "Snaps at a layer line", right: "1.2 mm neck at a layer boundary" },
            { id: "waste", left: "Uses too much filament", right: "Solid 14 mm base" },
          ],
          explanation: "Every symptom has a geometric cause you can point to. If you can't point to it, you haven't diagnosed it yet.",
          competencyId: "E1",
          check: "skill",
        },
        {
          id: "slot-math",
          type: "measurement",
          prompt: "A phone in its case is 11 mm thick. You want 0.5 mm of clearance on each side. How wide should the slot be?",
          answer: 12,
          tolerance: 0,
          unit: "mm",
          hint: "There is clearance in front of the phone AND behind it.",
          explanation: "11 + 0.5 + 0.5 = 12 mm. Measure a real phone if you can — cases vary a lot.",
          competencyId: "E2",
          check: "practice",
        },
        {
          id: "neck-mc",
          type: "multipleChoice",
          prompt: "The stand will print standing up, so its layers are horizontal. Which change to the neck will most likely stop it snapping?",
          hint: "Layers are weakest where few lines of plastic connect them. What gives a layer more to hold?",
          options: [
            { id: "a", text: "Make the neck thicker (for example 4 mm) so many more lines of plastic hold each layer together." },
            { id: "b", text: "Print it faster so the layers don't cool.", misconceptionId: "speed-fixes-strength" },
            { id: "c", text: "Add more infill to the whole stand.", misconceptionId: "infill-fixes-thin" },
          ],
          correctOptionIds: ["a"],
          explanation: "A 1.2 mm neck is only a few nozzle widths thick. Infill can't fit inside something that thin. More cross-section across the layer line = more strength.",
          competencyId: "E4",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "Treatment plan",
      blocks: [
        {
          id: "hypothesis-text",
          type: "text",
          title: "Write a hypothesis for every fix",
          body: "Use this shape: **If I** change ___, **then** ___ will happen, **because** ___.\n\nExample: If I widen the slot from 6 mm to 12 mm, then an 11 mm phone will slide in, because there is 0.5 mm of clearance on each side.",
        },
        {
          id: "hypothesis-mc",
          type: "multipleChoice",
          prompt: "Which hypothesis can actually be tested?",
          hint: "A testable hypothesis names one change and a result you can measure.",
          options: [
            { id: "a", text: "If I extend the base 25 mm behind the backrest, then the stand will stay upright with a phone in it, because the balance point will be over the base." },
            { id: "b", text: "If I make it better, then it will work.", misconceptionId: "vague-hypothesis" },
            { id: "c", text: "The base is bad." },
          ],
          correctOptionIds: ["a"],
          explanation: "A testable hypothesis names a specific change, a result you can check, and a reason. You can set a phone in it and see if it tips.",
          competencyId: "E7",
          check: "skill",
        },
        {
          id: "import-tip",
          type: "callout",
          tone: "tip",
          title: "Repairing an imported model",
          body: "An imported STL becomes one shape in Tinkercad. You repair it by adding: Hole shapes to cut material away, Solid shapes to add material. Then group.",
        },
        { id: "files", type: "modelDownload", modelIds: ["bad-phone-stand"], showImportSteps: true },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Admit the patient",
          steps: [
            "Create a new design and Import bad-phone-stand.stl.",
            "Use the Ruler (R) to confirm the slot width and the neck thickness before you change anything.",
            "Treat one symptom at a time. After each fix, check that you didn't create a new problem.",
          ],
        },
        {
          id: "chart-notes",
          type: "journal",
          projectKey: "cad-er",
          promptIds: ["problem", "test", "failed", "changed"],
        },
      ],
    },
    {
      phase: "prove",
      title: "Discharge the patient",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Repair the phone stand",
          prompt: "Fix all five symptoms. No step-by-step this time — you decide how. Then test your repair and write down what happened, including anything that still fails.",
          requirements: [
            "Slot fits a phone you measured (or 11 mm) with clearance — write the number",
            "Stand stays upright with the phone in it (centre of mass over the base)",
            "No part needs support when printed standing up",
            "Neck is at least 3 mm thick",
            "Base is no longer a solid 14 mm block — less material, same stability",
            "Single grouped model",
            "A hypothesis and a result for every fix in your journal",
          ],
          skills: ["E1", "E2", "E3", "E4", "E5", "E6", "E7"],
          visual: { modelId: "bad-phone-stand" },
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your repaired stand: a class design link or STL, plus a screenshot showing the new slot and neck dimensions. If you printed it, add a photo of the phone test (no faces).",
          accepts: ["design_url", "stl", "screenshot", "physical_test"],
          competencyIds: ["E1", "E2", "E3", "E4", "E5", "E6", "E7"],
          checklist: [
            "Slot and neck dimensions are visible",
            "Shown from the side so balance is visible",
            "Every fix has a hypothesis and a result in the journal",
            "Anything that still fails is written down honestly",
          ],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Which symptom was hardest to diagnose, and how did you finally find the cause?",
          sentenceStarters: ["The hardest symptom was…", "I found the cause by…", "Next time I would check…"],
          competencyIds: ["E1", "E7"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students transfer everything from Domains C and D into diagnosis: trace each visible symptom to a geometric cause, predict the effect of a fix, repair an existing model and document results honestly.",
    preparation: [
      "Import bad-phone-stand.stl into Tinkercad on a student device to confirm it loads.",
      "Optional: print one copy of the broken stand so students can see it tip over and feel the thin neck.",
      "Have a ruler and 2–3 phones (or phone-sized blocks of wood about 11 mm thick) for testing.",
    ],
    equipment: ["Student devices with Tinkercad", "Ruler or calipers", "Phone or 11 mm test block", "3D printer (optional)"],
    misconceptions: [
      { id: "too-heavy", text: "The phone is simply too heavy for a printed stand.", response: "Balance a phone on a ruler. Weight doesn't tip things — weight outside the base does." },
      { id: "solid-is-stable", text: "Solid, heavy bases are more stable.", response: "Stability depends on the footprint and where the balance point sits. A hollow base with a longer footprint beats a heavy short one." },
      { id: "speed-fixes-strength", text: "Print settings alone fix a weak thin feature.", response: "Settings help a little, but a 1.2 mm neck is a geometry problem. Fix it in CAD first." },
      { id: "infill-fixes-thin", text: "More infill strengthens every part.", response: "Thin features are all walls — there is no room for infill. Show a sliced preview of the neck if possible." },
      { id: "vague-hypothesis", text: "A hypothesis is a general hope that it will work.", response: "Ask: what exact number changes, and what will you look for to know it worked?" },
    ],
    discussionQuestions: [
      "Why is it important to notice what is NOT broken?",
      "Can one fix create a new problem? Give an example from your repair.",
      "Why might a doctor — or an engineer — write down a failed treatment?",
    ],
    printableObjects: ["bad-phone-stand (optional demo)", "Repaired stands (one per student or per pair if printer time is limited)"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls, printed standing up on its base with supports OFF (so the shelf problem is visible). Adjust for your printer.",
    troubleshooting: [
      "If students can't ungroup the imported stand: that's expected — an imported STL is one shape. They repair by adding Hole and Solid shapes.",
      "If a hole meant to widen the slot also cuts the backrest, check its length and Z position.",
      "If the repaired stand still tips, have students view from the side (Front view) and check where the backrest top is compared with the back of the base.",
    ],
    answerGuidance: [
      "Slot: widened to about 12 mm (or measured phone + about 1 mm) with a Hole box.",
      "Stability: base extended backward past the backrest top, or backrest angle reduced — either is fine if justified.",
      "Support: shelf removed, or given a 45° chamfer underneath so it supports itself.",
      "Strength: neck thickened to at least 3 mm (4–5 mm is better).",
      "Material: base hollowed with a Hole (leaving 2–3 mm walls/floor) or made thinner while keeping its footprint.",
      "Score with the CAD ER rubric (16 pts). Honest 'still fails' notes count toward Test & Results.",
    ],
    rubricId: "cad-er",
    alternatives: {
      noPrinter: "Test digitally: side view for balance, Ruler for slot and neck, and a written support check (anything flat hanging in air?). Test the slot with a cardboard cut-out at the same width.",
      touchDevice: "Use the on-screen Ruler, Group and Hole buttons; orbit with two fingers.",
    },
  },
};
