import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "calipers",
  number: 20,
  title: "Digital Calipers",
  subtitle: "Measure to a tenth of a millimetre",
  domain: "C",
  kind: "lesson",
  summary: "Zero, read and use digital calipers for outside, inside and depth measurements, and know when that precision matters.",
  estimatedMinutes: 50,
  printLevel: "prototype",
  competencyIds: ["C4"],
  prerequisites: ["measuring-real-objects"],
  vocabulary: [
    { term: "Calipers", definition: "A sliding measuring tool that reads sizes far more precisely than a ruler." },
    { term: "Zero", definition: "Setting the display to 0.00 with the jaws closed, so readings start from nothing." },
    { term: "Outside jaws", definition: "The large lower jaws that close around an object to measure its outside." },
    { term: "Inside jaws", definition: "The small upper jaws that open inside a hole to measure its inside." },
    { term: "Depth rod", definition: "The thin rod that slides out of the end to measure how deep a hole or step is." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "0.5 mm is the difference between 'fits' and 'doesn't'.",
          hook: "A ruler gets you to about half a millimetre. Calipers read to 0.01 mm on the display, so you can see differences a ruler can't.",
          visual: { diagram: "caliper-parts" },
        },
        {
          id: "parts",
          type: "diagram",
          name: "caliper-parts",
          caption: "Outside jaws, inside jaws, depth rod, zero button and display.",
          alt: "Digital calipers with each part labelled.",
        },
        {
          id: "safety",
          type: "callout",
          tone: "safety",
          title: "Caliper care and safety",
          body: "The jaw tips are pointed: never point them at anyone or use them as a scribe. Close the jaws gently — never force or snap them. Don't measure anything hot, moving or wet. Keep them in their case and switch them off when you're done.",
        },
        {
          id: "show-me",
          type: "showMe",
          title: "Measure the peg",
          steps: [
            { text: "Switch on. Set units to mm.", diagram: "caliper-parts" },
            { text: "Wipe the jaws, close them gently, and press zero. The display reads 0.00." },
            { text: "Open the outside jaws, place the peg between them, and slide closed until both jaws just touch. Don't squeeze." },
            { text: "Keep the jaws square to the peg (not tilted) and read the display." },
            { text: "Measure twice more, turning the peg a little each time. Record all three with units." },
          ],
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You forget to zero. With the jaws closed, the display already reads 0.32 mm. You measure a peg and get 8.35 mm. What is the peg really?",
          options: [
            { id: "a", text: "8.03 mm" },
            { id: "b", text: "8.35 mm — the display is always right", misconceptionId: "skip-zero" },
            { id: "c", text: "8.67 mm", misconceptionId: "add-offset" },
          ],
          expectedOptionId: "a",
          reveal: "Every reading includes the starting error. 8.35 − 0.32 = 8.03 mm. Easier: close the jaws, press zero, and measure again.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        {
          id: "match-jaws",
          type: "matching",
          prompt: "Match each measurement to the part of the calipers you'd use.",
          pairs: [
            { id: "outside", left: "Width of a marker", right: "Outside jaws" },
            { id: "inside", left: "Inside of a bottle cap", right: "Inside jaws" },
            { id: "depth", left: "How deep a hole goes", right: "Depth rod" },
            { id: "zero", left: "Starting every session", right: "Zero button with jaws closed" },
          ],
          explanation: "Outside jaws close around things; inside jaws open inside things; the depth rod reaches down into things.",
          competencyId: "C4",
          check: "skill",
        },
        {
          id: "post-height",
          type: "measurement",
          prompt: "On the Mystery Fit Object, rest the end of the calipers on top of the base and use the depth rod (or the step) to measure how far the square post sticks up. What should it read?",
          visual: { modelId: "mystery-fit-object" },
          answer: 6,
          tolerance: 0.3,
          unit: "mm",
          hint: "The post is a 6 mm cube sitting on the base.",
          explanation: "The CAD size is 6 mm. A printed part may read 5.8–6.2 mm. Record what you actually measure.",
          competencyId: "C4",
          check: "practice",
        },
        {
          id: "peg-diameter",
          type: "measurement",
          prompt: "Measure the round peg's diameter with the outside jaws. Enter your reading.",
          visual: { modelId: "mystery-fit-object" },
          answer: 8,
          tolerance: 0.3,
          unit: "mm",
          hint: "Close the jaws until they just touch — squeezing makes plastic read small.",
          explanation: "The CAD size is 8.00 mm. Printed pegs often read slightly different. A reading within 0.3 mm is a normal printed result; compare it with your ruler reading from last lesson.",
          competencyId: "C4",
          check: "practice",
        },
        {
          id: "cube-check",
          type: "measurement",
          prompt: "Measure the Axis Cube on X, Y and Z. Enter your X reading.",
          visual: { modelId: "axis-cube-20mm" },
          answer: 20,
          tolerance: 0.4,
          unit: "mm",
          hint: "One notch = X.",
          explanation: "If X, Y and Z don't all read the same, your printer may be slightly off on one axis. That's calibration data — keep it for the Tolerances lesson.",
          competencyId: "C4",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          where: "offline",
          kind: "micro",
          title: "Outside, inside, depth",
          prompt: "Find one object in the class bin that has an outside, an inside and a depth to measure (a bottle cap, a tape roll, a pen cap). Measure all three, three times each.",
          requirements: ["Outside, inside and depth recorded", "Three readings each, with units", "Calipers zeroed before starting"],
          skills: ["C4"],
        },
        {
          id: "squeeze-mc",
          type: "multipleChoice",
          prompt: "Two students measure the same eraser. One gets 18.6 mm, the other 17.9 mm. What most likely explains the difference?",
          options: [
            { id: "a", text: "One student squeezed the jaws, squashing the soft eraser." },
            { id: "b", text: "Calipers give random numbers.", misconceptionId: "calipers-random" },
            { id: "c", text: "Erasers change size every minute." },
          ],
          correctOptionIds: ["a"],
          explanation: "Soft or flexible objects compress. Close the jaws until they just touch, and measure soft things more than once.",
          competencyId: "C4",
          check: "practice",
        },
        {
          id: "precision-mc",
          type: "multipleChoice",
          prompt: "The display shows 8.03 mm. How should you record it for a CAD design?",
          options: [
            { id: "a", text: "8.03 mm — then decide how much clearance to add when designing" },
            { id: "b", text: "8 — the decimals don't matter", misconceptionId: "drop-decimals" },
            { id: "c", text: "803", misconceptionId: "drop-decimals" },
          ],
          correctOptionIds: ["a"],
          explanation: "Record exactly what you measured, with units. Rounding and clearance are design decisions you make later, on purpose.",
          competencyId: "C4",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "both",
          kind: "prove",
          title: "Precision report",
          prompt: "Your teacher gives you an unfamiliar object. Using calipers only, record one outside, one inside and one depth measurement — three readings each — and model the object's measured features in Tinkercad. No steps.",
          requirements: [
            "Calipers zeroed (show the 0.00 display or explain how you checked)",
            "Outside, inside and depth each measured three times",
            "Readings recorded to 0.01 mm with units",
            "Tinkercad model uses your average measurements",
          ],
          skills: ["C4", "C3", "A9"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Model what you measured",
          steps: [
            "Create a new design.",
            "Model the features you measured using your averages.",
          ],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Upload a photo of your measurement table and a screenshot (or class design link) of your model.",
          accepts: ["screenshot", "design_url", "physical_test"],
          competencyIds: ["C4"],
          checklist: ["Outside, inside and depth all recorded", "Three readings each, with units", "Model dimensions match your averages"],
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Watch the student take one inside and one depth measurement.",
          lookFors: ["Zeroes with jaws closed before measuring", "Chooses the right jaws or rod without prompting", "Keeps the calipers square and doesn't squeeze", "Handles the calipers safely and closes them gently"],
          competencyIds: ["C4"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Compare a caliper reading with your ruler reading of the same thing. When is the ruler good enough, and when do you need calipers?",
          sentenceStarters: ["The ruler said… and the calipers said…", "I'd need calipers when…"],
          competencyIds: ["C4"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students zero and use digital calipers for outside, inside and depth measurements, compare precision with a ruler, and handle the tool safely.",
    preparation: [
      "Check every caliper turns on, reads in mm, and zeroes. Replace flat batteries (often an LR44/SR44 button cell — check your model).",
      "Print a few Axis Cubes and Mystery Fit Objects if you didn't for the previous lesson.",
      "Prepare unfamiliar objects with an outside, inside and depth (tape roll, bottle cap, pen cap, PVC fitting) for the prove challenge.",
    ],
    equipment: ["Digital calipers (one per pair is ideal)", "Printed Axis Cubes and Mystery Fit Objects (optional)", "Objects with inside and depth features", "Student devices with Tinkercad"],
    misconceptions: [
      { id: "skip-zero", text: "The display is always right, even without zeroing.", response: "Hand out a caliper deliberately not zeroed; have students find the error with the jaws closed." },
      { id: "add-offset", text: "A starting offset should be added to the reading.", response: "Ask: with nothing between the jaws, should it read 0.32? So the extra must be taken away." },
      { id: "calipers-random", text: "Different readings mean the calipers are unreliable.", response: "Have both students measure again with light pressure; readings converge. Technique causes most variation." },
      { id: "drop-decimals", text: "Decimals don't matter, or can be dropped/ignored.", response: "Show that 8 mm vs 8.4 mm is the difference between a press fit and a loose fit." },
    ],
    discussionQuestions: [
      "Why should you record exactly what you measured, even if you'll round later?",
      "What's the most precise tool you need for a cookie cutter? For a bottle cap?",
    ],
    printableObjects: ["Axis Cube 20 mm", "Mystery Fit Object"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls, no supports. Adjust for your printer. Measure one print yourself first so you know your printer's typical difference from CAD.",
    troubleshooting: [
      "Display jumps or won't zero: clean the beam with a dry cloth, then check the battery.",
      "Readings in inches: press the unit button (often labelled mm/in).",
      "Display shows a minus sign: it was zeroed while the jaws were open. Close them and zero again.",
      "Inside measurement reads too small: the inside jaws were tilted. Rock them gently to find the largest reading.",
    ],
    answerGuidance: [
      "Mystery Fit Object CAD sizes: peg 8.00 mm diameter, 12 mm tall; post 6 × 6 × 6 mm; base 34 × 22 × 10 mm. Printed parts usually read within a few tenths of a millimetre; differences depend on the printer and material.",
      "Accept readings that are consistent (three readings within about 0.1 mm for rigid objects) and recorded with units.",
    ],
    alternatives: {
      noCalipers:
        "Ruler-based version: measure to the nearest 0.5 mm with a steel ruler. For outside widths, press two square blocks against either side of the object and measure between the blocks. For round objects, wrap a paper strip once around, mark it, measure the length and divide by 3.14 for the diameter. For depth, lower a straight wire or toothpick into the hole, pinch it at the top edge, and measure the wire. For thin items, stack 10 and divide the total by 10. Students record three readings and note that ruler precision is about ±0.5 mm.",
      noPrinter: "Measure everyday objects and use the 3D viewer's dimensions for the Axis Cube and Mystery Fit Object.",
    },
  },
};
