import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "final-capstone",
  number: 38,
  title: "Capstone: Design for Someone Else",
  subtitle: "A real client, a real problem, a printed solution",
  domain: "G",
  kind: "capstone",
  summary: "Design, prototype, test, revise and deliver a printed object that solves a real problem for a real person — and document every step.",
  estimatedMinutes: 270,
  printLevel: "required",
  competencyIds: ["G1", "G2", "G3", "G4", "G5", "G6", "F10"],
  prerequisites: ["iteration"],
  vocabulary: [
    { term: "Client", definition: "The real person you are designing for." },
    { term: "Deliverable", definition: "The finished object you hand to your client." },
    { term: "Design journal", definition: "Your record of every step: user, problem, constraints, ideas, tests and changes." },
    { term: "Hand-off", definition: "Giving the client the product and watching it work in their real space." },
  ],
  sections: [
    {
      phase: "discover",
      title: "The brief",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "CAPSTONE: Design for Someone Else",
          hook: "Everything you've learned leads here. Find a real person with a real problem. Hand them a printed object that solves it.",
          visual: { diagram: "design-cycle" },
        },
        {
          id: "brief",
          type: "text",
          title: "Your client",
          body: "Choose one approved client:\n\n- a teacher\n- a student\n- a coach\n- a custodian\n- a librarian\n- a parent or guardian\n- an office employee\n- an elementary teacher\n\nIf you already interviewed someone in earlier lessons, keep going with them.",
        },
        {
          id: "permission",
          type: "callout",
          tone: "safety",
          title: "Permission and privacy",
          body: "Your teacher approves your client before you start. Use a role, not a full name, in your journal and uploads. Photograph the object, never faces.",
        },
        {
          id: "documentation",
          type: "text",
          title: "Required documentation",
          body: "Your journal must include: **User, Problem, Constraints, Ideas (at least 3), Prototype 1, Test, Revision, Final product, Reflection.** Entries from earlier lessons carry over — update them if they've changed.",
        },
        {
          id: "cycle",
          type: "diagram",
          name: "design-cycle",
          caption: "You will go around this loop at least once — most strong projects go around twice.",
          alt: "Design cycle: understand, define, ideate, prototype, test, revise.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Plan the work",
      blocks: [
        {
          id: "problem-mc",
          type: "multipleChoice",
          prompt: "Which capstone problem statement is clear enough to design for?",
          hint: "A clear problem names who, what goes wrong, and a number.",
          options: [
            { id: "a", text: "The custodian's 3 radio chargers fall behind the shelf, which is 25 mm from the wall, and take 5 minutes to fish out each morning." },
            { id: "b", text: "The custodian needs organization.", misconceptionId: "vague-problem" },
            { id: "c", text: "I'm going to make a phone case for the custodian.", misconceptionId: "solution-as-problem" },
          ],
          correctOptionIds: ["a"],
          explanation: "A clear problem names the user, what goes wrong, when, and gives you numbers. A product name is a solution, not a problem.",
          competencyId: "G2",
          check: "skill",
        },
        {
          id: "milestones",
          type: "ordering",
          prompt: "Put the capstone milestones in order.",
          hint: "You need a client before you can interview them, and a prototype before you can revise it.",
          items: [
            { id: "approve", text: "Teacher approves client" },
            { id: "interview", text: "Interview and measure" },
            { id: "define", text: "Write problem and constraints" },
            { id: "ideas", text: "Sketch three approaches and choose one" },
            { id: "proto", text: "Build and test prototype 1" },
            { id: "revise", text: "Revise and re-test" },
            { id: "final", text: "Print final product and hand off" },
            { id: "reflect", text: "Reflect and present" },
          ],
          explanation: "The final print comes late — after at least one test and revision. Printing early is the most common way to run out of time.",
          competencyId: "G4",
          check: "practice",
        },
        { id: "journal-research", type: "journal", projectKey: "capstone", promptIds: ["user", "problem", "constraints", "ideas", "first-idea", "why"] },
      ],
    },
    {
      phase: "apply",
      title: "Build, test, revise",
      blocks: [
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Build your capstone",
          steps: [
            "Open your capstone design (or start one) in your class Tinkercad space.",
            "Build from your measurements and constraints. Use exact values for critical dimensions.",
            "Print only the critical part first. Test it before the full print.",
            "Save a copy before each revision: v1, v2, v3.",
          ],
        },
        {
          id: "print-tip",
          type: "callout",
          tone: "tip",
          title: "Before the final print",
          body: "Check: orientation for strength, overhangs over 45°, wall thickness at least 2 mm, and one grouped model. Fix in CAD, not with supports, when you can.",
        },
        { id: "journal-build", type: "journal", projectKey: "capstone", promptIds: ["prototype", "test", "failed", "changed"] },
        {
          id: "checkpoint",
          type: "teacherCheck",
          prompt: "Checkpoint before approving the final print.",
          lookFors: [
            "Journal has user, problem, measurable constraints and three ideas",
            "At least one prototype tested with recorded results",
            "At least one revision linked to a test result",
            "Model is grouped and printable (orientation, overhangs, walls)",
          ],
          competencyIds: ["G2", "G3", "G4"],
        },
      ],
    },
    {
      phase: "prove",
      title: "Deliver",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "both",
          kind: "prove",
          title: "Design for Someone Else",
          prompt: "Deliver a printed object that solves your client's problem. Test it in their real space with them. Your journal tells the full story — including what failed.",
          requirements: [
            "Real, teacher-approved client",
            "At least four constraints, three or more measurable",
            "Three different ideas considered",
            "At least one prototype tested and revised from evidence",
            "Final print meets its critical dimensions and constraints",
            "Final product tested with the client in the real space",
            "Journal complete: user, problem, constraints, ideas, prototype 1, test, revision, final product, reflection",
          ],
          skills: ["G1", "G2", "G3", "G4", "G5", "G6", "F10"],
        },
        { id: "journal-final", type: "journal", projectKey: "capstone", promptIds: ["final"] },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your final design (class design link or STL) and a photo of the product in use in the client's space (object only, no faces).",
          accepts: ["design_url", "stl", "physical_test", "screenshot"],
          competencyIds: ["G4", "G5", "F10"],
          checklist: [
            "Final design file or link",
            "Photo of the product in the real space",
            "Critical dimensions visible in a screenshot",
            "Client's response recorded in the journal (role, not name)",
          ],
          allowPrintRequest: true,
        },
        {
          id: "handoff-check",
          type: "teacherCheck",
          prompt: "Confirm the hand-off.",
          lookFors: [
            "Object was delivered to the client",
            "Client used or tried it in the real space",
            "Student recorded the client's response honestly",
          ],
          competencyIds: ["G5"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        { id: "journal-next", type: "journal", projectKey: "capstone", promptIds: ["next"] },
        {
          id: "reflect",
          type: "reflection",
          prompt: "With another week, what would you change — and what evidence tells you that?",
          sentenceStarters: ["With another week I would…", "I know this because…", "My client said…"],
          minWords: 30,
          competencyIds: ["G6", "F10"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "The culminating project: students apply CAD, measurement, printability and the design process to deliver a working object for a real person, and document the full story.",
    preparation: [
      "Build and share a list of approved clients; brief them that students will interview, test and deliver within a few weeks.",
      "Set up a print queue with a deadline for final prints that leaves time for one reprint.",
      "Print the capstone rubric (24 pts) and share it on day 1.",
      "Plan 5–6 class periods: brief + research, ideas, prototype, test, revise, final print and hand-off.",
    ],
    equipment: ["Student devices with Tinkercad", "Ruler and calipers", "3D printer(s) and filament", "Paper, cardboard and tape for low-fidelity prototypes"],
    misconceptions: [
      { id: "vague-problem", text: "A general need like 'organization' is a problem statement.", response: "Ask: who, what goes wrong, when, and what are the numbers?" },
      { id: "solution-as-problem", text: "The problem is the object you want to make.", response: "Ask: what would your client say is annoying, before you mention any object?" },
    ],
    discussionQuestions: [
      "How did your client change your design from what you first imagined?",
      "Which test taught you the most?",
      "What would make your object last a year of daily use?",
    ],
    printableObjects: ["Prototype test slices (short prints)", "One final print per student, plus one reprint if a revision requires it"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15–20% infill, 3 walls for parts that carry load; orient for layer strength and minimal support. Adjust for your printer and each design.",
    troubleshooting: [
      "If a student is stuck on choosing a client, assign one from the approved list and arrange a 10-minute interview.",
      "If the problem is too big, zoom into one moment ('where the keys go when she locks up').",
      "If time is short, accept a final print of the critical part plus a digital model of the rest, and score accordingly.",
      "If a final print fails, the failure and reprint plan go in the journal — it counts as testing evidence.",
    ],
    answerGuidance: [
      "Score with the capstone rubric (24 pts): CAD Construction, Dimensional Accuracy, Design for Additive Manufacturing, Problem Solving, Testing & Iteration, Communication — 4 points each.",
      "Testing & Iteration at 4 requires at least one test that drove a documented revision.",
      "A product that didn't fully work can still score well if testing, revision and reflection are honest and specific.",
    ],
    rubricId: "capstone",
    alternatives: {
      noPrinter: "Deliver a full-size cardboard or paper prototype plus the final Tinkercad design and a print-ready STL. Partner with a library or another school to print the final if possible.",
      noCalipers: "Measure with a ruler to the nearest 0.5 mm and design in extra clearance; test with a printed slice.",
      touchDevice: "Use on-screen tools for Group, Hole and Ruler; photograph handwritten sketches for the journal.",
    },
  },
};
