// GENERATED by scripts/build-lesson-index.ts — do not edit by hand.
import type { LessonInput } from "../schema";
import { lesson as l_align } from "./align";
import { lesson as l_boss_nametag } from "./boss-nametag";
import { lesson as l_bridging } from "./bridging";
import { lesson as l_cad_er } from "./cad-er";
import { lesson as l_calipers } from "./calipers";
import { lesson as l_duplicate } from "./duplicate";
import { lesson as l_exact_dimensions } from "./exact-dimensions";
import { lesson as l_final_capstone } from "./final-capstone";
import { lesson as l_grouping } from "./grouping";
import { lesson as l_holes } from "./holes";
import { lesson as l_interviewing_a_user } from "./interviewing-a-user";
import { lesson as l_iteration } from "./iteration";
import { lesson as l_layers } from "./layers";
import { lesson as l_make_it_fit } from "./make-it-fit";
import { lesson as l_maker_showcase } from "./maker-showcase";
import { lesson as l_material_efficiency } from "./material-efficiency";
import { lesson as l_measuring_real_objects } from "./measuring-real-objects";
import { lesson as l_mini_design_sprint } from "./mini-design-sprint";
import { lesson as l_mirror } from "./mirror";
import { lesson as l_moving_objects } from "./moving-objects";
import { lesson as l_navigating_tinkercad } from "./navigating-tinkercad";
import { lesson as l_orientation } from "./orientation";
import { lesson as l_overhangs } from "./overhangs";
import { lesson as l_print_detective } from "./print-detective";
import { lesson as l_print_failures } from "./print-failures";
import { lesson as l_product_design } from "./product-design";
import { lesson as l_prototype } from "./prototype";
import { lesson as l_repeat_duplicate } from "./repeat-duplicate";
import { lesson as l_rotating_objects } from "./rotating-objects";
import { lesson as l_ruler } from "./ruler";
import { lesson as l_scaling_objects } from "./scaling-objects";
import { lesson as l_strength } from "./strength";
import { lesson as l_supports } from "./supports";
import { lesson as l_testing } from "./testing";
import { lesson as l_text } from "./text";
import { lesson as l_tolerances } from "./tolerances";
import { lesson as l_what_is_3d_printing } from "./what-is-3d-printing";
import { lesson as l_workplanes } from "./workplanes";
import { lesson as l_workspace_rescue } from "./workspace-rescue";
import { lesson as l_writing_constraints } from "./writing-constraints";

/** Every lesson in the canonical curriculum. `number` sets display order. */
export const lessonInputs: LessonInput[] = [
  l_align,
  l_boss_nametag,
  l_bridging,
  l_cad_er,
  l_calipers,
  l_duplicate,
  l_exact_dimensions,
  l_final_capstone,
  l_grouping,
  l_holes,
  l_interviewing_a_user,
  l_iteration,
  l_layers,
  l_make_it_fit,
  l_maker_showcase,
  l_material_efficiency,
  l_measuring_real_objects,
  l_mini_design_sprint,
  l_mirror,
  l_moving_objects,
  l_navigating_tinkercad,
  l_orientation,
  l_overhangs,
  l_print_detective,
  l_print_failures,
  l_product_design,
  l_prototype,
  l_repeat_duplicate,
  l_rotating_objects,
  l_ruler,
  l_scaling_objects,
  l_strength,
  l_supports,
  l_testing,
  l_text,
  l_tolerances,
  l_what_is_3d_printing,
  l_workplanes,
  l_workspace_rescue,
  l_writing_constraints,
];
