import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "interviewing-a-user",
  number: 33,
  title: "Interviewing a User",
  subtitle: "Ask good questions, then really listen",
  domain: "G",
  kind: "lesson",
  summary: "Plan respectful interview questions, get permission, listen for the real problem and record what you learn without collecting personal data.",
  estimatedMinutes: 50,
  printLevel: "digital",
  competencyIds: ["G1", "F7", "F1"],
  prerequisites: ["product-design"],
  vocabulary: [
    { term: "Client", definition: "The real person you are designing for." },
    { term: "Open question", definition: "A question that can't be answered with yes or no. 'Tell me about…'" },
    { term: "Follow-up question", definition: "A question that digs deeper into what someone just said." },
    { term: "Consent", definition: "Clear permission from a person before you interview them or use what they said." },
    { term: "Personal data", definition: "Anything that identifies someone: full name, face, address, phone number." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Your client knows things you don't.",
          hook: "You think the librarian needs a bigger book stand. After five minutes of listening, you learn the real problem: returned books slide off the cart. Different problem, different design.",
          visual: { diagram: "design-cycle" },
        },
        {
          id: "explain",
          type: "text",
          body: "An interview is how you **understand** before you design. Your job is to ask, listen and take notes — not to pitch your idea.",
        },
        {
          id: "permission",
          type: "callout",
          tone: "safety",
          title: "Permission and respect come first",
          body: "Get your teacher's OK before you interview any adult. Interview at school, during class time. Ask the person if they agree, and tell them how you'll use their answers.",
        },
        {
          id: "privacy",
          type: "callout",
          tone: "warning",
          title: "No personal data in your journal or uploads",
          body: "Write a role, not a name: 'the school librarian', not their full name. No photos of people's faces. No phone numbers or addresses.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You ask: 'Would a phone holder help you?' The custodian says 'Sure.' What did you learn?",
          options: [
            { id: "a", text: "Almost nothing — yes/no questions invite polite answers." },
            { id: "b", text: "That a phone holder is definitely the right product.", misconceptionId: "yes-means-need" },
            { id: "c", text: "Exactly how big the holder should be." },
          ],
          expectedOptionId: "a",
          reveal: "People often say yes to be kind. 'Tell me about the last time your phone got in the way at work' would have told you what actually happens.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Better questions",
      blocks: [
        {
          id: "match-questions",
          type: "matching",
          prompt: "Match each weak question to a stronger version.",
          pairs: [
            { id: "q1", left: "Do you like my idea?", right: "What's the most annoying part of your day at the front desk?" },
            { id: "q2", left: "Is it hard to carry the keys?", right: "Walk me through what you do with your keys when you lock up." },
            { id: "q3", left: "Do you want it blue?", right: "Where would this object sit or hang?" },
            { id: "q4", left: "Is it big?", right: "Can I measure the space where it needs to fit?" },
          ],
          explanation: "Strong questions are open, are about what really happens, and gather numbers you can design with.",
          competencyId: "F7",
          check: "practice",
        },
        {
          id: "follow-up-mc",
          type: "multipleChoice",
          prompt: "The office employee says: 'The tape dispenser always ends up buried under papers.' What is the best next thing to say?",
          options: [
            { id: "a", text: "'Tell me more — when does it get buried, and what do you do to find it?'" },
            { id: "b", text: "'I could print you a tape dispenser!'", misconceptionId: "pitch-too-early" },
            { id: "c", text: "'OK, next question.'", misconceptionId: "script-only" },
          ],
          correctOptionIds: ["a"],
          explanation: "A follow-up question digs into the moment the problem happens. Pitching now stops the person from telling you more.",
          competencyId: "F7",
          check: "skill",
        },
        {
          id: "order-interview",
          type: "ordering",
          prompt: "Put the interview in a respectful order.",
          items: [
            { id: "teacher-ok", text: "Get your teacher's permission" },
            { id: "ask", text: "Introduce yourself and ask if they agree to a short interview" },
            { id: "open", text: "Ask open questions about their routine" },
            { id: "follow", text: "Ask follow-up questions about the problem" },
            { id: "measure", text: "Ask to see and measure the space or object" },
            { id: "thank", text: "Read back your notes and thank them" },
          ],
          explanation: "Permission first, measurements near the end, and reading back your notes checks that you understood correctly.",
          competencyId: "G1",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Rehearse",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          where: "offline",
          kind: "micro",
          title: "Practice interview",
          prompt: "Write six interview questions. Then interview a partner for 5 minutes about a problem in their backpack, locker or desk. Swap roles.",
          requirements: [
            "At least four open questions",
            "At least one question that asks for a measurement",
            "At least two follow-up questions asked during the interview",
            "Notes use a role or first name only",
          ],
          skills: ["F7", "G1"],
        },
        {
          id: "rehearsal-check",
          type: "teacherCheck",
          prompt: "Observe one practice interview per pair.",
          lookFors: [
            "Asks open questions, not mostly yes/no",
            "Asks at least one follow-up",
            "Listens without pitching a solution",
            "Takes notes, including a measurement",
          ],
          competencyIds: ["F7"],
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "offline",
          kind: "prove",
          title: "Interview your client",
          prompt: "With your teacher's permission, interview your capstone client for about 10 minutes. Find one problem you could solve with a printed object. Bring back at least two measurements.",
          requirements: [
            "Teacher approved the client before the interview",
            "Client agreed to be interviewed",
            "At least three open questions and two follow-ups",
            "At least two real measurements with units",
            "One-sentence problem statement written from what you heard",
            "No full names, faces or contact details recorded",
          ],
          skills: ["G1", "F7", "F1"],
        },
        { id: "journal", type: "journal", projectKey: "capstone", promptIds: ["user", "problem"] },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Upload a photo or screenshot of your interview notes. Cover or remove any names.",
          accepts: ["screenshot"],
          competencyIds: ["G1", "F7", "F1"],
          checklist: ["Questions and answers are visible", "Includes at least two measurements", "No full names, faces or contact details"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "What did your client say that surprised you or changed what you planned to design?",
          sentenceStarters: ["I expected…, but they said…", "This changes my design because…"],
          competencyIds: ["G1", "F1"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students learn to gather real requirements from a real person, respectfully and safely, and to separate the real problem from their first idea.",
    preparation: [
      "Pre-approve a list of willing adults (staff, coaches, librarian, custodian, office employees, elementary teachers) and tell them to expect a short student interview.",
      "Decide how students will reach clients during the school day (scheduled times, escorted visits or the client visiting class).",
      "Model one interview in front of the class, including asking permission and a follow-up question.",
    ],
    equipment: ["Notebook or interview template", "Ruler or tape measure", "Student devices for journal entries"],
    misconceptions: [
      { id: "yes-means-need", text: "If a client says yes to an idea, the idea is right.", response: "Point out that people are polite. Ask for stories about what happens, not opinions about an idea." },
      { id: "pitch-too-early", text: "Interviews are for selling your idea.", response: "Set a rule: no solutions until the last two minutes." },
      { id: "script-only", text: "A good interview means reading your questions in order.", response: "Model a follow-up: 'You said it gets buried — tell me more about that.'" },
    ],
    discussionQuestions: [
      "Why would a designer read their notes back to the client?",
      "What should you do if your client's problem is too big to solve with one printed object?",
      "Why do we write a role instead of a full name?",
    ],
    troubleshooting: [
      "If a client can't think of a problem, ask them to walk you through their morning or show you their workspace.",
      "If a student's client is unavailable, assign a backup from the approved list or let them interview a family member at home with a parent/guardian's knowledge, using the same privacy rules.",
      "If the problem is too big (a new desk), help them zoom in on one part of it (where the cable goes).",
    ],
    answerGuidance: [
      "Strong problem statement: 'The school librarian's returned books slide off the cart's 30 cm shelf when she pushes it over the doorway bump.'",
      "Proficient interviews include at least two follow-ups and two measurements with units.",
      "Check uploads for names, faces and contact details before approving.",
    ],
    alternatives: {
      touchDevice: "Students can photograph handwritten notes for the upload.",
    },
  },
};
