import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "jr-boss-bookmark",
  number: 108,
  title: "Boss Battle: Name Bookmark",
  subtitle: "Five rules. Your design.",
  domain: "B",
  kind: "boss",
  summary: "Design your own name bookmark that passes five rules, check it with a partner, fix one thing and print it.",
  estimatedMinutes: 30,
  printLevel: "required",
  competencyIds: ["A9", "B2", "B3", "B10", "E1"],
  prerequisites: ["jr-words"],
  vocabulary: [
    { term: "Boss battle", definition: "A big challenge with no step-by-step help. You use everything you learned." },
    { term: "Check", definition: "Look at your design and make sure it follows every rule." },
  ],
  sections: [
    {
      phase: "discover",
      title: "The mission",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Design your bookmark",
          hook: "Make a bookmark with your name. It has to pass five rules. How it looks is up to you!",
          visual: { modelId: "bookmark-good" },
        },
        {
          id: "rules",
          type: "text",
          body: "**Your bookmark must:**\n\n1. **Fit** inside 150 × 40 mm.\n2. Be **2 mm** thick.\n3. Have your name **raised 1 mm**, letters at least **8 mm** tall, **touching** the bookmark.\n4. Have a **tassel hole** at least 5 mm wide, with 3 mm of plastic around it.\n5. Be **grouped** into one piece.",
        },
        {
          id: "tip",
          type: "callout",
          tone: "idea",
          title: "Make it yours",
          body: "Add shapes, stars, hearts or a design on the end. Just keep the five rules.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Warm up",
      blocks: [
        {
          id: "which-rule",
          type: "matching",
          prompt: "Match each problem to the rule it breaks.",
          hint: "Read the five rules again.",
          pairs: [
            { id: "p1", left: "The bookmark is 180 mm long", right: "Rule 1: fit inside 150 × 40 mm" },
            { id: "p2", left: "The letters float above it", right: "Rule 3: letters touching" },
            { id: "p3", left: "The hole is at the very edge", right: "Rule 4: 3 mm of plastic around the hole" },
            { id: "p4", left: "The star isn't grouped", right: "Rule 5: one piece" },
          ],
          explanation: "These are the things to check before you submit.",
          competencyId: "E1",
          check: "practice",
        },
        {
          id: "hole-check",
          type: "measurement",
          prompt: "Your tassel hole is 6 mm wide. You need 3 mm of plastic on each side of it. How wide must the bookmark be there, at least?",
          answer: 12,
          tolerance: 0,
          unit: "mm",
          hint: "3 mm + the 6 mm hole + 3 mm.",
          explanation: "3 + 6 + 3 = 12 mm.",
          competencyId: "B3",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Boss battle",
      blocks: [
        {
          id: "boss",
          type: "challenge",
          kind: "boss",
          title: "The Name Bookmark",
          prompt: "Design your bookmark in Tinkercad. Check all five rules. Ask a partner to check too. Fix one thing that could be better.",
          requirements: [
            "Fits inside 150 × 40 mm",
            "2 mm thick",
            "Name raised 1 mm, 8 mm+ tall, touching",
            "Tassel hole 5 mm+ with 3 mm around it",
            "Grouped into one piece",
          ],
          skills: ["A9", "B2", "B3", "B10"],
          showTimer: false,
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Share your bookmark. Upload a screenshot or the design link, then ask for a print.",
          accepts: ["screenshot", "design_url", "stl"],
          competencyIds: ["A9", "B2", "B3", "B10"],
          checklist: ["Rule 1: fits 150 × 40 mm", "Rule 2: 2 mm thick", "Rule 3: letters raised, big and touching", "Rule 4: hole with space around it", "Rule 5: grouped", "My partner checked it"],
          allowPrintRequest: true,
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Check the bookmark before printing.",
          lookFors: ["Within 150 × 40 mm and 2 mm thick", "Letters 8 mm+ tall, raised 1 mm and touching", "Tassel hole 5 mm+ with 3 mm margin", "One grouped piece"],
          competencyIds: ["B3", "B10"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Think about it",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "What did you fix after checking? What would you change next time?",
          sentenceStarters: ["I fixed… because…", "Next time I would…"],
          competencyIds: ["E1"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "The capstone of the starter unit: students design to a short spec, check it themselves and with a partner, and improve one thing before printing.",
    preparation: [
      "Plan printer time about a week ahead: each bookmark takes roughly 20–25 minutes, so a class of 25 is about 8–10 hours. Plate 4–6 at once or print overnight.",
      "Print one bookmark-good as an example to pass around.",
      "Optional: yarn for tassels.",
    ],
    equipment: ["Chromebooks", "The sample bookmark", "Optional: yarn"],
    misconceptions: [],
    discussionQuestions: ["How did your partner's check help you?", "What is one thing every bookmark needs, no matter how it looks?"],
    printableObjects: ["bookmark-good (example)", "One bookmark per student"],
    slicerSettings: "PLA, 0.2 mm layers, 15% infill, flat on the plate. A color change at 2 mm makes the letters pop.",
    troubleshooting: ["If letters print as blobs, they're under 8 mm tall.", "If letters pop off, they weren't touching: lift them to exactly 2 mm."],
    answerGuidance: ["Hole margin: 3 + 6 + 3 = 12 mm.", "Accept any creative design that meets the five rules."],
  },
};
