import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "jr-move-stretch",
  number: 103,
  title: "Move, Stretch, Lift",
  subtitle: "Make shapes the size you want",
  domain: "A",
  kind: "lesson",
  summary: "Move shapes, change their size by typing numbers, and lift them off the workplane.",
  estimatedMinutes: 30,
  printLevel: "digital",
  competencyIds: ["A6", "A7", "A8", "A9"],
  prerequisites: ["jr-meet-tinkercad"],
  vocabulary: [
    { term: "Millimeter (mm)", definition: "A tiny unit of length. 10 mm is about as wide as your fingernail." },
    { term: "Length, width, height", definition: "How long, how wide and how tall a shape is." },
    { term: "Lift", definition: "Raise a shape up off the workplane." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Size by number",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Exactly the right size",
          hook: "Designers don't guess sizes. They type the number they want. Today you will too.",
          visual: { diagram: "exact-dimension", alt: "A box with its size numbers showing beside each side." },
        },
        {
          id: "how",
          type: "showMe",
          title: "Change the size",
          steps: [
            { text: "Click a shape. White squares appear on its corners.", diagram: "scale-handles" },
            { text: "Click a size number next to the shape. Type a new number and press Enter.", diagram: "exact-dimension" },
            { text: "To move a shape a little, click it and press the arrow keys.", diagram: "nudge-keys", keys: "← ↑ → ↓" },
            { text: "To lift it, drag the black cone on top, or press Ctrl + ↑.", diagram: "move-z" },
          ],
        },
        {
          id: "mm",
          type: "callout",
          tone: "tip",
          title: "How big is a millimeter?",
          body: "10 mm is about as wide as your fingernail. 100 mm is about as long as a crayon.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        {
          id: "box-width",
          type: "measurement",
          prompt: "You want a box 40 mm long. You typed 40. Then you made it twice as long. How long is it now?",
          answer: 80,
          tolerance: 0,
          unit: "mm",
          hint: "Twice as long means 40 + 40.",
          explanation: "40 + 40 = 80 mm.",
          competencyId: "A9",
          check: "practice",
        },
        {
          id: "lift",
          type: "multipleChoice",
          prompt: "Your shape is sitting on the workplane. You want it to float 10 mm above it. What do you do?",
          hint: "Look for the black cone on top of the shape.",
          options: [
            { id: "a", text: "Drag the black cone up, or type 10 in its box." },
            { id: "b", text: "Make the shape 10 mm taller.", misconceptionId: "taller-is-lift" },
            { id: "c", text: "Press Delete.", misconceptionId: "delete" },
          ],
          correctOptionIds: ["a"],
          explanation: "The black cone lifts a shape. Making it taller does not lift it: the bottom stays on the workplane.",
          competencyId: "A7",
          check: "skill",
        },
        {
          id: "size-check",
          type: "multipleChoice",
          prompt: "Which is the best way to make a box exactly 20 mm wide?",
          hint: "Guessing by dragging is hard to get exact.",
          options: [
            { id: "a", text: "Click the width number, type 20, press Enter." },
            { id: "b", text: "Drag a corner until it looks right.", misconceptionId: "eyeball" },
          ],
          correctOptionIds: ["a"],
          explanation: "Typing the number makes it exact every time.",
          competencyId: "A9",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Show what you can do",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Box builder",
          prompt: "Make a box that is 40 mm long, 20 mm wide and 5 mm tall. Then make a cylinder and lift it 10 mm above the box.",
          requirements: ["Box: 40 × 20 × 5 mm", "Cylinder lifted 10 mm", "Sizes typed, not guessed"],
          skills: ["A7", "A9"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Take a screenshot with the box selected so its sizes show.",
          accepts: ["screenshot", "design_url"],
          competencyIds: ["A7", "A9"],
          checklist: ["The box shows 40, 20 and 5", "The cylinder floats above the box"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Think about it",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Why is typing a size better than guessing?",
          sentenceStarters: ["Typing is better because…"],
          competencyIds: ["A9"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students control size and position with numbers, using whole millimeters only.",
    preparation: ["Bring a ruler to show 10 mm and 100 mm.", "On trackpads, students should use typed sizes and the arrow keys instead of dragging."],
    equipment: ["Chromebooks", "A ruler for the demo"],
    misconceptions: [
      { id: "taller-is-lift", text: "Making a shape taller lifts it.", response: "Show both side by side: a taller shape still touches the workplane." },
      { id: "delete", text: "Delete moves a shape.", response: "Remind students Delete removes, and Undo brings it back." },
      { id: "eyeball", text: "Dragging is exact enough.", response: "Have two students drag to 20 mm without looking at the number, then compare." },
    ],
    discussionQuestions: ["When would a designer need an exact size? (A lid, a case, a part that fits something)"],
    troubleshooting: ["If the size boxes don't show, the shape isn't selected. Click it once.", "If a shape sinks below the workplane, press D to drop it back down."],
    answerGuidance: ["Twice as long: 80 mm.", "Box builder: 40 × 20 × 5 mm box, cylinder lifted 10 mm."],
  },
};
