import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "layers",
  number: 23,
  title: "Layers",
  subtitle: "How the printer sees your design",
  domain: "D",
  kind: "lesson",
  summary: "See how a slicer cuts a design into layers, calculate layer counts, and design heights that line up with the layers.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["D1"],
  prerequisites: ["make-it-fit"],
  vocabulary: [
    { term: "Layer", definition: "One thin horizontal slice of a print, laid down in a single pass." },
    { term: "Layer height", definition: "How thick each layer is, for example 0.2 mm." },
    { term: "Slicer", definition: "Software that cuts a 3D model into layers and tells the printer where to move." },
    { term: "Layer line", definition: "The small ridge you can see and feel where one layer sits on another." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Slices of plastic",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Your printer can't print a cube.",
          hook: "It can only print one flat slice at a time — then the next one on top. A 20 mm cube is really about 100 thin pancakes of plastic.",
          visual: { diagram: "layers-stack" },
        },
        {
          id: "explain",
          type: "text",
          body: "A **slicer** cuts your model into horizontal layers. The printer draws each layer, moves up by one **layer height**, and draws the next. Everything about printing — time, strength, overhangs — comes back to layers.",
        },
        { id: "viewer", type: "modelViewer", modelId: "axis-cube-20mm", caption: "Drag the layer slider to build the cube one layer at a time.", showLayers: true },
        {
          id: "predict",
          type: "prediction",
          prompt: "You switch from 0.2 mm layers to 0.1 mm layers. What happens to print time?",
          options: [
            { id: "a", text: "About the same — the object is the same size", misconceptionId: "time-same" },
            { id: "b", text: "Roughly double — twice as many layers to draw" },
            { id: "c", text: "Half — thinner layers are faster", misconceptionId: "thin-faster" },
          ],
          expectedOptionId: "b",
          reveal: "Half the layer height means about twice as many layers, and each layer takes about as long. Thinner layers look smoother but take much longer. Exact times depend on the printer and slicer.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Count the layers",
      blocks: [
        {
          id: "slide-layers",
          type: "slider",
          prompt: "This dome is 20 mm tall. Pick the layer height that prints it in exactly **50 layers**. Watch the print time and the steps as you slide.",
          scene: "layers",
          min: 0.1,
          max: 0.4,
          step: 0.05,
          start: 0.1,
          unit: "mm",
          answer: 0.4,
          tolerance: 0.001,
          hint: "Layers × layer height = total height. What times 50 makes 20?",
          explanation: "20 ÷ 50 = **0.4 mm**. Thick layers print fast but leave big steps on curves. Thin layers look smooth but take longer.",
          competencyId: "D1",
        },
        {
          id: "count-20",
          type: "measurement",
          prompt: "A 20 mm tall cube prints at 0.2 mm layer height. How many layers?",
          answer: 100,
          tolerance: 0,
          unit: "layers",
          hint: "Height ÷ layer height.",
          explanation: "20 ÷ 0.2 = 100 layers.",
          competencyId: "D1",
          check: "practice",
        },
        {
          id: "count-feature",
          type: "measurement",
          prompt: "A tag has a 3 mm base with 1.2 mm raised letters on top. At 0.2 mm layers, which layer number is the FIRST layer of the letters?",
          answer: 16,
          tolerance: 0,
          unit: "layer",
          hint: "How many layers does the 3 mm base take? The letters start on the next one.",
          explanation: "3 ÷ 0.2 = 15 layers of base, so the letters begin on layer 16. Slicers let you pause or change colour at a layer like this.",
          competencyId: "D1",
          check: "practice",
        },
        {
          id: "mc-small",
          type: "multipleChoice",
          prompt: "You design a raised detail only 0.1 mm tall, and print at 0.2 mm layers. What is most likely to happen?",
          hint: "Compare the detail's height with one layer's height.",
          options: [
            { id: "a", text: "It may disappear or print unevenly — it's thinner than one layer." },
            { id: "b", text: "It prints exactly 0.1 mm tall.", misconceptionId: "any-height-prints" },
            { id: "c", text: "The printer automatically switches to 0.1 mm layers." },
          ],
          correctOptionIds: ["a"],
          explanation: "The printer can only build in whole layers. Details smaller than one layer height get rounded away or come out rough. Design heights in multiples of your layer height.",
          competencyId: "D1",
          check: "skill",
        },
        {
          id: "mc-lines",
          type: "multipleChoice",
          prompt: "Why can you feel tiny ridges on the side of a print?",
          hint: "A print is a stack of thin slices. What does the edge of each slice feel like?",
          options: [
            { id: "a", text: "Each ridge is the edge of one layer stacked on the one below." },
            { id: "b", text: "The nozzle scratched the print.", misconceptionId: "lines-are-damage" },
            { id: "c", text: "The model had ridges in Tinkercad." },
          ],
          correctOptionIds: ["a"],
          explanation: "Layer lines are a normal fingerprint of layer-by-layer printing. Thinner layers make them smaller, not gone.",
          competencyId: "D1",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "See it on a real part",
      blocks: [
        { id: "hook-viewer", type: "modelViewer", modelId: "orientation-hook", caption: "Slide through the hook's layers. Where is the narrowest layer? You'll need this next lesson.", showLayers: true },
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Layer-friendly heights",
          prompt: "In Tinkercad, build a 30 × 30 mm coaster whose base and raised rim both land exactly on 0.2 mm layers.",
          requirements: ["Base 2.4 mm thick (12 layers)", "Rim 1.6 mm taller than the base (8 more layers)", "Every height is a multiple of 0.2 mm"],
          skills: ["D1", "A9"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Build the coaster",
          steps: [
            "Create a new design.",
            "Click each height value and type it exactly — 2.4, then 4.0 for the rim.",
            "Turn off Snap Grid or set it to 0.1 mm so heights don't jump.",
          ],
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Two-colour name tag",
          prompt: "Design a name tag that a teacher could print in two colours by pausing at one layer to swap filament. You choose the shape and size.",
          requirements: [
            "Base thickness is a multiple of 0.2 mm (between 2 and 4 mm)",
            "Raised text or symbol at least 1.0 mm tall, also a multiple of 0.2 mm",
            "State the total layer count and the exact layer number where the colour swap happens",
            "Single grouped model",
          ],
          skills: ["D1", "B10", "A9"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your tag with a screenshot showing its heights, plus your layer math: total layers and the swap layer.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["D1"],
          checklist: ["Heights visible", "Total layer count shown with math", "Swap layer number stated"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Explain to a younger student how a 3D printer turns a design into an object. Use the word \"layer\".",
          sentenceStarters: ["First the slicer…", "Then the printer…", "Thinner layers mean…"],
          competencyIds: ["D1"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students build a working mental model of layer-by-layer printing that every later print-engineering lesson (orientation, strength, overhangs) depends on.",
    preparation: [
      "Optional: open the class slicer and slice the Axis Cube to show the layer preview live.",
      "Optional: have a few printed objects for students to feel layer lines.",
    ],
    equipment: ["Student devices with Tinkercad", "Optional: projector with slicer software", "Optional: sample prints"],
    misconceptions: [
      { id: "time-same", text: "Layer height doesn't affect print time.", response: "Slice the same model at 0.3, 0.2 and 0.1 mm and compare the estimated times on the board." },
      { id: "thin-faster", text: "Thinner layers print faster.", response: "Ask: if each pancake is thinner, how many more pancakes do you need for the same stack?" },
      { id: "any-height-prints", text: "Any height in CAD will print exactly.", response: "Show the slicer layer preview of a 0.1 mm detail at 0.2 mm layers." },
      { id: "lines-are-damage", text: "Layer lines are damage or a mistake.", response: "Every FDM print has them. They're evidence of how it was built — Print Detective clues." },
    ],
    discussionQuestions: ["When would you choose thin layers? When thick?", "What everyday objects are made in layers?"],
    troubleshooting: ["If heights won't type as 2.4, check that units are millimetres and Snap Grid isn't rounding."],
    answerGuidance: [
      "Prediction: b (about double).",
      "Counts: 100 layers; letters start at layer 16.",
      "Prove: e.g. 3.0 mm base + 1.2 mm text = 21 layers total, swap at the start of layer 16.",
    ],
    alternatives: {
      noPrinter: "This lesson is fully digital. Use the layer slider and slicer preview instead of real prints.",
      touchDevice: "Tap a dimension value to type exact heights.",
    },
  },
};
