import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "make-it-fit",
  number: 22,
  title: "Make It Fit",
  subtitle: "Design a part for a real object — and test only what matters",
  domain: "C",
  kind: "challenge",
  summary: "Measure a real object, design a part that fits it using your class clearance, and print only the interface first.",
  estimatedMinutes: 55,
  printLevel: "required",
  competencyIds: ["C7", "C8", "C10", "E2"],
  prerequisites: ["tolerances"],
  vocabulary: [
    { term: "Interface", definition: "The part of a design where it touches or connects to something else." },
    { term: "Critical dimension", definition: "The measurement that must be right for the part to work." },
    { term: "Test piece", definition: "A small print that contains only the feature you are testing." },
    { term: "Mating parts", definition: "Two parts designed to fit together." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Real objects, real fits",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Don't print the whole design when you're only testing one dimension.",
          hook: "A marker cap that takes 3 hours to print and doesn't fit is 3 hours lost. A 10-minute ring that tests just the fit tells you the same thing.",
          visual: { diagram: "prototype-critical" },
        },
        {
          id: "explain",
          type: "text",
          body: "Every fitted part has an **interface** — the surface that touches the real object. Measure it, add your class clearance, then print **only the interface** as a thin test piece. Fix the fit first. Print the full design last.",
        },
        { id: "critical", type: "diagram", name: "measure-critical", caption: "Find the dimension that must fit. That is the one you test.", alt: "A real object with its critical dimension (the one that must fit) highlighted." },
        {
          id: "predict-test",
          type: "prediction",
          prompt: "You're designing a 60 mm tall holder that clips onto a 19 mm marker. What should you print first?",
          options: [
            { id: "a", text: "The whole 60 mm holder, to see how it looks", misconceptionId: "print-whole-first" },
            { id: "b", text: "A 5 mm tall ring with the same clip opening" },
            { id: "c", text: "Nothing — if the numbers are right it will fit", misconceptionId: "math-guarantees-fit" },
          ],
          expectedOptionId: "b",
          reveal: "The ring tests the only dimension that can fail — the clip opening — in a fraction of the time and plastic. If it's too tight, change one number and reprint the ring.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Measure → design → test",
      blocks: [
        {
          id: "show-me",
          type: "showMe",
          title: "From object to test piece",
          steps: [
            { text: "Find the critical dimension. Measure it at least twice in different places. Write it down with units.", diagram: "measure-critical" },
            { text: "Add your class clearance from the Fit Lab. Example: 19.0 mm marker + 0.4 mm = 19.4 mm hole.", diagram: "clearance-fit" },
            { text: "Design the interface in Tinkercad: a short ring, plate or socket with only that hole or slot.", diagram: "group-hole" },
            { text: "Print the test piece. Try it on the real object. Rate the fit.", diagram: "prototype-critical" },
            { text: "Too tight or too loose? Change one number, reprint, test again. Record every try." },
          ],
        },
        {
          id: "math-check",
          type: "measurement",
          prompt: "A AA battery measures 14.2 mm across. Your class clearance is 0.4 mm. What hole diameter should the test piece have?",
          answer: 14.6,
          tolerance: 0.05,
          unit: "mm",
          hint: "Measured size + class clearance.",
          explanation: "14.2 + 0.4 = 14.6 mm. Use your own class clearance — this number is just an example.",
          competencyId: "C8",
          check: "practice",
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Warm-up: cap the Mystery Fit Object",
          steps: [
            "Download and import the Mystery Fit Object.",
            "Use the ruler to read the size of its round peg.",
            "Design a 4 mm tall ring that would slide over the peg using your class clearance.",
          ],
        },
        { id: "files", type: "modelDownload", modelIds: ["mystery-fit-object"], showImportSteps: true },
      ],
    },
    {
      phase: "apply",
      title: "Debug the fit",
      blocks: [
        {
          id: "slide-fit",
          type: "slider",
          prompt: "Your class test says **0.15 mm per side** gives a good fit. The peg is 10.0 mm. How big should the hole be?",
          scene: "clearance",
          min: 10,
          max: 11,
          step: 0.05,
          start: 10,
          unit: "mm",
          answer: 10.3,
          tolerance: 0.01,
          hint: "The gap is on BOTH sides of the peg.",
          explanation: "10.0 + 0.15 + 0.15 = **10.3 mm**.",
          competencyId: "C8",
        },
        {
          id: "mc-loose",
          type: "multipleChoice",
          prompt: "Your test ring for a 22.0 mm PVC fitting was designed at 22.4 mm and is too tight. What should you change?",
          options: [
            { id: "a", text: "Make the hole a little bigger (for example 22.6 mm), reprint the ring and test again." },
            { id: "b", text: "Print the full design anyway and sand it later.", misconceptionId: "print-whole-first" },
            { id: "c", text: "Make the whole part bigger with Shift + corner drag.", misconceptionId: "scale-whole-part" },
          ],
          correctOptionIds: ["a"],
          explanation: "Change only the critical dimension, by a small step, and retest the small piece. Scaling the whole part changes every dimension, not just the hole.",
          competencyId: "E2",
          check: "skill",
        },
        {
          id: "mc-which",
          type: "multipleChoice",
          prompt: "Which parts of a phone-charger cable holder are worth test-printing first? Choose all that apply.",
          options: [
            { id: "a", text: "The slot the cable snaps into" },
            { id: "b", text: "The hole for the screw that mounts it" },
            { id: "c", text: "The decorative logo on the front", misconceptionId: "test-everything" },
          ],
          correctOptionIds: ["a", "b"],
          explanation: "Test the features that must fit something real. The logo can't fail to fit anything.",
          competencyId: "C10",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "both",
          kind: "prove",
          title: "Make It Fit",
          prompt: "Choose a real object your teacher approves — a bolt, marker, battery, building block, PVC fitting or something else. Design a useful part that fits it: a cap, holder, clip, stand or adapter. You decide the design.",
          requirements: [
            "Critical dimension measured at least twice and recorded with units",
            "Clearance based on your class Fit Lab result, with the reason written down",
            "First print is ONLY the interface (a thin test piece), not the whole part",
            "Test result recorded; if it didn't fit, one change made and retested",
            "Final full design in Tinkercad that uses the fit you proved",
          ],
          skills: ["C3", "C7", "C8", "C10", "E2"],
          visual: { diagram: "prototype-critical" },
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit: your measurements, a photo of the test piece on the real object, what you changed (if anything), and your final design.",
          accepts: ["physical_test", "design_url", "screenshot", "stl"],
          competencyIds: ["C7", "C8", "C10", "E2"],
          checklist: [
            "Measurements with units",
            "Clearance and why you chose it",
            "Photo of the test piece on the object",
            "Fit result for each test print",
            "Link or screenshot of the final design",
          ],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "How much time and plastic did printing only the interface save? What did the test piece tell you that the screen couldn't?",
          sentenceStarters: ["Printing only the test piece saved…", "The test showed me…", "Next time I would change…"],
          competencyIds: ["C10", "E2"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students apply their class clearance to a real object, learn to isolate and prototype only the critical interface, and iterate on fit. Scored with the Make It Fit rubric.",
    preparation: [
      "Post the class clearance from the Tolerances lesson.",
      "Collect a bin of approved objects: AA/AAA batteries, markers, dowels, M5/M6 bolts, LEGO-compatible bricks, ½\" PVC fittings, lip balm tubes.",
      "Plan print time: test pieces should take under 15 minutes each. Set a limit, e.g. three test prints per student.",
    ],
    equipment: ["Digital calipers (or rulers)", "Approved real objects", "3D printer and filament", "Student devices with Tinkercad"],
    misconceptions: [
      { id: "print-whole-first", text: "You should print the whole design to see if it fits.", response: "Compare print time and grams for the full part vs. a 5 mm ring in the slicer. Same fit information, a fraction of the cost." },
      { id: "math-guarantees-fit", text: "If the math is right, it will fit the first time.", response: "Remind them of the Fit Lab: printers vary. Measurement and math get you close; a test proves it." },
      { id: "scale-whole-part", text: "Scaling the whole part fixes a tight hole.", response: "Scale a part with a hole live and show the walls and outside size change too. Change the hole dimension directly." },
      { id: "test-everything", text: "Every feature needs to be test-printed.", response: "Ask: does this feature have to fit something? If not, it can't fail a fit test." },
    ],
    discussionQuestions: [
      "What is the critical dimension of your object? How do you know?",
      "How many test prints did you need? What changed between them?",
      "When might you test two dimensions in one test piece?",
    ],
    printableObjects: ["Student test pieces (interface only)", "Student final parts after a successful fit test"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls; print test pieces with the fitted hole lying flat on the plate so it stays round — adjust for your printer.",
    troubleshooting: [
      "Round holes printing small: check the cylinder's Sides setting was raised; low-sided cylinders are polygons.",
      "Fit differs between the test ring and the final part: make sure the final part prints in the same orientation as the test piece.",
      "Student scaled a hole and the wall became paper thin: rebuild the hole at the exact size instead of scaling the group.",
    ],
    answerGuidance: [
      "Prediction: b (thin ring).",
      "Battery: 14.2 + 0.4 = 14.6 mm (with an example clearance of 0.4 mm).",
      "Debug: a — change only the hole, small step, retest.",
      "Strong submissions show at least two measurements, a clearance tied to class data, a test piece photo and a recorded iteration.",
    ],
    rubricId: "make-it-fit",
    alternatives: {
      noCalipers: "Measure with a ruler to the nearest 0.5 mm, or wrap a paper strip around round objects, mark the overlap and divide the length by 3.14 for the diameter. Expect more test iterations and discuss why.",
      noPrinter: "Cut the interface from thick cardboard or foam board using the same dimensions, or have the teacher batch-print test pieces off-site. Students still record a fit result.",
      touchDevice: "Tap a dimension to type exact sizes; use the on-screen Group button.",
    },
  },
};
