import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "material-efficiency",
  number: 29,
  title: "Material Efficiency",
  subtitle: "Same job, less plastic",
  domain: "D",
  kind: "lesson",
  summary: "Estimate how much material a design uses, compare solid and hollow versions, and choose walls that are thick enough without waste.",
  estimatedMinutes: 50,
  printLevel: "digital",
  competencyIds: ["D10", "D12", "C9"],
  prerequisites: ["supports"],
  vocabulary: [
    { term: "Volume", definition: "How much space an object takes up, in mm³ or cm³. For a box: length × width × height." },
    { term: "cm³", definition: "Cubic centimetre. 1 cm³ = 1,000 mm³." },
    { term: "Wall thickness", definition: "How thick the material is between the inside and outside of an object." },
    { term: "Print estimate", definition: "The slicer's prediction of time and grams of filament for a print." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Where does the plastic go?",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Most of a solid block does nothing.",
          hook: "A pencil holder only needs walls and a floor. Everything inside is plastic, time and money you didn't need to spend.",
          visual: { diagram: "material-compare" },
        },
        {
          id: "explain",
          type: "text",
          body: "You can estimate material with simple **volume** math: length × width × height. Subtract the empty inside from the outside and you get the material the walls and floor actually use.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "A solid 40 × 40 × 30 mm block vs. the same block hollowed into a container with 2 mm walls and a 2 mm floor. How much material does the container use compared to the solid block?",
          options: [
            { id: "a", text: "About 90% — the walls are most of it", misconceptionId: "walls-are-most" },
            { id: "b", text: "About half" },
            { id: "c", text: "About a quarter" },
          ],
          expectedOptionId: "c",
          reveal: "About a quarter. Thin walls around a big empty middle add up to much less than you'd guess. Check the math below.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Do the math",
      blocks: [
        {
          id: "show-me",
          type: "showMe",
          title: "Estimate material for a container",
          steps: [
            { text: "Outside volume: 40 × 40 × 30 = 48,000 mm³.", diagram: "material-compare" },
            { text: "Inside (empty) size: subtract both walls from each width: 40 − 2 − 2 = 36 mm. Subtract the floor from the height: 30 − 2 = 28 mm.", diagram: "wall-thickness" },
            { text: "Inside volume: 36 × 36 × 28 = 36,288 mm³." },
            { text: "Material = outside − inside = 48,000 − 36,288 = 11,712 mm³ ≈ 11.7 cm³." },
          ],
        },
        {
          id: "solid-volume",
          type: "measurement",
          prompt: "How many cm³ is the solid 40 × 40 × 30 mm block? (1 cm³ = 1,000 mm³)",
          answer: 48,
          tolerance: 0,
          unit: "cm³",
          hint: "Multiply the three sides in mm, then divide by 1,000.",
          explanation: "40 × 40 × 30 = 48,000 mm³ = 48 cm³.",
          competencyId: "D10",
          check: "practice",
        },
        {
          id: "percent-saved",
          type: "measurement",
          prompt: "The container uses 11,712 mm³ and the solid block uses 48,000 mm³. What percent of the material does the container SAVE? Round to the nearest whole number.",
          answer: 76,
          tolerance: 1,
          unit: "%",
          hint: "Saved = solid − container. Then divide by solid and × 100.",
          explanation: "48,000 − 11,712 = 36,288. 36,288 ÷ 48,000 ≈ 0.756, so about 76% saved.",
          competencyId: "D10",
          check: "skill",
        },
        {
          id: "mc-slicer",
          type: "multipleChoice",
          prompt: "Your math says the solid block is 48 cm³ of plastic, but the slicer's estimate is much lower. Why?",
          options: [
            { id: "a", text: "The slicer doesn't print it solid — it uses walls plus a partly empty infill pattern inside." },
            { id: "b", text: "Your math must be wrong.", misconceptionId: "math-must-match-slicer" },
            { id: "c", text: "The slicer shrinks the model to save plastic." },
          ],
          correctOptionIds: ["a"],
          explanation: "Your volume math is the 100%-solid worst case — great for comparing designs. The slicer's grams estimate includes infill and walls and is the number to trust for the real print.",
          competencyId: "D10",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "How thin is too thin?",
      blocks: [
        { id: "thin-walls", type: "modelViewer", modelId: "thin-wall-test", caption: "Walls of 0.4, 0.8, 1.2, 1.6, 2.0 and 3.0 mm. A typical nozzle draws lines about 0.4 mm wide.", showDimensions: true },
        { id: "wall-diagram", type: "diagram", name: "wall-thickness", caption: "A wall only a line or two wide is fragile. Several lines wide is sturdy.", alt: "Cross-sections of thin, medium and thick walls compared to the width of a 0.4 mm nozzle line." },
        {
          id: "mc-wall",
          type: "multipleChoice",
          prompt: "A pencil cup gets knocked off desks a lot. Which wall thickness is the best balance of strength and material?",
          options: [
            { id: "a", text: "0.4 mm — saves the most plastic", misconceptionId: "thinnest-is-best" },
            { id: "b", text: "About 2 mm — several lines thick, still light" },
            { id: "c", text: "8 mm — can never break", misconceptionId: "thicker-always-better" },
          ],
          correctOptionIds: ["b"],
          explanation: "0.4 mm is a single line — fragile and may not print at all. 8 mm wastes plastic and time for little gain. Around 1.6–2 mm is a common, sturdy starting point for small parts on a 0.4 mm nozzle.",
          competencyId: "C9",
          check: "skill",
        },
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Check it in Tinkercad",
          prompt: "Build the 40 × 40 × 30 mm container from the Show Me. Then change the walls to 3 mm and calculate the new material volume.",
          requirements: ["Container built with 2 mm walls and floor", "Rebuilt with 3 mm walls and floor", "Material volume calculated for both"],
          skills: ["D10", "C9", "B3"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Build and compare",
          steps: ["Create a new design.", "Build the solid block and the hole, then group.", "Ungroup, resize the hole for 3 mm walls, regroup, and redo the math."],
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Slim down the planter",
          prompt: "A classmate designed a planter as a solid 70 × 70 × 50 mm block. Redesign it so it still works as a planter but uses far less plastic. Show your math.",
          requirements: [
            "Outside size stays 70 × 70 × 50 mm",
            "Walls at least 1.6 mm and floor at least 2 mm — choose a value and justify it",
            "Uses 30% or less of the solid block's volume",
            "Volume math shown: solid, empty inside, material, percent of solid",
            "Single grouped model",
          ],
          skills: ["D10", "D12", "C9", "B3"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your planter (link, screenshot with dimensions, or STL) and your volume math.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["D10", "D12", "C9"],
          checklist: ["Outside still 70 × 70 × 50 mm", "Wall and floor thickness stated with a reason", "Math for solid, inside and material", "Percent of solid volume"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Why should a designer care how much plastic a part uses? Give two reasons.",
          sentenceStarters: ["Using less plastic means…", "But walls that are too thin…"],
          competencyIds: ["D10", "C9"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students use volume math to compare designs, understand the difference between CAD volume and slicer estimates, and choose sensible wall thicknesses.",
    preparation: [
      "Optional: slice the solid 40 × 40 × 30 block and the 2 mm container in your slicer and note the grams for each to share.",
      "Optional: print the Thin Wall Test so students can feel each wall.",
      "Calculators allowed.",
    ],
    equipment: ["Student devices with Tinkercad", "Calculators", "Optional: printed Thin Wall Test", "Optional: slicer on the projector"],
    misconceptions: [
      { id: "walls-are-most", text: "Hollowing a block barely saves material.", response: "Work the math on the board. The empty middle is the biggest part." },
      { id: "math-must-match-slicer", text: "Volume math should equal the slicer's estimate.", response: "Show the slicer's cut-away infill preview. Math is the solid worst case; the slicer prints partly hollow." },
      { id: "thinnest-is-best", text: "The thinnest wall is always the most efficient.", response: "Pass around the 0.4 mm wall from the Thin Wall Test (or show it in the slicer preview). Efficient means enough material, not the least." },
      { id: "thicker-always-better", text: "Thicker walls are always better.", response: "Compare grams and time in the slicer for 2 mm vs. 8 mm walls. Past a point you pay more for little strength." },
    ],
    discussionQuestions: [
      "Where else could you remove material without hurting a design?",
      "Is the lightest design always the best design?",
    ],
    troubleshooting: [
      "Students forget the second wall: remind them every width loses a wall on BOTH sides.",
      "Students subtract the floor twice: an open-top container only loses one floor from its height.",
    ],
    answerGuidance: [
      "Prediction: c (about 24% of the solid).",
      "Solid: 48 cm³. Saved: about 76%.",
      "3 mm walls and floor: inside 34 × 34 × 27 = 31,212 mm³; material 48,000 − 31,212 = 16,788 mm³ ≈ 16.8 cm³.",
      "Planter with 2 mm walls and floor: solid 245,000 mm³; inside 66 × 66 × 48 = 209,088 mm³; material 35,912 mm³ ≈ 15% of solid. With 3 mm walls and floor: inside 64 × 64 × 47 = 192,512; material 52,488 ≈ 21%.",
    ],
    alternatives: {
      noPrinter: "This lesson is digital. Use slicer estimates as the 'test result'.",
      touchDevice: "Tap dimension values to type exact sizes.",
    },
  },
};
