import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "measuring-real-objects",
  number: 19,
  title: "Measuring Real Objects",
  subtitle: "From the real world into CAD",
  domain: "C",
  kind: "lesson",
  summary: "Measure physical objects with a ruler, find the critical dimension, measure more than once, and record it so someone else could build from it.",
  estimatedMinutes: 50,
  printLevel: "prototype",
  competencyIds: ["C3"],
  prerequisites: ["ruler"],
  vocabulary: [
    { term: "Critical dimension", definition: "The measurement that must be right for the part to work — usually where two things touch or fit." },
    { term: "Outside dimension", definition: "The size across the outside of an object, such as the width of a marker." },
    { term: "Inside dimension", definition: "The size of an opening, such as the inside of a cap." },
    { term: "Repeat measurement", definition: "Measuring the same thing several times to catch mistakes." },
    { term: "Millimetre (mm)", definition: "The unit CAD uses. 10 mm = 1 cm." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "The CAD file is only as good as your measurement.",
          hook: "Design a perfect pencil holder for a 7 mm pencil — but the pencil is really 8 mm. Perfect CAD, useless part.",
          visual: { diagram: "measure-critical" },
        },
        {
          id: "explain",
          type: "text",
          body: "Not every measurement matters equally. Find the **critical dimension** — the one where your part touches or fits the object. Measure it **at least three times**, write down the **unit**, and sketch where you measured.",
        },
        {
          id: "show-me",
          type: "showMe",
          title: "Measure with a ruler",
          steps: [
            { text: "Line up the object's edge with the 0 mark — not the end of the ruler, which is often worn or has a margin." },
            { text: "Look straight down at the far edge. Looking from an angle shifts the reading." },
            { text: "Read to the nearest 0.5 mm. Write it with its unit: 22.5 mm." },
            { text: "Measure twice more in slightly different spots. If the readings disagree by more than 1 mm, measure again." },
            { text: "Sketch the object and label where each measurement was taken.", diagram: "measure-critical" },
          ],
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You design a cap to slide over a marker. Which measurement is critical?",
          options: [
            { id: "a", text: "The marker's outside width where the cap goes" },
            { id: "b", text: "The marker's total length", misconceptionId: "all-dims-equal" },
            { id: "c", text: "The marker's weight", misconceptionId: "irrelevant-dim" },
          ],
          expectedOptionId: "a",
          reveal: "The cap only touches the marker's tip end. If that width is wrong, nothing else matters. Length is useful, but a cap that is a little long still works.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        {
          id: "cube-measure",
          type: "measurement",
          prompt: "Measure the printed Axis Cube with a ruler (or use the 3D viewer below). What should its X width be according to the CAD file?",
          visual: { modelId: "axis-cube-20mm" },
          answer: 20,
          tolerance: 0.5,
          unit: "mm",
          hint: "Use the face with one notch for X.",
          explanation: "The CAD file says 20 mm. A real print may measure 19.8–20.3 mm depending on the printer — that difference is useful information, not a mistake.",
          competencyId: "C3",
          check: "practice",
        },
        {
          id: "average",
          type: "measurement",
          prompt: "Three measurements of a battery's width: 14.0 mm, 14.5 mm, 14.0 mm. What value would you record? (Average, to one decimal.)",
          answer: 14.2,
          tolerance: 0.05,
          unit: "mm",
          hint: "Add them up and divide by 3.",
          explanation: "42.5 ÷ 3 = 14.17 → 14.2 mm. With a ruler you can only trust about ±0.5 mm, so record your average and note the tool you used.",
          competencyId: "C3",
          check: "practice",
        },
        {
          id: "critical-mc",
          type: "multipleChoice",
          prompt: "You're designing a holder that a glue stick slides into from the top. Which two measurements are critical?",
          options: [
            { id: "a", text: "The glue stick's width, and how deep the holder must be to keep it upright" },
            { id: "b", text: "The colour and the brand", misconceptionId: "irrelevant-dim" },
            { id: "c", text: "Every dimension is equally critical", misconceptionId: "all-dims-equal" },
          ],
          correctOptionIds: ["a"],
          explanation: "Width decides whether it fits. Depth decides whether it stays upright. Other dimensions can be approximate.",
          competencyId: "C3",
          check: "skill",
        },
        {
          id: "fit-object-view",
          type: "modelViewer",
          modelId: "mystery-fit-object",
          caption: "The Mystery Fit Object: a base with a round peg and a square post. If your teacher printed one, measure the real thing.",
          showDimensions: false,
        },
        {
          id: "peg-measure",
          type: "measurement",
          prompt: "Measure the round peg on the Mystery Fit Object. What is its diameter (width across)?",
          visual: { modelId: "mystery-fit-object" },
          answer: 8,
          tolerance: 0.5,
          unit: "mm",
          hint: "Measure straight across the widest part of the circle.",
          explanation: "The CAD size is 8 mm. A ruler reading between 7.5 and 8.5 mm is a good result. Measuring a circle with a ruler is hard — tomorrow, calipers will help.",
          competencyId: "C3",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          where: "both",
          kind: "micro",
          title: "Measurement card",
          prompt: "Pick one object from the class bin (marker, eraser, battery, building brick…). Make a measurement card: a sketch, the critical dimension, three readings, the average, and the unit.",
          requirements: ["Critical dimension identified", "Three readings plus an average", "Units on every number", "Sketch shows where each measurement was taken"],
          skills: ["C3"],
        },
        {
          id: "model-it",
          type: "tinkercadLaunch",
          title: "Model your object",
          steps: [
            "Create a new design.",
            "Build a simple version of your object using only your measurement card.",
            "Swap cards with a partner and model their object from their card. Could you do it without asking questions?",
          ],
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "both",
          kind: "prove",
          title: "Blind build",
          prompt: "Your teacher hands you an object you haven't seen today. Measure it and write a measurement card good enough that a classmate could model it in Tinkercad without ever seeing the object. Then model it yourself. No steps.",
          requirements: [
            "At least three dimensions recorded, with units",
            "Critical dimension identified and measured three times",
            "Sketch labels where each measurement was taken",
            "Tinkercad model matches your recorded dimensions",
          ],
          skills: ["C3", "A9"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Upload a photo of your measurement card and a screenshot (or class design link) of your model with dimensions showing.",
          accepts: ["screenshot", "design_url", "physical_test"],
          competencyIds: ["C3"],
          checklist: ["Card shows three readings for the critical dimension", "Every number has a unit", "Model dimensions match the card"],
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Watch the student measure the critical dimension once.",
          lookFors: ["Starts at the 0 mark, not the ruler's end", "Looks straight down at the reading", "Measures more than once without being reminded", "Records units"],
          competencyIds: ["C3"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Did your three readings agree? What might have caused any difference?",
          sentenceStarters: ["My readings were…", "The difference might come from…"],
          competencyIds: ["C3"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students learn to identify the critical dimension, measure it repeatedly with a ruler, and record measurements clearly enough for someone else to use.",
    preparation: [
      "Collect a bin of everyday objects with clear critical dimensions: markers, glue sticks, AA/AAA batteries, erasers, building bricks, bottle caps.",
      "Optional: print a few Axis Cubes and Mystery Fit Objects as measuring specimens.",
      "Set aside 'mystery' objects for the prove challenge that students haven't handled yet.",
    ],
    equipment: ["Rulers with millimetre markings (one per pair)", "Everyday objects to measure", "Optional: printed Axis Cubes and Mystery Fit Objects", "Student devices with Tinkercad"],
    misconceptions: [
      { id: "all-dims-equal", text: "Every dimension needs to be equally precise.", response: "Ask: if this number were 2 mm off, would the part still work? Only the 'no' answers are critical." },
      { id: "irrelevant-dim", text: "Properties like colour, brand or weight are measurements for CAD.", response: "CAD only knows shape and size. Ask what the printer would do with that number." },
    ],
    discussionQuestions: [
      "Why might a printed 20 mm cube measure 20.2 mm?",
      "What makes a measurement card good enough for someone else to use?",
    ],
    printableObjects: ["Axis Cube 20 mm (a few for the class)", "Mystery Fit Object (a few for the class)"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls, no supports. Adjust for your printer. Measure one printed cube yourself first so you know how your printer compares to 20 mm.",
    troubleshooting: [
      "Readings vary by several mm: check the student is starting from 0 and keeping the ruler straight along the object.",
      "Round objects are hard to measure: place two blocks against either side and measure between the blocks.",
    ],
    answerGuidance: [
      "Accept ruler readings within ±0.5 mm of the true value; the process (repeat, units, sketch) matters more than precision today.",
      "Mystery Fit Object CAD sizes: base 34 × 22 × 10 mm, round peg 8 mm wide and 12 mm tall, square post 6 × 6 × 6 mm.",
    ],
    alternatives: {
      noPrinter: "Skip the printed specimens; measure everyday objects and use the 3D viewer's dimensions for the Axis Cube and Mystery Fit Object.",
      touchDevice: "Students can photograph their measurement card with the device camera for submission.",
    },
  },
};
