import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "mini-design-sprint",
  number: 40,
  title: "Mini Design Sprint",
  subtitle: "One week. One problem. One object that works.",
  domain: "F",
  kind: "challenge",
  summary: "A condensed product design challenge: pick a defined problem, write measurable constraints, prototype the critical part, test, revise once, and present a functional design.",
  estimatedMinutes: 225,
  printLevel: "prototype",
  competencyIds: ["F1", "F2", "F5", "F6", "F8", "F10"],
  prerequisites: ["cad-er"],
  vocabulary: [
    { term: "Design sprint", definition: "A short, time-boxed run through the whole design process." },
    { term: "Constraint", definition: "A must-have requirement you can measure or test." },
    { term: "Prototype", definition: "A quick early version built to answer one question." },
    { term: "Iteration", definition: "Changing the design because of a test result, then testing again." },
    { term: "Functional design", definition: "An object judged by whether it does its job, not just how it looks." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Day 1 — Understand and define",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "One week. One problem. One object that works.",
          hook: "You've repaired someone else's broken design. Now design your own — for a real problem, with numbers, tests and a version 2.",
          visual: { diagram: "design-cycle" },
        },
        {
          id: "plan",
          type: "text",
          title: "The sprint",
          body: "- **Day 1:** pick a problem, talk to the user, write constraints\n- **Day 2:** three ideas, choose one, start CAD\n- **Day 3:** prototype the critical part and test it\n- **Day 4:** revise and re-test\n- **Day 5:** finish and present",
        },
        {
          id: "problems",
          type: "text",
          title: "Pick a problem card",
          body: "- Your **teacher's** dry-erase markers roll off a 5 cm ledge.\n- A **classmate's** earbuds tangle in their backpack.\n- A **classmate's** charging cable falls behind the desk.\n- Your **teacher's** sticky notes get lost under papers.\n- Or propose your own — your teacher approves it.",
        },
        {
          id: "talk",
          type: "callout",
          tone: "safety",
          title: "Talk to your user (5 minutes)",
          body: "Ask your user — a classmate or your teacher — two open questions and measure the object or space. Use a role, not a full name, in your journal. No photos of faces.",
        },
        {
          id: "constraint-mc",
          type: "multipleChoice",
          prompt: "Which is a measurable constraint for the rolling-marker problem?",
          options: [
            { id: "a", text: "Holds 3 markers 18 mm across and fits on a 5 cm ledge" },
            { id: "b", text: "Looks nice on the whiteboard", misconceptionId: "wish-is-constraint" },
            { id: "c", text: "Is really good" },
          ],
          correctOptionIds: ["a"],
          explanation: "A constraint has a number or a clear pass/fail test. 'Looks nice' is a wish: good to have, but it doesn't decide whether the design works.",
          competencyId: "F2",
          check: "skill",
        },
        { id: "journal-define", type: "journal", projectKey: "mini-sprint", promptIds: ["user", "problem", "constraints"] },
      ],
    },
    {
      phase: "practice",
      title: "Day 2 — Ideas and CAD",
      blocks: [
        {
          id: "sketch",
          type: "diagram",
          name: "sketch-concepts",
          caption: "Three ideas that work in different ways — then choose with your constraints.",
          alt: "Three different rough sketches for one problem.",
        },
        {
          id: "choose-mc",
          type: "multipleChoice",
          prompt: "Your best-looking idea sticks out 45 mm past a 5 cm (50 mm) ledge. Another idea fits completely on the ledge. Which do you build?",
          options: [
            { id: "a", text: "The one that fits on the ledge — it meets the constraint." },
            { id: "b", text: "The best-looking one — looks matter most.", misconceptionId: "looks-first" },
          ],
          correctOptionIds: ["a"],
          explanation: "Choose with your constraints. You can make the working idea look good later.",
          competencyId: "F2",
          check: "practice",
        },
        { id: "journal-ideas", type: "journal", projectKey: "mini-sprint", promptIds: ["ideas", "first-idea", "why"] },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Start your design",
          steps: [
            "Create a new design named after your problem, e.g. 'marker stop v1'.",
            "Build the critical feature first — the hole, slot or clip that touches the real object — using your measured numbers plus clearance.",
            "Then build the rest around it. Keep it one grouped model.",
          ],
        },
      ],
    },
    {
      phase: "apply",
      title: "Days 3–4 — Prototype, test, revise",
      blocks: [
        {
          id: "predict-print",
          type: "prediction",
          prompt: "Your design is a 90-minute print. The riskiest part is whether a 4 mm cable fits the clip. What do you print on Day 3?",
          visual: { diagram: "prototype-critical" },
          options: [
            { id: "a", text: "Only a thin slice with the clip" },
            { id: "b", text: "The whole design", misconceptionId: "print-it-all" },
          ],
          expectedOptionId: "a",
          reveal: "A slice prints in minutes and answers the fit question. You'll have time to change it and print again before Day 5.",
        },
        {
          id: "test-tip",
          type: "callout",
          tone: "tip",
          title: "Test like a designer",
          body: "Write the pass rule first: 'cable clips in and stays put, 5 out of 5 tries'. Then test. Record the number, even if it fails.",
        },
        { id: "journal-test", type: "journal", projectKey: "mini-sprint", promptIds: ["prototype", "test", "failed", "changed"] },
        {
          id: "revision-mc",
          type: "multipleChoice",
          prompt: "Your 4.0 mm clip was too tight — the cable wouldn't go in 5/5 tries. What's the best revision?",
          options: [
            { id: "a", text: "Widen only the clip opening a little (e.g. to 4.4 mm), print another slice and re-test." },
            { id: "b", text: "Change the clip, the base and the infill all at once.", misconceptionId: "change-everything" },
            { id: "c", text: "Give up on the clip and start a new idea." },
          ],
          correctOptionIds: ["a"],
          explanation: "One targeted change linked to the test result. If it works, you know why.",
          competencyId: "F8",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Day 5 — Finish and present",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "both",
          kind: "prove",
          title: "Mini Product Design Challenge",
          prompt: "Deliver a functional design that solves your defined problem. Show the evidence: constraints, a test, a revision and a re-test. Present it in 90 seconds.",
          requirements: [
            "Problem statement names the user and what goes wrong",
            "At least three constraints, two with numbers and units",
            "Critical part prototyped and tested with a recorded result",
            "At least one revision based on that test, then re-tested",
            "Final design is one grouped, printable model",
            "90-second talk: user, problem, test, change, final design",
          ],
          skills: ["F1", "F2", "F5", "F6", "F8", "F10"],
        },
        { id: "journal-final", type: "journal", projectKey: "mini-sprint", promptIds: ["final"] },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your final design (class design link or STL), a screenshot with the critical dimension visible, and a photo of your test if you printed.",
          accepts: ["design_url", "stl", "screenshot", "physical_test"],
          competencyIds: ["F1", "F2", "F5", "F6", "F8", "F10"],
          checklist: ["Critical dimension is visible", "Test result recorded in the journal", "Revision and re-test recorded", "Single grouped model"],
          allowPrintRequest: true,
        },
        {
          id: "present-check",
          type: "teacherCheck",
          prompt: "Observe each 90-second presentation.",
          lookFors: ["Names the user and the problem", "Describes a test with a number", "Explains one change and why", "Explains how the final design meets a constraint"],
          competencyIds: ["F10"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        { id: "journal-next", type: "journal", projectKey: "mini-sprint", promptIds: ["next"] },
        {
          id: "reflect",
          type: "reflection",
          prompt: "What did your test teach you that you couldn't have known from the CAD model alone?",
          sentenceStarters: ["In CAD it looked…, but the test showed…", "Next time I would test…"],
          competencyIds: ["F6", "F8"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "The 9-week course's finish line: a compressed, complete design cycle on a defined problem, emphasising measurable constraints, testing the critical part and one evidence-based revision.",
    preparation: [
      "Print or post the problem cards; decide whether students may propose their own problem.",
      "Set a print-queue rule: Day 3 slices under 20 minutes; final prints queued by the end of Day 4.",
      "Have the real objects available (markers, earbuds, cables, sticky-note pads) so students can measure and test.",
    ],
    equipment: ["Student devices with Tinkercad", "Ruler or calipers", "Objects from the problem cards", "3D printer (optional)", "Paper for sketches"],
    misconceptions: [
      { id: "wish-is-constraint", text: "Any request is a constraint.", response: "Ask: can you test it with a number or a clear yes/no? If not, it's a wish." },
      { id: "looks-first", text: "The best-looking idea is the best idea.", response: "Check each idea against the constraints first; looks can be improved after it works." },
      { id: "print-it-all", text: "Print the whole design to test it.", response: "Compare print times. Test only the part most likely to fail." },
      { id: "change-everything", text: "Fix a failure by changing everything.", response: "If you change three things, you won't know which one worked. Change the one the test points to." },
    ],
    discussionQuestions: [
      "What's the difference between a constraint and a wish?",
      "Why test the riskiest part first?",
      "How was this different from repairing the phone stand in CAD ER?",
    ],
    printableObjects: ["Day 3 test slices (short prints)", "Final designs (one per student, if printer time allows)"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls, no supports where possible. Use the same settings for the slice and the final so results carry over. Adjust for your printer.",
    troubleshooting: [
      "If a student is stuck on Day 1, assign the rolling-marker card — it has clear numbers.",
      "If a design is too big to print in time, print the critical part and submit the full design digitally.",
      "If a test passes on the first try, have them run a harder test (more repetitions, real use) to find something to improve.",
    ],
    answerGuidance: [
      "Strong constraints example (cable clip): 'holds a 4 mm cable; clips onto a 20 mm desk edge; sticks out no more than 25 mm; removable by hand'.",
      "Proficient: at least one test with a recorded number, one targeted revision and a re-test.",
      "Optional scoring: use the capstone rubric's Problem Solving, Testing & Iteration and Communication rows (12 pts).",
    ],
    alternatives: {
      noPrinter: "Prototype the critical part in cardboard at the designed size, test it with the real object, revise in CAD, and submit the final design digitally.",
      noCalipers: "Measure with a ruler to the nearest 0.5 mm and add a little more clearance; test with a printed or cardboard slice.",
      touchDevice: "Use on-screen Group, Hole and Ruler tools; photograph sketches for the journal.",
    },
  },
};
