import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "mirror",
  number: 15,
  title: "Mirror",
  subtitle: "Design half, get the whole",
  domain: "B",
  kind: "lesson",
  summary: "Flip shapes with the Mirror tool to build symmetric parts, and position the mirrored half so the seam meets exactly.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["B7"],
  prerequisites: ["repeat-duplicate"],
  vocabulary: [
    { term: "Mirror", definition: "Flip a shape across an axis so it becomes its own reflection." },
    { term: "Symmetry", definition: "When one half of an object is a reflection of the other half." },
    { term: "Mirror line", definition: "The line (or plane) that a shape is flipped across." },
    { term: "Seam", definition: "Where the two halves of a mirrored design meet." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Half the work. Perfect symmetry.",
          hook: "Glasses frames, guitar bodies and car fronts are symmetric. Designers build one side, then mirror it, so both sides match to the millimetre.",
          visual: { diagram: "mirror-axis" },
        },
        {
          id: "explain",
          type: "text",
          body: "Select a shape and press **M**. Arrows appear on each axis. Click an arrow and the shape **flips in place** across that axis. It does not jump to the other side — you move it there yourself.",
        },
        {
          id: "bracket-view",
          type: "modelViewer",
          modelId: "half-bracket",
          caption: "Half of a shelf bracket, 30 mm wide. Its right edge (X = 30 mm) is where the other half should join.",
          showDimensions: true,
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You duplicate the half bracket and mirror the copy on X. Where is the copy?",
          visual: { diagram: "mirror-axis" },
          options: [
            { id: "a", text: "In the same spot as the original, but flipped" },
            { id: "b", text: "Already joined on the right side, making a full bracket", misconceptionId: "mirror-moves" },
            { id: "c", text: "Upside down", misconceptionId: "mirror-wrong-axis" },
          ],
          expectedOptionId: "a",
          reveal: "Mirror flips the copy inside its own box. It overlaps the original until you move it. Mirroring on X flips left–right; only a Z mirror turns a shape upside down.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        { id: "files", type: "modelDownload", modelIds: ["half-bracket"], showImportSteps: true },
        {
          id: "show-me",
          type: "showMe",
          title: "Complete the bracket",
          steps: [
            { text: "Import the Half Bracket. Click it and note its width: 30 mm." },
            { text: "Press Ctrl+D to duplicate it.", keys: "Ctrl+D" },
            { text: "With the copy selected, press M and click the arrow on the X axis. The copy flips left–right.", diagram: "mirror-axis", keys: "M" },
            { text: "Move the copy 30 mm on X so its edge meets the original's right edge.", diagram: "nudge-keys" },
            { text: "Select both and group (Ctrl+G).", keys: "Ctrl+G" },
          ],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Build the full bracket",
          steps: [
            "Create a new design and import the Half Bracket.",
            "Follow the Show Me steps to make the full bracket.",
            "Check the finished width: it should read exactly 60 mm.",
            "Orbit close to the seam. There should be no gap and no step.",
          ],
        },
        {
          id: "find-seam",
          type: "hotspot",
          prompt: "Click the edge where the mirrored half must meet the original.",
          hint: "The two halves must touch along one straight edge. Which edge is the open side of the half?",
          modelId: "half-bracket",
          hotspots: [
            { id: "edge", label: "Right edge (X = 30 mm)", position: [30, 10, 2], radius: 8, correct: true, feedback: "Test result: that's the mirror line. The copy's flat edge must touch here exactly." },
            { id: "upright", label: "Upright", position: [2, 10, 17], radius: 8, correct: false, feedback: "Joining at the upright would put the wall in the middle and the arms pointing outward — a different part. Where is the flat, cut side?" },
          ],
          explanation: "A half part is cut along its mirror line. That flat cut face is where the two halves meet.",
          competencyId: "B7",
          check: "practice",
        },
        {
          id: "width-check",
          type: "measurement",
          prompt: "A half part is 23 mm wide. After mirroring and joining perfectly, how wide is the full part?",
          hint: "Two halves of the same width, placed side by side.",
          answer: 46,
          tolerance: 0,
          unit: "mm",
          explanation: "Two halves with no gap and no overlap: 23 × 2 = 46 mm. A different width means the seam has a gap or an overlap.",
          competencyId: "B7",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Mirror a letter",
          prompt: "Using only boxes, build half of a capital letter A (one leg plus half the crossbar). Mirror it to complete the letter, 40 mm wide.",
          requirements: ["Full letter exactly 40 mm wide", "No gap at the seam", "Single grouped model"],
          skills: ["B7", "B4", "B2"],
        },
        {
          id: "text-mc",
          type: "multipleChoice",
          prompt: "You mirror a Text shape that says 'HI 5' on X. What does it look like?",
          hint: "Hold a sign up to a real mirror. What happens to the words?",
          options: [
            { id: "a", text: "The letters read backwards, like in a mirror." },
            { id: "b", text: "It still reads 'HI 5' normally.", misconceptionId: "mirror-text-same" },
            { id: "c", text: "The letters are upside down.", misconceptionId: "mirror-wrong-axis" },
          ],
          correctOptionIds: ["a"],
          explanation: "H and I are symmetric so they look the same, but the 5 turns backwards. Mirror reverses everything left–right. This is useful for stamps, which must be backwards to print forwards.",
          competencyId: "B7",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Symmetric key tag",
          prompt: "Design half of a key tag using at least three shapes, including one hole. Mirror it to make a complete tag exactly 50 mm wide. Put a 5 mm keyring hole on the mirror line — it should still be round after mirroring. No steps.",
          requirements: [
            "Full tag exactly 50 mm wide",
            "Left and right halves are exact mirror images",
            "Round 5 mm keyring hole centred on the mirror line",
            "No gap or step at the seam",
            "Single grouped model",
          ],
          skills: ["B7", "B3", "B4", "B2"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a class design link or a top-view screenshot that shows the 50 mm width.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["B7"],
          checklist: ["Width reads 50 mm", "Keyring hole is round and centred", "Everything is one group"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "The keyring hole sits on the mirror line. What did you have to think about to keep it round?",
          sentenceStarters: ["At first I…", "I kept it round by…"],
          competencyIds: ["B7"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students mirror in place, move the copy to close the seam, and reason about features that sit on the mirror line.",
    preparation: ["Import the Half Bracket once on a student device and check its width reads 30 mm."],
    equipment: ["Student devices with Tinkercad"],
    misconceptions: [
      { id: "mirror-moves", text: "Mirror moves the shape to the other side of the mirror line.", response: "Mirror the original (not a copy) on the projector — it flips in place and the original side is gone." },
      { id: "mirror-wrong-axis", text: "Any mirror turns a shape upside down.", response: "Click the X, Y and Z mirror arrows one at a time and ask students to predict each." },
      { id: "mirror-text-same", text: "Mirrored text still reads normally.", response: "Mirror the word 'CAT' live. Connect to stamps and ambulance lettering." },
    ],
    discussionQuestions: ["Why do designers often build only half of a symmetric object?", "What could go wrong if a feature crosses the mirror line?"],
    troubleshooting: [
      "Students mirrored the original instead of a copy: Ctrl+Z, then Ctrl+D first.",
      "Width is 59 or 61 mm: the copy was moved too little or too much. Type the exact X position or nudge 1 mm at a time.",
      "Keyring hole looks like a figure-8 or a half moon: the half-hole wasn't cut exactly at the mirror line. Easiest fix: add the full round hole after mirroring, aligned to the centre.",
    ],
    answerGuidance: [
      "Bracket: duplicate, mirror on X, move +30 mm on X, group → 60 mm wide.",
      "Key tag: build a 25 mm half, mirror and join; the cleanest approach places one complete 5 mm hole centred on the seam after joining (align centre on X), then groups.",
    ],
    alternatives: { touchDevice: "Use the Mirror button in the top toolbar instead of the M key." },
  },
};
