import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "moving-objects",
  number: 4,
  title: "Moving Objects",
  subtitle: "X, Y and Z — and knowing where the floor is",
  domain: "A",
  kind: "lesson",
  summary: "Move shapes across the workplane and up or down by exact amounts, and make sure every part actually sits on the floor.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["A6", "A7"],
  prerequisites: ["navigating-tinkercad"],
  vocabulary: [
    { term: "X axis", definition: "Left–right across the workplane (red)." },
    { term: "Y axis", definition: "Front–back across the workplane (green)." },
    { term: "Z axis", definition: "Up and down, away from the workplane (blue)." },
    { term: "Nudge", definition: "Move a shape a fixed small step with the arrow keys." },
    { term: "Elevation", definition: "How high the bottom of a shape is above the workplane." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Three directions",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "A floating part prints as spaghetti.",
          hook: "If a shape hovers even 1 mm above the workplane, the printer starts it in mid-air. If it sinks below, part of it disappears. Moving on purpose fixes both.",
          visual: { modelId: "misplaced-shapes", alt: "Misplaced shapes: one floating, one sunk." },
        },
        {
          id: "axes",
          type: "diagram",
          name: "xyz-axes",
          caption: "X is left–right, Y is front–back, Z is up. Tinkercad's workplane is the X–Y floor.",
          alt: "X, Y and Z arrows.",
        },
        {
          id: "show-me",
          type: "showMe",
          title: "Four ways to move",
          steps: [
            { text: "Drag a shape across the workplane to move it on X and Y." },
            { text: "Arrow keys nudge the selected shape 1 mm. Shift + arrow nudges 10 mm.", diagram: "nudge-keys", keys: "← → ↑ ↓ / Shift + arrow" },
            { text: "Drag the small black cone above the shape to raise or lower it on Z. Ctrl + ↑ / ↓ also moves it up or down.", diagram: "move-z", keys: "Ctrl + ↑ / ↓" },
            { text: "Press D to drop the selected shape straight down onto the workplane.", diagram: "move-z", keys: "D" },
          ],
        },
        {
          id: "nudge-math",
          type: "measurement",
          prompt: "You press Shift + → three times, then → four times. How far did the shape move?",
          answer: 34,
          tolerance: 0,
          unit: "mm",
          hint: "Each Shift + → is 10 mm. Each → is 1 mm.",
          explanation: "3 × 10 + 4 × 1 = 34 mm. Nudging lets you move by exact amounts without a ruler.",
          competencyId: "A6",
          check: "practice",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "A cube is sitting 18 mm above the workplane. You select it and press D. What happens?",
          visual: { diagram: "move-z" },
          options: [
            { id: "a", text: "It drops straight down until it touches the workplane" },
            { id: "b", text: "It is deleted", misconceptionId: "d-deletes" },
            { id: "c", text: "It moves 1 mm down" },
          ],
          expectedOptionId: "a",
          reveal: "D drops the shape so its lowest point rests on the workplane. It does not move it left, right, forward or back.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Make a mess, then fix it",
      blocks: [
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Rebuild the Misplaced Shapes scene",
          steps: [
            "Open Tinkercad and create a new design. Check that Snap Grid (bottom right) is 1 mm.",
            "Drag in a Box. Lift it with the cone handle until it shows 18 mm above the workplane.",
            "Drag in a Sphere. Press Ctrl + ↓ until it sinks partly through the workplane.",
            "Orbit to a side view. Confirm the box floats and the sphere sinks.",
            "Now fix both: select each one and press D. Orbit again to check.",
            "Optional: import misplaced-shapes.stl to compare with the original scene.",
          ],
        },
        { id: "files", type: "modelDownload", modelIds: ["misplaced-shapes"], showImportSteps: true },
        {
          id: "find-sunk",
          type: "hotspot",
          prompt: "In the original scene, click the shape that would lose part of itself because it is below the workplane.",
          modelId: "misplaced-shapes",
          hotspots: [
            { id: "sphere", label: "Sphere", position: [0, 0, 0], radius: 11, correct: true, feedback: "Yes. Its bottom is 13 mm below the floor. Anything below the workplane won't print as designed." },
            { id: "cube", label: "Cube", position: [65, 45, 28], radius: 14, correct: false, feedback: "This one has the opposite problem: it floats 18 mm above the floor." },
            { id: "cylinder", label: "Cylinder", position: [-60, -40, 12], radius: 13, correct: false, feedback: "Far from the centre, but it sits on the workplane." },
            { id: "cone", label: "Cone", position: [-25, 70, 10], radius: 11, correct: false, feedback: "The cone's base rests on the workplane." },
          ],
          explanation: "Floating and sunk shapes can both look fine from above. Orbit to a side view, then use D or the cone handle to fix them.",
          competencyId: "A7",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Parking lot",
          prompt: "Drag in five different shapes anywhere. Park them in a straight row along X.",
          requirements: ["All five rest on the workplane (check from the side)", "Each shape is exactly 30 mm farther along X than the one before (use nudges)", "All five are lined up on Y"],
          skills: ["A6", "A7"],
        },
        {
          id: "slide-lift",
          type: "slider",
          prompt: "Lift the small 10 mm cube so it sits **exactly on top** of the 20 mm box — not sunk in, not floating.",
          scene: "lift",
          min: 0,
          max: 40,
          step: 1,
          start: 5,
          unit: "mm",
          answer: 20,
          tolerance: 0,
          hint: "In Tinkercad, Z is where the BOTTOM of a shape is. Where is the top of the box?",
          explanation: "The box's top is at Z = 20 mm, so the cube's bottom goes at **20**. Z always measures the bottom of the shape.",
          competencyId: "A7",
        },
        {
          id: "check-floor",
          type: "multipleChoice",
          prompt: "From the top view, your shape looks like it is sitting on the workplane. What is the best way to be sure?",
          options: [
            { id: "a", text: "Orbit to a low side view and look for a gap, or select it and press D" },
            { id: "b", text: "Zoom in from the top view", misconceptionId: "top-view-enough" },
            { id: "c", text: "If its shadow is on the grid, it's on the workplane", misconceptionId: "top-view-enough" },
          ],
          correctOptionIds: ["a"],
          explanation: "Height is invisible from straight above. Check Z from the side, and use D when a shape should rest on the floor.",
          competencyId: "A7",
          check: "skill",
        },
        {
          id: "axis-check",
          type: "multipleChoice",
          prompt: "You need to move a shape toward the back of the workplane, away from you. Which axis is that?",
          options: [
            { id: "a", text: "Y" },
            { id: "b", text: "X", misconceptionId: "axis-mixup" },
            { id: "c", text: "Z", misconceptionId: "axis-mixup" },
          ],
          correctOptionIds: ["a"],
          explanation: "Front–back is Y. Left–right is X. Up–down is Z.",
          competencyId: "A6",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Staircase in the air",
          prompt: "Build a floating staircase of three 10 mm cubes, plus one cylinder on the ground. No steps — choose your own moves.",
          requirements: [
            "Cube 1 rests on the workplane",
            "Cube 2's bottom is exactly 15 mm above the workplane; Cube 3's bottom is exactly 30 mm above",
            "Each cube is exactly 20 mm farther along X than the one before",
            "A cylinder rests on the workplane exactly 25 mm in front of Cube 1 (along Y)",
          ],
          skills: ["A6", "A7"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a class share link or two screenshots: one from the side showing the heights, one from the top showing the spacing.",
          accepts: ["design_url", "screenshot"],
          competencyIds: ["A6", "A7"],
          checklist: ["Side view shows three different heights", "Top view shows even 20 mm spacing", "Cylinder touches the workplane"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "When is dragging good enough, and when do you need nudges or D?",
          sentenceStarters: ["Dragging is fine when…", "I need exact moves when…"],
          competencyIds: ["A6", "A7"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students move shapes by exact amounts on X, Y and Z and build the habit of checking that parts sit on the workplane.",
    preparation: [
      "Test the nudge keys and Snap Grid on a student device. Nudge step size follows the Snap Grid setting, so keep it at 1 mm.",
      "Download misplaced-shapes.stl. An imported STL usually arrives as one combined shape, which is why students rebuild the scene with Tinkercad shapes instead of editing the import.",
    ],
    equipment: ["Student devices with Tinkercad", "Mouse recommended"],
    misconceptions: [
      { id: "d-deletes", text: "Pressing D deletes the shape.", response: "Delete is the Delete key. D means drop. Demonstrate on a floating shape." },
      { id: "top-view-enough", text: "If it looks right from the top, it's on the workplane.", response: "Lift a shape 5 mm and show it from above, then orbit to the side." },
      { id: "axis-mixup", text: "Mixing up X, Y and Z directions.", response: "Point to the red/green/blue arrows on the view cube and have students point left–right, front–back, up." },
    ],
    discussionQuestions: [
      "Why would a slicer have trouble with a part that floats 1 mm above the workplane?",
      "How can you move a shape exactly 47 mm with the fewest key presses?",
    ],
    troubleshooting: [
      "If arrow keys move the camera instead of the shape, click the shape first so it is selected.",
      "If a nudge moves the wrong distance, check the Snap Grid setting.",
      "If Ctrl + arrow doesn't work in a browser, use the cone handle and watch the height number while dragging.",
    ],
    answerGuidance: [
      "Staircase: Cube 1 at X = 0, Z = 0; Cube 2 at X + 20, elevation 15; Cube 3 at X + 40, elevation 30. Cylinder 25 mm along Y from Cube 1, elevation 0.",
      "Students who nudge 20 mm with Shift + → twice are using the most efficient method.",
    ],
    alternatives: {
      touchDevice: "Without arrow keys, drag shapes and type values where Tinkercad shows them, or use an on-screen keyboard. Use the cone handle for height.",
    },
  },
};
