import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "navigating-tinkercad",
  number: 3,
  title: "Navigating Tinkercad",
  subtitle: "Orbit, pan, zoom and select on purpose",
  domain: "A",
  kind: "lesson",
  summary: "Control the 3D view so you can inspect any part of a design, get back home when you're lost, and select exactly the shapes you mean.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["A1", "A2", "A3", "A4", "A5"],
  prerequisites: ["print-detective"],
  vocabulary: [
    { term: "Workplane", definition: "The blue grid that shapes sit on. It is the floor of your design." },
    { term: "Orbit", definition: "Swing the camera around the design to see it from another side." },
    { term: "Pan", definition: "Slide the camera sideways or up and down without turning it." },
    { term: "Zoom", definition: "Move the camera closer to or farther from the design." },
    { term: "Selection", definition: "The shape or shapes that your next action will change." },
  ],
  sections: [
    {
      phase: "discover",
      title: "You're the camera",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "If you can't see it, you can't fix it.",
          hook: "Five shapes are scattered around a workspace. One is floating. One is sinking through the floor. From the starting view, you can't tell which.",
          visual: { modelId: "misplaced-shapes", alt: "Five shapes scattered around a workplane." },
        },
        {
          id: "explain",
          type: "text",
          body: "In 3D, the shapes stay still and **you move the camera**. Three moves cover everything: **orbit** (turn around it), **pan** (slide), and **zoom** (closer or farther).",
        },
        {
          id: "controls",
          type: "diagram",
          name: "view-controls",
          caption: "Right-drag orbits. Shift + right-drag (or middle-drag) pans. Scroll zooms. The view cube and Home button reset the view.",
          alt: "Mouse map of orbit, pan and zoom controls.",
        },
        {
          id: "show-me",
          type: "showMe",
          title: "Find your way around",
          steps: [
            { text: "Orbit: hold the right mouse button and drag. The design turns in front of you.", diagram: "view-controls", keys: "Right-drag" },
            { text: "Pan: hold Shift and right-drag (or drag with the middle button / scroll wheel) to slide the view.", keys: "Shift + Right-drag" },
            { text: "Zoom: roll the scroll wheel. Zoom toward the spot under your pointer." , keys: "Scroll" },
            { text: "Lost? Press F (or the Zoom to fit button) to fit everything on screen, or click Home / a face of the view cube.", keys: "F" },
          ],
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You orbit all the way around a shape. Did the shape move?",
          options: [
            { id: "a", text: "No. Only my view changed; the shape is in the same place" },
            { id: "b", text: "Yes. Orbiting turns the shape", misconceptionId: "orbit-moves" },
          ],
          expectedOptionId: "a",
          reveal: "Orbit, pan and zoom never change your design. They only move the camera. That's why you can explore freely without breaking anything.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Explore the scene",
      blocks: [
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Import the Misplaced Shapes",
          steps: [
            "Open Tinkercad and create a new design in your class.",
            "Import misplaced-shapes.stl (download it below). It arrives as one combined shape — that's fine for today.",
            "Orbit to a low side view. Which shape sits higher than all the others?",
            "Orbit until you are looking up from under the workplane.",
            "Zoom in on the cube. Orbit to a side view to check whether it touches the workplane.",
            "Press F to fit everything, then click Home to reset.",
          ],
        },
        { id: "files", type: "modelDownload", modelIds: ["misplaced-shapes"], showImportSteps: true },
        {
          id: "find-floating",
          type: "hotspot",
          prompt: "Orbit the model. Click the shape that is floating above the workplane.",
          modelId: "misplaced-shapes",
          hotspots: [
            { id: "cube", label: "Cube", position: [65, 45, 28], radius: 14, correct: true, feedback: "Found it. From the side you can see an 18 mm gap under the cube." },
            { id: "sphere", label: "Sphere", position: [0, 0, 0], radius: 11, correct: false, feedback: "This one has the opposite problem: most of it is below the workplane." },
            { id: "cylinder", label: "Cylinder", position: [-60, -40, 12], radius: 13, correct: false, feedback: "Orbit to a side view. Does this one touch the workplane?" },
            { id: "cone", label: "Cone", position: [-25, 70, 10], radius: 11, correct: false, feedback: "Orbit to a side view. The cone's base sits on the workplane." },
            { id: "bar", label: "Bar", position: [35, -65, 3], radius: 10, correct: false, feedback: "Low and flat, but resting on the workplane." },
          ],
          explanation: "From straight above, a floating shape looks like it's on the floor. Orbit to a low side view to check the gap.",
          competencyId: "A2",
          check: "skill",
        },
        {
          id: "select-text",
          type: "text",
          title: "Selecting on purpose",
          body: "Every edit changes **only what's selected**. Click selects one shape. **Shift + click** adds or removes shapes. Drag a box across empty space to select everything inside it. **Ctrl + A** selects everything.",
        },
        {
          id: "selection",
          type: "diagram",
          name: "selection",
          caption: "Click, Shift + click, or drag a selection box.",
          alt: "Three ways to select shapes.",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Selection drill",
          prompt: "In a new design, drag out a Box, a Cylinder, a Sphere and a Cone. Then select exactly what each line asks for and change its colour.",
          requirements: ["Only the Sphere is red", "The Box and Cone (and nothing else) are green — use Shift + click", "Everything is selected with one key press, then you click empty space to deselect"],
          skills: ["A5"],
        },
        {
          id: "lost-view",
          type: "multipleChoice",
          prompt: "You zoomed and panned so far that your design is off the screen. What's the fastest way back?",
          options: [
            { id: "a", text: "Press F (Zoom to fit) or click Home on the view cube" },
            { id: "b", text: "Start a new design", misconceptionId: "lost-restart" },
            { id: "c", text: "Keep scrolling until it appears" },
          ],
          correctOptionIds: ["a"],
          explanation: "Fit view and Home are your 'get unstuck' buttons. Nothing in your design changed — only the camera moved.",
          competencyId: "A1",
          check: "skill",
        },
        {
          id: "box-select",
          type: "multipleChoice",
          prompt: "You drag a selection box that touches only half of a shape. In Tinkercad, what usually happens?",
          options: [
            { id: "a", text: "Shapes completely inside the box are selected; a shape only partly inside may be left out" },
            { id: "b", text: "Half of the shape is selected", misconceptionId: "half-select" },
          ],
          correctOptionIds: ["a"],
          explanation: "A whole shape is either selected or not. If something is left out, drag a bigger box or Shift + click it.",
          competencyId: "A5",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Inspector's report",
          prompt: "Open the Misplaced Shapes design again. Without any steps, take three screenshots that prove you can control the camera.",
          requirements: [
            "Screenshot 1: a low side view that shows the cube sitting higher than the other shapes",
            "Screenshot 2: a view from underneath, looking up through the workplane at the bottoms of the shapes",
            "Screenshot 3: zoomed in so the cone fills most of the screen",
            "Your design itself is unchanged (no shapes moved)",
          ],
          skills: ["A1", "A2", "A3", "A4"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Upload your three screenshots.",
          accepts: ["screenshot"],
          competencyIds: ["A1", "A2", "A3", "A4"],
          checklist: ["Cube is clearly higher than the others", "View is from below the workplane", "Cone fills the screen"],
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Ask the student to select one shape, then two, then everything, while you watch.",
          lookFors: ["Click to select one shape", "Shift + click to add a second", "Ctrl + A or a selection box for everything", "Clicks empty space to deselect"],
          competencyIds: ["A5"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Why can a design look correct from one view and be wrong from another?",
          sentenceStarters: ["From the top view…", "When I orbited…"],
          competencyIds: ["A1", "A2"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students gain fluent camera control and deliberate selection, the foundation for every later CAD lesson.",
    preparation: [
      "Make sure students can sign in to your Tinkercad Classroom and create a design there.",
      "Download misplaced-shapes.stl and test importing it once on a student device.",
      "Tinkercad usually imports an STL as one shape, so the five pieces can't be selected separately. That is fine here: today is about viewing, not editing.",
      "Tinkercad may place the import so its lowest point rests on the workplane, which hides the 'sunk' sphere. The in-app hotspot viewer shows the true positions; in Tinkercad, focus on the cube sitting higher than the rest.",
    ],
    equipment: ["Student devices with Tinkercad", "A mouse with a scroll wheel is strongly recommended"],
    misconceptions: [
      { id: "orbit-moves", text: "Orbiting rotates the shape.", response: "Orbit, then select the shape and show its dimensions are unchanged. Only the camera moved." },
      { id: "lost-restart", text: "If the view is lost, the design is broken and you must start over.", response: "Demonstrate getting 'lost' on purpose, then press F or Home." },
      { id: "half-select", text: "A selection box can select part of a shape.", response: "Shapes are selected whole. Show a box that misses a shape, then Shift + click to add it." },
    ],
    discussionQuestions: [
      "Which view helped you most to spot the floating cube? Why?",
      "When would you want to look at a design from underneath?",
    ],
    troubleshooting: [
      "Trackpad users: two-finger drag usually orbits and pinch zooms; behaviour varies by device. A mouse makes this lesson much easier.",
      "If an import looks huge or tiny, check that the import units are millimetres.",
      "If right-click opens a browser menu, make sure the pointer is over the 3D workspace.",
    ],
    answerGuidance: [
      "The cube is the floating shape (18 mm gap). The sphere is the sunk shape (mostly below the workplane).",
      "Screenshots: accept any view that clearly shows the evidence asked for.",
    ],
    alternatives: {
      touchDevice: "On tablets, one-finger drag usually orbits, two-finger drag pans and pinch zooms. Use the on-screen view cube and Fit button instead of F.",
    },
  },
};
