import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "print-detective",
  number: 2,
  title: "Print Detective",
  subtitle: "Every print leaves clues",
  domain: "D",
  kind: "lab",
  summary: "Examine six real printed objects, record evidence before you know the answer, then connect each clue to how the part was designed or printed.",
  estimatedMinutes: 50,
  printLevel: "digital",
  competencyIds: ["D11", "D1"],
  prerequisites: ["what-is-3d-printing"],
  vocabulary: [
    { term: "Evidence", definition: "Something you can see or feel that supports your explanation." },
    { term: "Stringing", definition: "Thin hairs of plastic left when the nozzle drips while moving between parts." },
    { term: "Bridge", definition: "A section printed across a gap between two supports, with nothing underneath." },
    { term: "First layer", definition: "The layer printed directly on the build plate. Everything else is built on it." },
    { term: "Support scar", definition: "A rough surface left where temporary support material was removed." },
  ],
  sections: [
    {
      phase: "discover",
      title: "The case files",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Nobody tells you what went wrong. The plastic does.",
          hook: "Six objects. Each one has a story about how it was printed. Your job is to read the clues before anyone tells you the answer.",
          visual: { diagram: "layers-stack" },
        },
        {
          id: "fail-gallery",
          type: "failGallery",
          title: "Fail gallery · guess the crime",
          cards: [
            { id: "spaghetti", nickname: "The Spaghetti Monster", diagram: "failure-spaghetti", clue: "Started fine. Came back an hour later to a bird's nest of plastic noodles.", cause: "The part came loose from the bed (or started in mid-air), so the nozzle kept squirting plastic onto nothing.", fix: "Make sure the part sits flat on the workplane, clean the bed, and watch the first layer go down." },
            { id: "stringing", nickname: "The Cobweb", diagram: "failure-stringing", clue: "Thin hairy strings stretched between two towers, like a spider moved in.", cause: "Melted plastic oozed out of the nozzle while it travelled across the gap.", fix: "Usually a settings fix: lower the temperature a little or turn retraction up. Your design is probably fine." },
            { id: "warping", nickname: "The Banana", diagram: "failure-warping", clue: "The corners curled up off the bed. It rocks on the table.", cause: "The plastic shrank as it cooled, pulling the corners up — big flat parts are the worst.", fix: "Round the sharp corners, add a brim, or keep drafts off the printer." },
            { id: "shift", nickname: "The Glitch", diagram: "failure-layer-shift", clue: "Halfway up, the whole print jumped sideways, like a video game lag spike.", cause: "The print head got bumped or skipped steps — often the nozzle hit a curled-up part.", fix: "Printer problem: check the belts and that nothing blocks the head. Re-print." }
          ],
        },
        {
          id: "rules",
          type: "text",
          title: "Detective rules",
          body: "- Look and touch first. Write what you **notice** before you guess what **happened**.\n- Use the object's label (A–F), not your name. First observations are not graded.\n- Good evidence is specific: where on the object, what it looks or feels like.",
        },
        {
          id: "safety",
          type: "callout",
          tone: "safety",
          title: "Handle with care",
          body: "Some samples are meant to be weak. Don't bend or snap them unless your teacher says so, and keep sharp support bits away from faces.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Investigate",
      blocks: [
        {
          id: "observe",
          type: "observe",
          title: "Print Detective Kit",
          cards: [
            {
              id: "object-a",
              label: "OBJECT A",
              hint: "Look at the underside of the two arms.",
              diagram: "support-scars",
              reveal: "**Support scars.** The arms stuck out flat with nothing under them, so the slicer added temporary supports. Breaking them off left a rough, pitted surface. Designers avoid this by changing the shape or the orientation so supports aren't needed.",
            },
            {
              id: "object-b",
              label: "OBJECT B",
              hint: "Look in the space between the two pegs.",
              diagram: "failure-stringing",
              reveal: "**Stringing.** The nozzle travelled from one peg to the other while still leaking a little melted plastic, leaving hair-thin strings. It's a printer-setting problem (temperature, retraction), not a design problem.",
            },
            {
              id: "object-c",
              label: "OBJECT C",
              hint: "Run a fingernail along the stem. Which way do the lines go?",
              diagram: "hook-standing",
              reveal: "**Layer orientation.** This hook was printed standing up, so every layer line runs across the stem. Layers stick to each other less strongly than plastic sticks to itself, so it would snap along one of those lines. Printed lying flat, the same hook is much stronger.",
            },
            {
              id: "object-d",
              label: "OBJECT D",
              hint: "Compare the short spans with the longest one.",
              diagram: "bridge-span",
              reveal: "**Bridge failure.** The printer can stretch plastic across a short gap and it hardens before it sags. The longest span (60 mm) was too far, so it drooped. Short bridges work; long ones need supports or a redesign.",
            },
            {
              id: "object-e",
              label: "OBJECT E",
              hint: "Look at the thinnest wall on the left. Is it complete?",
              diagram: "wall-thickness",
              reveal: "**Thin wall.** The thinnest wall (0.4 mm) is only one nozzle line wide, so it is fragile, may have gaps, or may be skipped by the slicer. Walls should be several nozzle-widths thick, often 1.2 mm or more, to print solidly.",
            },
            {
              id: "object-f",
              label: "OBJECT F",
              hint: "Flip it over. What do the bottom lines look like?",
              diagram: "first-layer",
              reveal: "**Poor first layer.** The nozzle was a little too high, so the first lines came out round and separate instead of squished flat. The part may have come loose during printing. Every layer depends on the first one.",
            },
          ],
        },
        {
          id: "match",
          type: "matching",
          prompt: "Match each clue to the most likely cause.",
          hint: "Picture what the nozzle was doing at that spot: moving through the air, crossing a gap, or starting on the plate?",
          pairs: [
            { id: "m1", left: "Rough, pitted underside", right: "Support material was removed there" },
            { id: "m2", left: "Hair-thin strings between parts", right: "Plastic leaked while the nozzle travelled" },
            { id: "m3", left: "Long span sagging in the middle", right: "The gap was too long to bridge" },
            { id: "m4", left: "Bottom lines round and separate", right: "Nozzle too high for the first layer" },
            { id: "m5", left: "Wall full of gaps", right: "Wall thinner than a couple of nozzle lines" },
          ],
          explanation: "Each clue points to a different moment in the print: the first layer, the travel moves, the overhangs, or the shape itself.",
          competencyId: "D11",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "Design problem or printer problem?",
      blocks: [
        {
          id: "design-or-printer",
          type: "multipleChoice",
          prompt: "Which TWO of these problems could you fix by changing the design in CAD?",
          hint: "Which problems would still happen on a perfect printer, because of the shape itself?",
          options: [
            { id: "a", text: "Support scars under flat arms" },
            { id: "b", text: "A wall that is too thin to print" },
            { id: "c", text: "Stringing between two pegs", misconceptionId: "all-design" },
            { id: "d", text: "A first layer printed with the nozzle too high", misconceptionId: "all-design" },
          ],
          correctOptionIds: ["a", "b"],
          explanation: "Arms and wall thickness are shapes you control in CAD. Stringing and first-layer height are printer and slicer settings. Knowing the difference tells you where to look first.",
          competencyId: "D11",
          check: "skill",
        },
        {
          id: "layers-check",
          type: "prediction",
          prompt: "Object C is printed again, this time lying flat on its side. Where will it be weakest now?",
          visual: { diagram: "hook-flat" },
          options: [
            { id: "a", text: "It will be stronger along the hook, because the layer lines now run along it" },
            { id: "b", text: "Exactly the same, because it is the same shape", misconceptionId: "shape-only" },
            { id: "c", text: "Weaker, because it is lying down" },
          ],
          expectedOptionId: "a",
          reveal: "Same shape, different layers. Lying flat, the lines run along the hook, so there is no easy layer to split along. You'll test this in the Strength lesson.",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "offline",
          kind: "prove",
          title: "The unknown sample",
          prompt: "Your teacher will hand you a print you haven't seen before. Write a short case report. No hints this time.",
          requirements: [
            "Two specific observations (where, and what it looks or feels like)",
            "Your best explanation of what happened",
            "Design problem or printer problem? Say which and why",
            "One change you would try next",
          ],
          skills: ["D11", "D1"],
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Listen to or read the student's case report on the unknown sample.",
          lookFors: [
            "Observations are specific and come before the explanation",
            "The explanation is supported by the evidence they noticed",
            "Correctly separates design causes from printer/setting causes",
            "Proposes one concrete next change",
          ],
          competencyIds: ["D11", "D1"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Which object fooled you at first? What evidence changed your mind?",
          sentenceStarters: ["At first I thought…", "Then I noticed…", "Next time I will look for…"],
          competencyIds: ["D11"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students learn to read physical evidence on a print and to separate design causes from printer causes, before they design anything themselves.",
    preparation: [
      "Build the Print Detective Kit 1–2 weeks ahead. Label each sample with a sticker (A–F) and nothing else.",
      "OBJECT A — support scars: print excessive-support-object (the T-bracket) standing on its stem with supports ON (touching build plate). Snap the supports off so the rough underside is visible.",
      "OBJECT B — stringing: print two copies of peg-10mm about 40 mm apart in one job. Turn retraction off (or to 0 mm) and raise nozzle temperature 10–15 °C above normal so strings form.",
      "OBJECT C — layer orientation: print orientation-hook standing up (as it loads). Optional: also print one lying flat to keep for the Strength lesson.",
      "OBJECT D — bridge failure: print bridge-test with supports OFF. The 40 mm and 60 mm spans should sag.",
      "OBJECT E — thin wall: print thin-wall-test with normal settings. The 0.4 mm wall is one nozzle line wide and is usually fragile, gappy or missing; the 0.8 mm wall may also flex easily.",
      "OBJECT F — poor first layer: print hole-10mm (the flat plate) with the first layer too high, e.g. raise the Z-offset by about 0.1–0.2 mm or set first-layer height noticeably higher. Watch it and stop if it comes loose. Never lower the nozzle into the bed to make a 'too low' sample.",
      "Optional bonus: print overhang-test with supports OFF to show drooping fins at 60° and 70°.",
      "Pick one extra print for the Prove it task that students haven't seen: a failed print from your bin, a warped corner, or a second copy of a sample printed a different way.",
      "Set up six stations or pass objects around in table groups. Students record observations in the app before opening any reveal.",
    ],
    equipment: ["The six labelled Print Detective samples", "One unknown sample per group for Prove it", "Optional: magnifying glasses or phone cameras for close-ups"],
    misconceptions: [
      { id: "all-design", text: "Every print problem means the design is wrong.", response: "Sort the six samples into 'design' and 'printer settings' piles together. Stringing and first-layer issues happen even with perfect designs." },
      { id: "shape-only", text: "The same shape is always equally strong no matter how it is printed.", response: "Show the layer lines on Object C and ask where the plastic is glued to itself versus melted together in one line." },
    ],
    discussionQuestions: [
      "What is the difference between an observation and an explanation?",
      "Which samples could be fixed in CAD? Which need a printer setting changed?",
      "If you could only test one thing before printing a big part, which of these problems would you check for?",
    ],
    printableObjects: ["excessive-support-object", "peg-10mm (×2)", "orientation-hook", "bridge-test", "thin-wall-test", "hole-10mm", "Optional: overhang-test"],
    slicerSettings: "Starting point for the 'good' parts of each sample: PLA, 0.2 mm layers, 15% infill, 2–3 walls — adjust for your printer. Then change only the one setting listed for each object so its defect is clear.",
    troubleshooting: [
      "If stringing won't appear, raise temperature a little more and lower travel speed; some printers resist stringing.",
      "If the 60 mm bridge prints cleanly, your cooling is good. Keep it and ask students why it still worked.",
      "If the first-layer sample detaches mid-print, keep the failed piece; it is excellent evidence.",
      "If students jump straight to answers, cover the reveals and require two written observations per object first.",
    ],
    answerGuidance: [
      "A support scars; B stringing; C layer orientation (weak across the stem); D bridge failure on long spans; E thin wall; F first layer too high.",
      "Design-fixable: A (shape or orientation), C (orientation), D (shorter span or a support), E (thicker wall). Printer-fixable: B, F.",
      "Prove it: credit any explanation that is consistent with the student's own evidence, even if it differs from yours. The skill is reasoning from evidence.",
    ],
    alternatives: {
      noPrinter: "Borrow samples from a nearby school, library or makerspace, or use the diagrams on each card plus photos of failed prints. Students still record observations before reading reveals.",
    },
  },
};
