import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "print-failures",
  number: 30,
  title: "Print Failures",
  subtitle: "Every failed print is a clue",
  domain: "D",
  kind: "lesson",
  summary: "Name common print failures, read the evidence on a failed part, and decide whether to fix the design or the settings.",
  estimatedMinutes: 50,
  printLevel: "prototype",
  competencyIds: ["D11"],
  prerequisites: ["material-efficiency"],
  vocabulary: [
    { term: "Warping", definition: "Corners of a print curling up off the build plate as the plastic cools and shrinks." },
    { term: "Stringing", definition: "Thin wisps of plastic left between parts when the nozzle travels." },
    { term: "Layer shift", definition: "Upper layers printed out of line with the lower ones." },
    { term: "Under-extrusion", definition: "Too little plastic coming out, leaving gaps and weak, thin lines." },
    { term: "Diagnosis", definition: "Using evidence to decide the most likely cause of a problem." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Read the evidence",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Failure is data.",
          hook: "A failed print isn't a dead end — it's a report from the printer. Learn to read it and you'll know what to change next.",
          visual: { diagram: "failure-spaghetti" },
        },
        {
          id: "explain",
          type: "text",
          body: "Like a doctor, a designer looks at the **symptoms**, thinks of likely **causes**, then changes **one thing** and tests again. Some failures come from the design. Others come from the printer or settings.",
        },
        {
          id: "observe",
          type: "observe",
          title: "Failure cards",
          cards: [
            { id: "warp", label: "Card A", hint: "Look at the corners.", diagram: "failure-warping", reveal: "Warping. The corners cooled, shrank and pulled up. Common causes: poor bed adhesion, a dirty plate, or a large flat part with sharp corners." },
            { id: "string", label: "Card B", hint: "Look between the towers.", diagram: "failure-stringing", reveal: "Stringing. Plastic oozed while the nozzle moved between towers. Usually a settings issue: temperature too hot or retraction too low." },
            { id: "spaghetti", label: "Card C", hint: "What happened to the part?", diagram: "failure-spaghetti", reveal: "Spaghetti. The part came loose or a tall thin part was knocked over, and the printer kept printing in mid-air. Check first-layer adhesion and whether the base is big enough." },
            { id: "shift", label: "Card D", hint: "Compare the top and the bottom.", diagram: "failure-layer-shift", reveal: "Layer shift. The printer lost its position partway up — often a bump, a loose belt or the nozzle hitting a curled-up part." },
            { id: "foot", label: "Card E", hint: "Look at the very bottom edge.", diagram: "failure-elephant-foot", reveal: "Elephant's foot. The first layers squished out wider. Often the nozzle is a little too close or the bed too hot. It can make parts not fit." },
            { id: "under", label: "Card F", hint: "Look at the lines themselves.", diagram: "failure-under-extrusion", reveal: "Under-extrusion. Not enough plastic came out — maybe a partial clog, a tangled spool or printing too fast." },
          ],
        },
        { id: "first-layer", type: "diagram", name: "first-layer", caption: "Many failures start at the first layer: too high, just right, too low.", alt: "First-layer quality: nozzle too high (round lines), just right (flat lines), too low (scraped, transparent)." },
      ],
    },
    {
      phase: "practice",
      title: "Match symptom to cause",
      blocks: [
        {
          id: "match",
          type: "matching",
          prompt: "Match each failure to its most likely cause.",
          pairs: [
            { id: "m-warp", left: "Corners lifted off the plate", right: "Plastic shrinking as it cools; weak bed adhesion" },
            { id: "m-string", left: "Fine hairs between two posts", right: "Plastic oozing during travel moves" },
            { id: "m-shift", left: "Top half offset sideways", right: "The printer lost its position (bump, loose belt, collision)" },
            { id: "m-foot", left: "Bottom edge bulging out", right: "First layers squished too much" },
            { id: "m-under", left: "Gappy, thin, weak lines", right: "Not enough plastic coming out" },
          ],
          explanation: "These are the most likely causes, not the only ones. A good diagnosis names a likely cause, then tests it by changing one thing.",
          competencyId: "D11",
          check: "skill",
        },
        {
          id: "mc-design-or-settings",
          type: "multipleChoice",
          prompt: "A tall, skinny 5 × 5 × 80 mm tower keeps getting knocked over halfway through. What is the best FIRST change?",
          options: [
            { id: "a", text: "Change the design or orientation: widen the base, add a brim, or print it lying down." },
            { id: "b", text: "Print it again exactly the same and hope.", misconceptionId: "just-reprint" },
            { id: "c", text: "Buy a new printer.", misconceptionId: "printer-is-broken" },
          ],
          correctOptionIds: ["a"],
          explanation: "Tiny footprint + tall height = easy to knock over. This one is a design problem. Fix the cause before reprinting.",
          competencyId: "D11",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "The CAD debugger",
      blocks: [
        { id: "thin-viewer", type: "modelViewer", modelId: "thin-wall-test", caption: "Thin Wall Test: 0.4, 0.8, 1.2, 1.6, 2.0 and 3.0 mm walls, 15 mm tall.", showDimensions: true },
        {
          id: "hotspot",
          type: "hotspot",
          prompt: "Some failures are caused by the design. On a printer with a 0.4 mm nozzle, click the wall most likely to come out missing, broken or full of gaps.",
          modelId: "thin-wall-test",
          hotspots: [
            { id: "w04", label: "0.4 mm wall", position: [4.2, 10, 17], radius: 3, correct: true, feedback: "Only one line wide. Some slicers skip walls this thin entirely, and if it prints it snaps easily." },
            { id: "w08", label: "0.8 mm wall", position: [10.8, 10, 17], radius: 3, correct: false, feedback: "Two lines wide — it usually prints, but it's fragile." },
            { id: "w12", label: "1.2 mm wall", position: [17.8, 10, 17], radius: 3, correct: false, feedback: "Three lines wide. Usually prints fine." },
            { id: "w16", label: "1.6 mm wall", position: [25.2, 10, 17], radius: 3, correct: false, feedback: "Four lines wide — sturdy for small parts." },
            { id: "w20", label: "2.0 mm wall", position: [33, 10, 17], radius: 3, correct: false, feedback: "Solid and strong." },
            { id: "w30", label: "3.0 mm wall", position: [41.5, 10, 17], radius: 3, correct: false, feedback: "Very strong — maybe more than a small part needs." },
          ],
          explanation: "When a wall is about as thin as the nozzle line, the printer can't build it reliably. That's a design failure: no setting will make it strong. Make it thicker in CAD.",
          competencyId: "D11",
          check: "practice",
        },
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Debug the Thin Wall Test",
          prompt: "Import the Thin Wall Test and fix it so every wall would print reliably — without making any wall thicker than it needs to be.",
          requirements: ["Every wall at least 1.2 mm thick", "Walls still 15 mm tall on the 2 mm base", "Single grouped model"],
          skills: ["D11", "C9", "E6"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Fix the thin walls",
          steps: ["Import the Thin Wall Test.", "Add solid boxes to thicken the thinnest walls, or rebuild them at the new thickness.", "Group everything."],
        },
        { id: "files", type: "modelDownload", modelIds: ["thin-wall-test"], showImportSteps: true },
        {
          id: "optional",
          type: "text",
          title: "Optional: one test, many failures",
          body: "This community all-in-one tester checks overhangs, bridges, stringing and more in one print. It's a link to the original creator's page.",
        },
        { id: "ext-files", type: "modelDownload", modelIds: ["ext-all-in-one-tester-morejoncarlos"], showImportSteps: false, required: false },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Failure detective",
          prompt: "Your teacher will give you a real failed print (or a photo of one) you haven't seen before. Diagnose it like a pro — no hints this time.",
          requirements: [
            "Name the failure and describe the evidence you see",
            "Give the most likely cause and one other possible cause",
            "Decide: design problem or printer/settings problem — and why",
            "Name ONE change you would make and how you'd test whether it worked",
          ],
          skills: ["D11", "E1"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a photo of the failed print with your diagnosis written underneath (or as a caption).",
          accepts: ["physical_test", "screenshot"],
          competencyIds: ["D11"],
          checklist: ["Failure named", "Evidence described", "Likely cause + one alternative", "Design or settings decision", "One change and how to test it"],
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Listen to the student explain their diagnosis out loud.",
          lookFors: [
            "Uses evidence from the part, not a guess",
            "Separates design causes from printer/settings causes",
            "Proposes changing one thing at a time",
            "Treats the failure as information, not blame",
          ],
          competencyIds: ["D11"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Why change only ONE thing before printing again?",
          sentenceStarters: ["If I change two things at once…", "Changing one thing lets me…"],
          competencyIds: ["D11"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students build a vocabulary of common print failures and a diagnose → change one thing → retest habit, separating design faults from machine and settings faults. Prepares them for CAD ER.",
    preparation: [
      "Collect failed prints over the term in a 'failure bin' — label each with what went wrong. If you have none, print the Thin Wall Test and a small part with no brim on a dirty plate.",
      "For the prove challenge, choose failures students haven't seen in the cards (or mix cards with a real sample).",
    ],
    equipment: ["Failed prints or photos", "Student devices with Tinkercad", "Optional: printed Thin Wall Test"],
    misconceptions: [
      { id: "just-reprint", text: "Reprinting the same file will fix a failure.", response: "Ask: what's different this time? If nothing changed, expect the same result." },
      { id: "printer-is-broken", text: "Any failure means the printer is broken.", response: "Most failures come from design, settings or setup and are fixable. Sort the bin into design vs. settings causes." },
    ],
    discussionQuestions: [
      "Which failures can a designer fix in CAD? Which need the printer or slicer?",
      "Why is it useful to keep failed prints?",
    ],
    printableObjects: ["thin-wall-test (demo)", "Optional: ext-all-in-one-tester-morejoncarlos (link-out)"],
    slicerSettings: "Starting point for the Thin Wall Test: PLA, 0.2 mm layers, 2 walls, 15% infill, 0.4 mm nozzle — adjust for your printer. Some slicers drop walls thinner than the nozzle; that's part of the lesson.",
    troubleshooting: [
      "No failed prints available: use the observe cards plus slicer previews of thin walls and tall towers.",
      "Students argue over a cause: accept any cause that fits the evidence, and push for a test that would tell them apart.",
    ],
    answerGuidance: [
      "Observe cards: A warping, B stringing, C spaghetti, D layer shift, E elephant's foot, F under-extrusion.",
      "Tall tower: a — design/orientation change.",
      "Thin wall: 0.4 mm is the most likely to fail.",
      "Prove: strong answers cite visible evidence, name a likely and alternative cause, classify design vs. settings, and propose one testable change.",
    ],
    alternatives: {
      noPrinter: "Use the observe cards and photos of failed prints (your own or from your printer manufacturer's troubleshooting guide).",
      touchDevice: "Tap failure cards to reveal them; tap hotspots directly.",
    },
  },
};
