import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "repeat-duplicate",
  number: 14,
  title: "Repeat Duplicate",
  subtitle: "Patterns with perfect spacing",
  domain: "B",
  kind: "lesson",
  summary: "Teach Tinkercad one move, then repeat it to build evenly spaced rows and circular patterns.",
  estimatedMinutes: 50,
  printLevel: "digital",
  competencyIds: ["B6"],
  prerequisites: ["duplicate"],
  vocabulary: [
    { term: "Repeat duplicate", definition: "Duplicate, move or rotate the copy once, then press Ctrl+D again to repeat that same change." },
    { term: "Pattern", definition: "Copies of a shape placed at a regular spacing or angle." },
    { term: "Spacing", definition: "The distance from the centre of one copy to the centre of the next." },
    { term: "Radial pattern", definition: "Copies arranged around a centre point, like the spokes of a wheel." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Teach it once. Repeat it forever.",
          hook: "A comb has 20 teeth. A vent has 10 slots. Placing each one by hand takes ages — and one is always a little off.",
          visual: { diagram: "duplicate-pattern" },
        },
        {
          id: "explain",
          type: "text",
          body: "Press **Ctrl+D**, then move or rotate the copy. Without clicking anything else, press **Ctrl+D** again. Tinkercad makes another copy **and repeats your move**. Keep pressing to grow the pattern.",
        },
        {
          id: "show-me",
          type: "showMe",
          title: "A row of five pegs",
          steps: [
            { text: "Place a Cylinder 4 × 4 × 10 mm.", diagram: "exact-dimension" },
            { text: "Press Ctrl+D to duplicate it.", keys: "Ctrl+D" },
            { text: "Move the copy 8 mm on X (type the position, or nudge with the arrow keys).", diagram: "nudge-keys" },
            { text: "Press Ctrl+D three more times. Each new copy lands another 8 mm along.", diagram: "duplicate-pattern", keys: "Ctrl+D" },
          ],
        },
        {
          id: "callout-break",
          type: "callout",
          tone: "warning",
          title: "Don't click away",
          body: "If you click the workplane or select another shape between steps, Tinkercad forgets the move. Then the next Ctrl+D is just a normal duplicate.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You duplicate a peg, move the copy 8 mm, then press Ctrl+D four more times. How far is the last peg from the first?",
          options: [
            { id: "a", text: "40 mm" },
            { id: "b", text: "32 mm", misconceptionId: "repeat-count" },
            { id: "c", text: "8 mm — every copy lands in the same place", misconceptionId: "repeat-same-spot" },
          ],
          expectedOptionId: "a",
          reveal: "The first move made copy 1 at 8 mm. Four repeats add copies at 16, 24, 32 and 40 mm. That's 6 pegs with 5 gaps: 5 × 8 = 40 mm.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Row and wheel",
          steps: [
            "Build the row of five pegs from the Show Me steps.",
            "Now a wheel: place a Box 40 × 3 × 3 mm centred on the workplane.",
            "Press Ctrl+D, then rotate the copy 30° around Z.",
            "Press Ctrl+D four more times. You get 6 bars — 12 spokes, because each bar crosses the centre.",
          ],
        },
        {
          id: "order",
          type: "ordering",
          prompt: "Put the repeat-duplicate steps in order.",
          items: [
            { id: "select", text: "Select the shape" },
            { id: "dup1", text: "Press Ctrl+D" },
            { id: "move", text: "Move or rotate the copy once" },
            { id: "dup2", text: "Press Ctrl+D again (without clicking away)" },
          ],
          explanation: "The move between the first and second Ctrl+D is what Tinkercad remembers and repeats.",
          competencyId: "B6",
          check: "practice",
        },
        {
          id: "spacing",
          type: "measurement",
          prompt: "You need 10 slots evenly spaced across 54 mm, measured from the centre of the first slot to the centre of the last. How far should you move the first copy?",
          answer: 6,
          tolerance: 0,
          unit: "mm",
          hint: "10 slots have 9 gaps between them.",
          explanation: "54 ÷ 9 = 6 mm. Count gaps, not shapes.",
          competencyId: "B6",
          check: "skill",
        },
        {
          id: "angle",
          type: "measurement",
          prompt: "You want 8 copies evenly spaced around a full circle. What angle do you rotate the first copy?",
          answer: 45,
          tolerance: 0,
          unit: "°",
          hint: "A full circle is 360°.",
          explanation: "360 ÷ 8 = 45°. For bars that cross the centre, you only need 180° worth of copies.",
          competencyId: "B6",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Comb",
          prompt: "Make a comb: a 70 × 10 × 3 mm spine with 15 teeth (1.5 × 20 × 3 mm), spaced 4.5 mm centre to centre.",
          requirements: ["15 identical teeth", "Spacing exactly 4.5 mm", "Teeth touch the spine", "Single grouped model"],
          skills: ["B6", "B4", "B2"],
        },
        {
          id: "micro-mc",
          type: "multipleChoice",
          prompt: "Your third tooth jumped to a strange spot and the pattern broke. What probably happened?",
          options: [
            { id: "a", text: "You clicked somewhere else between Ctrl+D presses, so Tinkercad forgot the move." },
            { id: "b", text: "Repeat duplicate only works three times.", misconceptionId: "repeat-limit" },
            { id: "c", text: "The teeth were too thin to copy." },
          ],
          correctOptionIds: ["a"],
          explanation: "Delete the broken copies, select the last good tooth, and teach the move again: Ctrl+D, move, Ctrl+D.",
          competencyId: "B6",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Cooling vent cover",
          prompt: "Design a vent cover 60 × 40 × 3 mm with 8 slot holes (2 × 30 mm) cut all the way through. Slots are 6 mm apart centre to centre, and the whole set of slots is centred on the plate. Add a 12-spoke decoration (radial pattern) on a separate 30 mm disc. No steps.",
          requirements: [
            "8 identical slots, 6 mm centre to centre",
            "Slot pattern centred on the plate",
            "Slots cut through the plate",
            "12 evenly spaced spokes on the disc",
            "Plate and disc are each a single group",
          ],
          skills: ["B6", "B3", "B4", "B2"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a class design link or a top-view screenshot of both parts.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["B6"],
          checklist: ["Slots look evenly spaced in the top view", "Spokes are evenly spaced", "Each part is one group"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Why do you divide by the number of gaps instead of the number of shapes when you plan spacing?",
          sentenceStarters: ["The number of gaps is…", "If I divided by the number of shapes…"],
          competencyIds: ["B6"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students use repeat duplicate for linear and radial patterns and plan spacing with the gaps-not-shapes rule.",
    preparation: ["Practise the wheel demo once: repeat duplicate is easy to break by clicking away, which is worth showing on purpose."],
    equipment: ["Student devices with Tinkercad"],
    misconceptions: [
      { id: "repeat-count", text: "The number of Ctrl+D presses after the move equals the total number of gaps.", response: "Draw the pegs on the board and number every gap, including the first move." },
      { id: "repeat-same-spot", text: "Repeat duplicate stacks every copy in the same place.", response: "That is plain duplicate. The move in between is what gets repeated — demo both." },
      { id: "repeat-limit", text: "Repeat duplicate has a small limit.", response: "Press Ctrl+D twenty times on the projector. The limit is clicking away, not the count." },
    ],
    discussionQuestions: ["Where do you see radial patterns in everyday objects?", "What other changes besides moving could Tinkercad repeat?"],
    troubleshooting: [
      "Radial copies orbit off to one side: the bar wasn't centred on the point you wanted to rotate around. A bar centred on the hub rotates around its own middle.",
      "Pattern is in the wrong direction: Ctrl+Z, then teach the move again on the correct axis.",
    ],
    answerGuidance: [
      "Comb: first tooth at one end, Ctrl+D, move 4.5 mm on X, then Ctrl+D 13 more times (15 teeth = 14 gaps = 63 mm).",
      "Vent: 8 slots → 7 gaps × 6 mm = 42 mm span of centres; group the slots and align them to the plate centre before grouping with the plate.",
      "Spokes: 6 bars through the centre at 30° steps give 12 spokes (or 12 half-length spokes at 30° that start at the centre).",
    ],
    alternatives: { touchDevice: "Use the Duplicate button repeatedly; type the move in the position fields rather than dragging." },
  },
};
