import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "ruler",
  number: 18,
  title: "The Ruler Tool",
  subtitle: "Place anything at an exact distance",
  domain: "C",
  kind: "lesson",
  summary: "Use Tinkercad's Ruler to measure from a point you choose and to place shapes at exact distances from each other.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["C1", "C2"],
  prerequisites: ["boss-die"],
  vocabulary: [
    { term: "Ruler", definition: "A Tinkercad tool you drop at a point; it shows distances from that point to the selected shape." },
    { term: "Origin", definition: "The point you measure from. With the Ruler, it's wherever you place it." },
    { term: "Offset", definition: "A set distance between two things, such as 5 mm from an edge." },
    { term: "Edge-to-edge vs centre-to-centre", definition: "Two ways to measure spacing: between the nearest edges, or between the middles." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "'About here' isn't a measurement.",
          hook: "A screw hole 5 mm from the edge of a bracket. A button 12 mm from the corner of a case. Real designs say exactly where things go.",
          visual: { diagram: "ruler-tool" },
        },
        {
          id: "explain",
          type: "text",
          body: "Press **R** (or drag the Ruler from the toolbar) and click to drop it — a corner of a shape is a great spot. Now select any shape: numbers show its distance from the Ruler on X, Y and Z. **Click a number and type** to move the shape exactly.",
        },
        {
          id: "cube-view",
          type: "modelViewer",
          modelId: "axis-cube-20mm",
          caption: "The 20 mm Axis Cube. One notch marks X, two mark Y, three mark the top (Z).",
          showDimensions: true,
        },
        {
          id: "show-me",
          type: "showMe",
          title: "Put a peg exactly 10 mm from the cube",
          steps: [
            { text: "Import the Axis Cube and drop the Ruler on its front-left bottom corner.", diagram: "ruler-tool", keys: "R" },
            { text: "Add a Cylinder 6 × 6 × 10 mm anywhere on the workplane." },
            { text: "Select the cylinder. Read the X and Y numbers — they show its distance from the Ruler." },
            { text: "Click the X distance and type 30. The cylinder's near edge is now 30 mm from the corner — 10 mm past the cube's 20 mm face.", diagram: "exact-dimension" },
          ],
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "The Ruler is on the cube's left corner. You type 30 for the cylinder's X distance. Where is the gap between the cube and cylinder?",
          visual: { diagram: "ruler-tool" },
          options: [
            { id: "a", text: "10 mm — the cube takes up the first 20 mm" },
            { id: "b", text: "30 mm", misconceptionId: "ruler-from-object" },
            { id: "c", text: "It depends on the cylinder's height", misconceptionId: "ruler-z" },
          ],
          expectedOptionId: "a",
          reveal: "The Ruler measures from where you placed it, not from the nearest shape. 30 − 20 = 10 mm of gap. Always ask: where is my Ruler?",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        { id: "files", type: "modelDownload", modelIds: ["axis-cube-20mm", "mystery-fit-object"], showImportSteps: true },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Ruler practice",
          steps: [
            "Create a new design and import the Axis Cube.",
            "Follow the Show Me steps to place the cylinder 10 mm from the cube.",
            "Move the Ruler to a different corner. Watch the numbers change for the same cylinder.",
            "Place a second cylinder exactly 10 mm behind the cube (on Y) using the Ruler.",
          ],
        },
        {
          id: "centre-calc",
          type: "measurement",
          prompt: "The Ruler shows a peg's left edge at 6 mm. The peg is 8 mm wide. How far is the peg's centre from the Ruler?",
          answer: 10,
          tolerance: 0,
          unit: "mm",
          hint: "The centre is half the width past the edge.",
          explanation: "6 + 8 ÷ 2 = 10 mm. Some measurements need edges; others need centres. Know which one you are reading.",
          competencyId: "C1",
          check: "skill",
        },
        {
          id: "gap-calc",
          type: "measurement",
          prompt: "On the Mystery Fit Object, the round peg (8 mm wide) is centred 10 mm from the left end and the square post (6 mm wide) is centred 25 mm from the left end. What is the gap between them, edge to edge?",
          visual: { modelId: "mystery-fit-object" },
          answer: 8,
          tolerance: 0,
          unit: "mm",
          hint: "Start with centre-to-centre (25 − 10), then subtract half of each width.",
          explanation: "25 − 10 = 15 mm centre to centre. 15 − 4 − 3 = 8 mm edge to edge.",
          competencyId: "C2",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Corner holes",
          prompt: "Make a 50 × 30 × 3 mm plate with four 4 mm holes. Each hole's centre is exactly 5 mm from the two nearest edges.",
          requirements: ["Hole centres 5 mm from each edge", "Holes cut through", "Single grouped model"],
          skills: ["C1", "C2", "B3"],
        },
        {
          id: "micro-mc",
          type: "multipleChoice",
          prompt: "You typed 5 for a hole's X distance, but the hole's centre is 7 mm from the edge. Why?",
          options: [
            { id: "a", text: "The Ruler was reading to the hole's edge, so 5 mm puts the edge at 5 and the centre at 5 + 2 = 7." },
            { id: "b", text: "Holes always shift 2 mm when grouped.", misconceptionId: "holes-shift" },
            { id: "c", text: "The plate is the wrong size." },
          ],
          correctOptionIds: ["a"],
          explanation: "For a centre at 5 mm with a 4 mm hole, the edge goes at 5 − 2 = 3 mm.",
          competencyId: "C1",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Cap layout",
          prompt: "Import the Mystery Fit Object. Without moving it, add three markers using the Ruler: a 4 mm cube sitting on the base exactly 3 mm from its right end and centred front-to-back; a 2 mm tall disc (10 mm wide) centred exactly on top of the round peg; and a 5 mm sphere exactly 6 mm in front of the base. No steps.",
          requirements: [
            "Cube is 3 mm from the right end and centred front-to-back",
            "Disc is centred on the peg and sits on its top",
            "Sphere is 6 mm in front of the base",
            "Mystery Fit Object has not moved",
            "Ruler visible in your screenshot",
          ],
          skills: ["C1", "C2", "B4"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a screenshot for each marker with the Ruler distances showing, or a class design link.",
          accepts: ["screenshot", "design_url"],
          competencyIds: ["C1", "C2"],
          checklist: ["Ruler numbers are readable", "Each marker's distance matches the requirement"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Where did you put the Ruler for each marker, and why did that spot make the job easier?",
          sentenceStarters: ["For the cube I put the Ruler…", "That made it easier because…"],
          competencyIds: ["C1"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students place the Ruler deliberately and use typed distances to position shapes relative to other shapes, including edge vs centre reasoning.",
    preparation: [
      "Import the Axis Cube and Mystery Fit Object once to check they arrive at the expected sizes (20 mm cube; 34 × 22 mm base).",
      "Practise switching the Ruler's measurement between edges and centre if your version of Tinkercad offers it, so you can demonstrate.",
    ],
    equipment: ["Student devices with Tinkercad"],
    misconceptions: [
      { id: "ruler-from-object", text: "The Ruler measures from the nearest shape.", response: "Move the Ruler while one shape is selected; the numbers change even though nothing else moved." },
      { id: "ruler-z", text: "Shape height changes horizontal distances.", response: "Change the cylinder's height live; the X number stays the same." },
      { id: "holes-shift", text: "Holes move when grouped.", response: "Ungroup and re-read the Ruler distance — the hole didn't move; the reading was to its edge." },
    ],
    discussionQuestions: ["When is it better to measure centre to centre, and when edge to edge?", "Where would you place the Ruler to design a part that must line up with another part?"],
    troubleshooting: [
      "No distance numbers appear: the Ruler isn't placed yet, or no shape is selected.",
      "Numbers seem to measure the wrong thing: check whether the Ruler is reading to the shape's edge or its centre.",
      "Ruler landed in mid-air or on the wrong corner: press R again and click the exact corner of the object.",
    ],
    answerGuidance: [
      "Corner holes: with the Ruler on the plate corner and edge readings, each 4 mm hole's near edge is at 3 mm; centres at 5 mm.",
      "Prove: cube right face at 31 mm from the left end (34 − 3), cube Y edges at 9–13 mm across the 22 mm base; disc centred at X 10, Y 11, bottom at Z 22; sphere's back edge 6 mm in front of the base's front face.",
    ],
    alternatives: { touchDevice: "Use the Ruler button in the toolbar and tap to place it; tap a distance to type a value." },
  },
};
