import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "strength",
  number: 25,
  title: "Strength",
  subtitle: "Layer direction, walls and infill",
  domain: "D",
  kind: "lab",
  summary: "Load-test the same hook printed two ways, then learn how walls and infill change strength.",
  estimatedMinutes: 55,
  printLevel: "required",
  competencyIds: ["D7", "D8", "D9"],
  prerequisites: ["orientation"],
  vocabulary: [
    { term: "Infill", definition: "The pattern printed inside a part to fill it, given as a percentage." },
    { term: "Walls (perimeters)", definition: "The solid outlines printed around the outside of every layer." },
    { term: "Load test", definition: "Adding weight step by step until a part bends or breaks, and recording when." },
    { term: "Failure point", definition: "The exact place a part breaks." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Predict the break",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Two identical files. Which one holds more?",
          hook: "Your teacher printed the Orientation Hook twice — once standing, once flat. Same plastic, same settings. Today you load them until something gives.",
          visual: { diagram: "orientation-strength" },
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "How will the two hooks compare in the load test?",
          options: [
            { id: "a", text: "The flat hook holds noticeably more weight" },
            { id: "b", text: "They hold about the same — same file, same plastic", misconceptionId: "same-file-same-strength" },
            { id: "c", text: "The standing hook holds more", misconceptionId: "upright-stronger" },
          ],
          expectedOptionId: "a",
          reveal: "Usually the flat hook wins by a lot, and the standing hook snaps cleanly along a layer line near the bend. Exact numbers vary with printer, plastic and settings — that's why you test.",
        },
        {
          id: "safety",
          type: "callout",
          tone: "safety",
          title: "Load-test safely",
          body: "Wear eye protection — plastic can snap and fly. Hang weight in a bag over a tray, close to the floor. Add weight slowly, a little at a time. Keep hands and feet out from under the bag. Never pull or yank by hand.",
        },
      ],
    },
    {
      phase: "practice",
      title: "The load test",
      blocks: [
        {
          id: "show-me",
          type: "showMe",
          title: "Run the load test",
          steps: [
            { text: "Put on eye protection. Clamp or hold the hook's long stem firmly at a table edge, with the curved end facing up and out.", diagram: "hook-standing" },
            { text: "Hang an empty bag on the curved end, just above a tray on the floor." },
            { text: "Add weight in equal steps (for example 100 g at a time — washers, coins or small water bottles). Wait 5 seconds after each step." },
            { text: "Record the total weight at each step and when the hook first bends and when it breaks." },
            { text: "Look at the break. Is it a clean line along a layer, or torn plastic?", diagram: "layers-stack" },
            { text: "Repeat with the other hook. Same clamp, same steps.", diagram: "hook-flat" },
          ],
        },
        {
          id: "lab-evidence",
          type: "uploadEvidence",
          prompt: "Record your load test: a table of weight added vs. what happened for BOTH hooks, plus a close-up photo of each failure point.",
          accepts: ["physical_test", "screenshot"],
          competencyIds: ["D7"],
          checklist: ["Weight at first bend and at break for both hooks", "Photo of each break", "Which hook held more, and by how much"],
        },
        {
          id: "mc-break",
          type: "multipleChoice",
          prompt: "The standing hook broke in a perfectly flat, clean line. What does that tell you?",
          hint: "A clean, flat break follows a line that was already in the part. Which lines run all the way across?",
          options: [
            { id: "a", text: "It split between two layers — the layer boundary was the weakest place." },
            { id: "b", text: "The plastic was old or bad.", misconceptionId: "bad-plastic" },
            { id: "c", text: "The clamp cut it." },
          ],
          correctOptionIds: ["a"],
          explanation: "A clean, flat break along a layer line is the signature of layer separation. That's the weakness orientation can design out.",
          competencyId: "D7",
          check: "skill",
        },
      ],
    },
    {
      phase: "apply",
      title: "Inside the part",
      blocks: [
        {
          id: "explain-inside",
          type: "text",
          body: "Most prints aren't solid. The slicer prints a few **walls** around the outside and a lighter **infill** pattern inside. Both change strength, weight and print time.",
        },
        { id: "walls", type: "diagram", name: "walls-perimeters", caption: "Walls are the solid outline; infill fills the middle.", alt: "Cross-section showing perimeters (outer walls) and infill in the middle." },
        { id: "infill", type: "diagram", name: "infill-patterns", caption: "10%, 20% and 50% infill. More infill = heavier and slower.", alt: "Cut-away views of 10%, 20% and 50% infill inside a part with solid walls." },
        {
          id: "match",
          type: "matching",
          prompt: "Match each setting change to its most likely effect.",
          hint: "Walls are the outer skin, infill is the inside, and orientation sets which way the layers run.",
          pairs: [
            { id: "walls-up", left: "2 walls → 4 walls", right: "Thin parts like hooks get much stiffer" },
            { id: "infill-up", left: "15% → 80% infill", right: "Heavier and slower; stronger, but with diminishing returns" },
            { id: "infill-down", left: "15% → 5% infill", right: "Faster and lighter, but top surfaces may sag" },
            { id: "orient", left: "Standing → flat", right: "Load runs along layers instead of across them" },
          ],
          explanation: "For thin parts, most strength comes from the walls, because bending loads are carried at the outside surface. Infill helps, but doubling it rarely doubles strength.",
          competencyId: "D8",
          check: "practice",
        },
        {
          id: "slide-infill-strong",
          type: "slider",
          prompt: "A bracket may use **no more than 15 g**. Find the **strongest** infill (highest %) that fits.",
          scene: "infill",
          min: 0,
          max: 100,
          step: 5,
          start: 80,
          unit: "%",
          answer: 30,
          tolerance: 0,
          hint: "Slide down until the grams reach 15 or less.",
          explanation: "At **30%** it's exactly 15 g. More infill = stronger and heavier; walls matter too, so many makers add walls before adding infill.",
          competencyId: "D8",
        },
        {
          id: "mc-walls",
          type: "multipleChoice",
          prompt: "A thin 8 mm hook is too weak. You can change ONE setting. Which is usually the best first try?",
          hint: "A thin hook is mostly skin. Which setting makes the skin thicker?",
          options: [
            { id: "a", text: "Add more walls (for example 2 → 4)" },
            { id: "b", text: "Raise infill to 100%", misconceptionId: "infill-is-strength" },
            { id: "c", text: "Use thinner layers", misconceptionId: "thin-layers-stronger" },
          ],
          correctOptionIds: ["a"],
          explanation: "In a thin part the walls carry most of the load. Extra walls often add more strength for less plastic than maxing out infill. Test it to be sure on your printer.",
          competencyId: "D9",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Rescue the standing hook",
          prompt: "Sometimes a part MUST print standing up (for example, it won't fit on the plate lying down). Redesign the hook so it survives more weight while still printing standing up. You decide how.",
          requirements: [
            "Prints standing up, same overall height (58 mm)",
            "At least one design change aimed at the weak bend (thickness, a gusset, a rounded inside corner…)",
            "Recommend wall count and infill, with a reason for each",
            "Predict how much more weight it will hold — and if printed, record the real result",
          ],
          skills: ["D7", "D8", "D9", "E4"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Redesign the hook",
          steps: ["Import the Orientation Hook.", "Keep it standing (58 mm tall).", "Change the geometry at the bend — no step-by-step this time."],
        },
        { id: "files", type: "modelDownload", modelIds: ["orientation-hook"], showImportSteps: true },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your redesign, your settings recommendation, and your prediction (plus test results if it was printed).",
          accepts: ["design_url", "screenshot", "stl", "physical_test"],
          competencyIds: ["D7", "D8", "D9"],
          checklist: ["Still 58 mm tall and standing", "Change at the bend explained", "Walls and infill recommended with reasons", "Prediction stated"],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "If you could change only one thing to make a part stronger — orientation, walls or infill — which would you choose and why?",
          sentenceStarters: ["I would change… because…", "The load test showed…"],
          competencyIds: ["D7", "D9"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students gather physical evidence that layer direction controls strength, then reason about walls and infill as the other strength levers.",
    preparation: [
      "Print the Orientation Hook twice per group with identical settings: once standing (58 mm tall, as imported) and once lying flat (10 mm tall).",
      "Set up a test station: a clamp or heavy-duty binder clip at a table edge, a cloth bag, a tray underneath, and weights in equal steps (100 g washers, coins in bags, or 250 ml water bottles).",
      "Have eye protection for every student at the station.",
    ],
    equipment: ["Printed hooks (two orientations)", "Clamp", "Cloth bag", "Weights in equal steps", "Eye protection", "Tray or bin under the test area"],
    misconceptions: [
      { id: "same-file-same-strength", text: "The same file always makes an equally strong part.", response: "The file sets the shape; the printer sets the layer direction. Show both breaks side by side." },
      { id: "upright-stronger", text: "Printing a hook upright, the way it's used, makes it stronger.", response: "Look at the break surface: it's flat along a layer line." },
      { id: "bad-plastic", text: "A clean break means the filament was bad.", response: "Both hooks used the same spool. Ask why only one broke along a layer." },
      { id: "infill-is-strength", text: "100% infill is always the best way to add strength.", response: "Compare grams and print time in the slicer for 4 walls vs. 100% infill on a thin hook." },
      { id: "thin-layers-stronger", text: "Thinner layers make a part much stronger.", response: "Thinner layers mostly improve looks and add time. Orientation and walls matter more for strength." },
    ],
    discussionQuestions: [
      "How much more did the flat hook hold? Was every group's result the same?",
      "Why might a designer still choose the weaker orientation?",
      "Where does a hook carry most of its stress — inside or near the surface?",
    ],
    printableObjects: ["orientation-hook (standing)", "orientation-hook (flat)", "Optional: student redesigned hooks"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2 walls for BOTH hooks so the only difference is orientation — adjust for your printer. For the walls/infill demo, reprint one hook with 4 walls.",
    troubleshooting: [
      "Hook slips in the clamp: clamp the stem over a longer length, or pad it with tape.",
      "Flat hook bends without breaking: record the weight at which it bends noticeably — that's a valid result.",
      "Bag swings: lower it closer to the tray and add weight gently.",
    ],
    answerGuidance: [
      "Prediction: a (flat stronger) is typical; accept any well-reasoned prediction and focus on the evidence.",
      "Break reading: a — layer separation.",
      "Single setting: a — more walls (as a usual first try, not a universal rule).",
      "Prove: strong redesigns thicken the bend, add a gusset or round the inside corner (stress concentrates at sharp corners) and recommend more walls.",
    ],
    alternatives: {
      noPrinter: "Use a teacher demo with pre-printed hooks, or model it with stacked craft sticks glued face-to-face vs. a single long stick.",
      touchDevice: "Students can complete the redesign on a tablet; type dimensions directly.",
    },
  },
};
