import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "supports",
  number: 28,
  title: "Supports",
  subtitle: "Use them when you must — design them out when you can",
  domain: "D",
  kind: "lesson",
  summary: "Decide when a part needs support material, and redesign parts so they hold themselves up.",
  estimatedMinutes: 50,
  printLevel: "prototype",
  competencyIds: ["D4", "D5"],
  prerequisites: ["bridging"],
  vocabulary: [
    { term: "Support material", definition: "Temporary scaffolding the slicer adds under overhangs, removed after printing." },
    { term: "Self-supporting", definition: "Designed so every overhang is gentle enough to print without supports." },
    { term: "Support scar", definition: "A rough mark left where support was removed." },
    { term: "Gusset", definition: "A triangle-shaped brace in a corner that adds strength and can replace an overhang." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Scaffolding for plastic",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Supports work. They also cost you.",
          hook: "Support material lets a printer build a flat ledge on air. But it adds time and plastic, it ends up in the trash, and it leaves scars. Good designers need less of it.",
          visual: { diagram: "supports" },
        },
        {
          id: "explain",
          type: "text",
          body: "The slicer can add **supports** under steep overhangs — a breakable scaffold you pull off later. You can usually avoid them three ways: change the angle, change the orientation, or split the part.",
        },
        { id: "scars", type: "diagram", name: "support-scars", caption: "Supports leave rough patches where they touched the part.", alt: "Rough marks left on a surface where support material was removed." },
        {
          id: "predict-1",
          type: "prediction",
          prompt: "Support or no support? A 30 mm cube with a 10 mm cylinder hole going straight down through it, printed sitting flat.",
          options: [
            { id: "yes", text: "Needs support", misconceptionId: "holes-need-support" },
            { id: "no", text: "No support needed" },
          ],
          expectedOptionId: "no",
          reveal: "The hole's walls are straight up and down, so every layer sits on the one below. No overhang — no support.",
        },
        {
          id: "predict-2",
          type: "prediction",
          prompt: "Support or no support? A mushroom: a 10 mm stem with a flat-bottomed 40 mm cap on top, printed standing up.",
          options: [
            { id: "yes", text: "Needs support" },
            { id: "no", text: "No support needed", misconceptionId: "printer-figures-it-out" },
          ],
          expectedOptionId: "yes",
          reveal: "The flat underside of the cap sticks out 15 mm on every side with nothing below — a 90° overhang. It needs support, or a cone-shaped underside, or to print upside down on its flat cap.",
        },
        {
          id: "predict-3",
          type: "prediction",
          prompt: "Support or no support? A letter A, 40 mm tall, printed standing up.",
          options: [
            { id: "yes", text: "Needs support", misconceptionId: "any-lean-needs-support" },
            { id: "no", text: "Probably no support needed" },
          ],
          expectedOptionId: "no",
          reveal: "The legs lean gently, well inside 45° from vertical, and the crossbar is a short bridge. Most printers do this without support.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Same part, two designs",
      blocks: [
        { id: "viewer-before", type: "modelViewer", modelId: "excessive-support-object", caption: "Before: flat arms. The slicer fills the space under both arms with support.", showLayers: true },
        { id: "viewer-after", type: "modelViewer", modelId: "redesigned-support-object", caption: "After: 45° chamfers under each arm. Same top shape, no support needed.", showLayers: true },
        { id: "self-supporting", type: "diagram", name: "self-supporting", caption: "Swap a flat overhang for a 45° slope and the part holds itself up.", alt: "Replacing a flat overhang with a 45° chamfer so the part supports itself." },
        {
          id: "mc-compare",
          type: "multipleChoice",
          prompt: "The redesigned T-bracket uses a little more plastic in the part itself. Why is it still usually the better design? Choose all that apply.",
          options: [
            { id: "a", text: "No support to print, so less plastic is wasted overall" },
            { id: "b", text: "No support scars on the underside" },
            { id: "c", text: "The chamfers brace the arms, so they are stronger" },
            { id: "d", text: "It will print in exactly half the time", misconceptionId: "exact-time-claims" },
          ],
          correctOptionIds: ["a", "b", "c"],
          explanation: "Support is plastic you throw away. The chamfers replace it with useful material that also strengthens the arms. It usually prints faster too, but how much depends on the slicer.",
          competencyId: "D5",
          check: "skill",
        },
        {
          id: "order-strategies",
          type: "ordering",
          prompt: "A part needs support. Put these fixes in the order a designer usually tries them, from easiest to most work.",
          items: [
            { id: "rotate", text: "Rotate the part so the overhang faces up or lies flat" },
            { id: "angle", text: "Change the overhang to 45° or less (chamfer, cone, gusset)" },
            { id: "split", text: "Split the part into pieces that each print flat, then join them" },
            { id: "support", text: "Turn on supports and plan for clean-up" },
          ],
          explanation: "Rotating costs nothing. Reshaping is a small design change. Splitting adds assembly. Supports always work but cost time, plastic and finish. This order is a habit, not a law.",
          competencyId: "D5",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "When support is the right call",
      blocks: [
        {
          id: "mc-when",
          type: "multipleChoice",
          prompt: "Which part is a reasonable place to just use supports?",
          options: [
            { id: "a", text: "A small figure with outstretched arms, where changing the arms would ruin the look" },
            { id: "b", text: "A box with a straight-sided hole", misconceptionId: "holes-need-support" },
            { id: "c", text: "A flat 3 mm coaster", misconceptionId: "always-support" },
          ],
          correctOptionIds: ["a"],
          explanation: "Supports are a tool, not a failure. When the shape matters more than the time and clean-up, use them — on purpose.",
          competencyId: "D4",
          check: "skill",
        },
        {
          id: "optional",
          type: "text",
          title: "Optional: test your support settings",
          body: "This community support-removal test shows how easily supports come off with your slicer settings. It's a link to the original creator's page.",
        },
        { id: "ext-files", type: "modelDownload", modelIds: ["ext-support-removal-test-unclejessy"], showImportSteps: false, required: false },
        {
          id: "safety",
          type: "callout",
          tone: "safety",
          title: "Removing supports",
          body: "Wear eye protection — support bits can snap off and fly. Use pliers, not fingernails, and cut or pull away from your body.",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Pencil cup with a ledge",
          prompt: "Design a pencil cup with a ledge around the top rim (for sticky notes or paper clips). It must print with zero support in the orientation you choose.",
          requirements: [
            "Cup at least 70 mm tall with walls at least 2 mm",
            "Ledge sticks out at least 15 mm past the cup wall",
            "No overhang steeper than 45° from vertical, and no flat ledge on air",
            "Placed in Tinkercad in your print orientation, sitting on the workplane",
            "One sentence explaining which strategy you used: angle, orientation or split",
          ],
          skills: ["D4", "D5", "D2", "B3"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Design the pencil cup",
          steps: ["Create a new design.", "Sketch the side view on paper first — where is the overhang?", "Build it your way. No steps this time."],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a side-view screenshot and your one-sentence strategy. If it was printed, add a photo of the underside of the ledge.",
          accepts: ["screenshot", "design_url", "stl", "physical_test"],
          competencyIds: ["D4", "D5"],
          checklist: ["Side view shows the ledge underside", "Strategy named", "Sitting on the workplane"],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "When is it OK to use supports, and when should you redesign instead?",
          sentenceStarters: ["Supports make sense when…", "I would redesign when…"],
          competencyIds: ["D4", "D5"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students learn what supports do, when they're needed, and how to redesign so parts print without them — a key design-for-printing habit.",
    preparation: [
      "If possible, print both T-brackets: excessive-support-object WITH supports on, and redesigned-support-object with supports off. Weigh both including the removed support.",
      "Have pliers and eye protection ready if students remove supports.",
    ],
    equipment: ["Student devices with Tinkercad", "Optional: printed T-brackets", "Pliers and eye protection", "Optional: kitchen scale"],
    misconceptions: [
      { id: "holes-need-support", text: "Any hole or empty space needs support.", response: "Vertical holes have straight walls. Only the ceiling of a sideways hole can overhang." },
      { id: "printer-figures-it-out", text: "The printer will figure out how to print anything.", response: "Show the slicer preview with supports off: the cap's first layer is printed on air." },
      { id: "any-lean-needs-support", text: "Any slanted surface needs support.", response: "Revisit the overhang test: 20°–45° fins printed fine." },
      { id: "exact-time-claims", text: "A design change gives an exact, predictable time saving.", response: "Slice both brackets and compare. Savings depend on the slicer and settings." },
      { id: "always-support", text: "It's safest to always turn supports on.", response: "Slice a flat coaster with supports on: nothing is added, but on many parts you'd waste plastic for nothing. Turn them on when there's a reason." },
    ],
    discussionQuestions: [
      "What did you notice about the underside of the supported bracket?",
      "Which strategy (rotate, reshape, split) was most useful in your pencil cup?",
    ],
    printableObjects: ["excessive-support-object (with supports)", "redesigned-support-object (no supports)", "Optional: student pencil cups"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls. Supports: on, 'touching build plate' only, for the original T-bracket; off for the redesign — adjust for your printer.",
    troubleshooting: [
      "Supports won't come off: print a little cooler, or increase the support gap in your slicer.",
      "Slicer adds support to the redesign: check the overhang threshold setting (often set around 45–55°).",
    ],
    answerGuidance: [
      "Predictions: cube hole — no; mushroom — yes; letter A — probably no.",
      "Compare: a, b, c.",
      "Ordering: rotate → reshape → split → supports (as a typical habit).",
      "When to support: a.",
      "Pencil cup: chamfered (cone-shaped) ledge underside at ≤ 45°, or the cup printed upside down on its ledge (the cup floor then becomes a bridge — check its span), or a separate ledge ring.",
    ],
    alternatives: {
      noPrinter: "Use the slicer's support preview on student designs as the test result.",
      touchDevice: "Tap to rotate shapes and type angles directly.",
    },
  },
};
