import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "testing",
  number: 36,
  title: "Testing",
  subtitle: "A test is only useful if the result is written down",
  domain: "F",
  kind: "lesson",
  summary: "Plan fair, repeatable tests for each constraint, decide pass/fail before testing, run them on prototype 1 and record honest results.",
  estimatedMinutes: 50,
  printLevel: "prototype",
  competencyIds: ["F6", "G4"],
  prerequisites: ["prototype"],
  vocabulary: [
    { term: "Test plan", definition: "For each constraint: how you'll test it and what counts as a pass." },
    { term: "Pass criteria", definition: "The result you need, decided BEFORE the test." },
    { term: "Repeatable", definition: "Someone else could run the same test and get a similar result." },
    { term: "User test", definition: "Watching your real user try the prototype." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "'It works' is not a test result.",
          hook: "'The 18 mm marker slid in with a small gap, 5 out of 5 tries' is. Testing turns your opinion into evidence.",
          visual: { diagram: "measure-critical" },
        },
        {
          id: "explain",
          type: "text",
          body: "Every constraint needs a test. Decide the **pass criteria before** you test — otherwise it's easy to talk yourself into a pass.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You test a clip once and it holds. Your user will clip and unclip it 20 times a day. Is one try enough?",
          options: [
            { id: "a", text: "No — repeat the test several times, the way the user actually uses it." },
            { id: "b", text: "Yes — it worked, so it passes.", misconceptionId: "one-try-enough" },
          ],
          expectedOptionId: "a",
          reveal: "Clips often crack after a few uses. Testing 10 or 20 times copies real use and shows problems one try would hide.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Plan a fair test",
      blocks: [
        {
          id: "good-test-mc",
          type: "multipleChoice",
          prompt: "Constraint: 'Holds a 600 g water bottle without tipping.' Which is the best test?",
          options: [
            { id: "a", text: "Put a full 600 g bottle in it on a flat desk, bump the desk lightly 5 times, and record if it tips." },
            { id: "b", text: "Look at it and decide it seems stable.", misconceptionId: "looks-pass" },
            { id: "c", text: "Put an empty bottle in it once." },
          ],
          correctOptionIds: ["a"],
          explanation: "A good test uses the real load, copies real use, repeats, and has a clear pass/fail. An empty bottle doesn't test the 600 g constraint.",
          competencyId: "F6",
          check: "skill",
        },
        {
          id: "order-test",
          type: "ordering",
          prompt: "Put the testing steps in order.",
          items: [
            { id: "pick", text: "Pick the constraint to test" },
            { id: "criteria", text: "Write how you'll test it and what counts as a pass" },
            { id: "predict", text: "Predict the result" },
            { id: "run", text: "Run the test (more than once)" },
            { id: "record", text: "Record what actually happened, with numbers" },
            { id: "compare", text: "Compare with the pass criteria and decide: pass or fail" },
          ],
          explanation: "Pass criteria come before the test. Results get written down before you decide what they mean.",
          competencyId: "F6",
          check: "practice",
        },
        {
          id: "match-method",
          type: "matching",
          prompt: "Match each constraint to a test method.",
          pairs: [
            { id: "w", left: "Width ≤ 60 mm", right: "Measure the print with a ruler or calipers" },
            { id: "f", left: "Holds a 14 mm glue stick", right: "Insert the glue stick 5 times; record any sticking" },
            { id: "s", left: "Stays on a 5 cm ledge when bumped", right: "Bump the board 5 times; count falls" },
            { id: "u", left: "Opens with one hand", right: "Watch the user try it without help" },
          ],
          explanation: "Some constraints are measured, some are tried, and some need the real user.",
          competencyId: "F6",
          check: "practice",
        },
        {
          id: "fail-amount",
          type: "measurement",
          prompt: "Constraint: width ≤ 60 mm. Your print measures 61.4 mm. By how many mm does it fail?",
          answer: 1.4,
          tolerance: 0.05,
          unit: "mm",
          explanation: "61.4 − 60 = 1.4 mm. Writing the exact amount tells you what to change next: shrink the width by at least 1.4 mm.",
          competencyId: "F6",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Write your test plan",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Capstone test plan",
          prompt: "Write a test for every constraint in your capstone journal. Use a table: constraint | how I'll test | pass if | my prediction.",
          requirements: ["One row per constraint", "Every pass criterion has a number or a clear yes/no", "At least one test repeats 5 or more times", "At least one test involves your user (if possible)"],
          skills: ["F6"],
        },
        {
          id: "user-test-tip",
          type: "callout",
          tone: "tip",
          title: "Testing with your user",
          body: "Hand them the prototype and say nothing. Watch what they try first. Write down where they get confused — that's data.",
        },
        {
          id: "permission",
          type: "callout",
          tone: "safety",
          body: "Same rules as your interview: teacher permission to visit your client, and no photos of faces. Photograph the prototype, not the person.",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Test prototype 1",
          prompt: "Run your test plan on prototype 1. Record every result, including failures. Decide pass or fail for each constraint using your pass criteria.",
          requirements: [
            "Every planned test was run",
            "Results include numbers or counts (e.g. '3 of 5 tries')",
            "Each constraint is marked pass or fail against the criteria you wrote first",
            "At least one failure or surprise is described — or an explanation of why nothing failed",
          ],
          skills: ["F6", "G4"],
        },
        { id: "journal", type: "journal", projectKey: "capstone", promptIds: ["test", "failed"] },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Upload a photo of the test in progress (prototype only, no faces) or your filled-in results table.",
          accepts: ["physical_test", "screenshot"],
          competencyIds: ["F6", "G4"],
          checklist: ["Pass criteria were written before testing", "Results have numbers", "Pass/fail is marked for each constraint"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Which test result surprised you most? What does it tell you to change?",
          sentenceStarters: ["I predicted…, but…", "This tells me to change…"],
          competencyIds: ["F6"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students learn that a test is planned, repeatable and judged against criteria set in advance — and that a failed test is useful evidence, not a bad grade.",
    preparation: [
      "Make sure each student has prototype 1 (printed slice, paper or cardboard) or a plan to test digitally.",
      "Arrange short, supervised client visits for user tests where possible.",
      "Have rulers or calipers and the real objects students' designs must hold.",
    ],
    equipment: ["Prototypes from the previous lesson", "Ruler or calipers", "Real objects for fit and load tests", "Student devices"],
    misconceptions: [
      { id: "one-try-enough", text: "If it works once, it passes.", response: "Ask how often the user will use it. Test at least five times and look for wear or cracking." },
      { id: "looks-pass", text: "Looking at a prototype is a test.", response: "Ask: what number or count did you record? No result = no test." },
    ],
    discussionQuestions: [
      "Why should pass criteria be written before the test?",
      "Is a failed test a bad thing? What does it give you?",
      "What can a user test reveal that you can't test yourself?",
    ],
    printableObjects: ["Prototype 1 test slices from the previous lesson (reprints only if a print failed)"],
    slicerSettings: "Reprint with the same settings as prototype 1 so results are comparable — starting point: PLA, 0.2 mm layers, 15% infill, 2–3 walls. Adjust for your printer.",
    troubleshooting: [
      "If every test 'passes', check whether pass criteria were set after testing, or whether the test copies real use.",
      "If a prototype breaks during a test, that's a result — have the student photograph where it broke and record it.",
      "If a client isn't available, a classmate can stand in for a usability test; note it in the journal.",
    ],
    answerGuidance: [
      "Strong test row example: 'Holds 14 mm glue stick | insert and remove 5 times | pass if it goes in by hand every time and doesn't fall out when tipped | prediction: tight.'",
      "Proficient: every constraint has a test with criteria; results include numbers; failures are reported honestly.",
    ],
    alternatives: {
      noPrinter: "Test paper/cardboard prototypes for size and reach, and test fit with a cardboard cut-out at the designed hole size. Record which constraints still need a print to test.",
      noCalipers: "Measure prints with a ruler to the nearest 0.5 mm and record that precision in the results.",
    },
  },
};
