import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "text",
  number: 16,
  title: "Text & Shape Settings",
  subtitle: "Words and details that actually print",
  domain: "B",
  kind: "lesson",
  summary: "Add raised and recessed text, change shape settings like sides and segments, and size details so they will print clearly.",
  estimatedMinutes: 50,
  printLevel: "digital",
  competencyIds: ["B10", "B9"],
  prerequisites: ["mirror"],
  vocabulary: [
    { term: "Raised text", definition: "Letters that stick up from a surface (solid text on top)." },
    { term: "Recessed text", definition: "Letters cut into a surface (text set to Hole and sunk in)." },
    { term: "Shape parameters", definition: "Settings in the shape panel that change a shape's form, such as sides, bevel or segments." },
    { term: "Segments", definition: "The number of flat sides used to draw a curve. More segments look smoother." },
    { term: "Stroke", definition: "The thickness of the lines that make up each letter." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "If you can't read it, it didn't print.",
          hook: "Text looks sharp on screen at any size. On a printer, letters thinner than about 1 mm can turn into blobs or vanish.",
          visual: { diagram: "text-raised-recessed" },
        },
        {
          id: "explain",
          type: "text",
          body: "Drag the **Text** shape from Basic Shapes. Type your words in the shape panel and pick a font. Keep it **Solid** for raised text, or switch to **Hole** and sink it into a surface for recessed text.",
        },
        {
          id: "explain-params",
          type: "text",
          title: "Shape settings",
          body: "Most shapes have settings in the shape panel. A Polygon has **sides** (6 makes a hexagon). A Cylinder has **sides** too — more sides look rounder. A Round Roof or Rounded Box may have **bevel** or **segments**. Change a number and watch the shape update.",
        },
        {
          id: "text-diagram",
          type: "diagram",
          name: "text-raised-recessed",
          caption: "Raised text sits on top of the surface. Recessed text is a hole cut into it.",
          alt: "Raised text on one plate, recessed text cut into another plate.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "You print a name tag with text 3 mm tall in a thin, curly font. What do you expect?",
          options: [
            { id: "a", text: "The letters blur together or break up." },
            { id: "b", text: "It prints exactly like the screen.", misconceptionId: "screen-equals-print" },
            { id: "c", text: "The printer makes the letters bigger automatically.", misconceptionId: "printer-fixes" },
          ],
          expectedOptionId: "a",
          reveal: "A typical nozzle draws lines about 0.4 mm wide. Thin strokes in tiny letters are only one or two lines wide. Starting points: letters at least 5–6 mm tall, a bold font, and about 1 mm raised or recessed. Test on your own printer.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Try it",
      blocks: [
        {
          id: "show-me",
          type: "showMe",
          title: "Recessed text on a plate",
          steps: [
            { text: "Make a Box 60 × 20 × 4 mm.", diagram: "exact-dimension" },
            { text: "Drag in a Text shape. In the shape panel, type your initials and choose a bold font." },
            { text: "Resize the text to about 8 mm tall (Y) and 2 mm high (Z). Switch it to Hole.", diagram: "solid-vs-hole" },
            { text: "Raise the text so its bottom is at Z = 3 mm. It now cuts 1 mm into the 4 mm plate.", diagram: "move-z" },
            { text: "Select both, align to the centre, and group (Ctrl+G).", diagram: "align-handles", keys: "Ctrl+G" },
          ],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Raised, recessed and reshaped",
          steps: [
            "Build the recessed plate from the Show Me steps.",
            "Make a second plate with the same text raised 1 mm (Solid, sitting on top at Z = 4 mm).",
            "Drag in a Polygon and change its sides to 3, 6 and 10. Then a Cylinder: change its sides from a low number to a high number.",
            "Compare the two plates. Which would be easier to read after painting? After wearing in a pocket?",
          ],
        },
        {
          id: "depth",
          type: "measurement",
          prompt: "A plate is 5 mm thick and sits on the workplane. You want text recessed 1.5 mm deep. Where should the bottom of the text hole be?",
          answer: 3.5,
          tolerance: 0,
          unit: "mm (Z)",
          hint: "The top of the plate is at Z = 5 mm.",
          explanation: "5 − 1.5 = 3.5 mm. The hole must also reach above Z = 5 mm so it cuts through the top surface.",
          competencyId: "B10",
          check: "skill",
        },
        {
          id: "params-match",
          type: "matching",
          prompt: "Match the goal to the shape setting.",
          pairs: [
            { id: "hex", left: "A hexagon nut shape", right: "Polygon with 6 sides" },
            { id: "smooth", left: "A rounder cylinder", right: "Increase the cylinder's sides" },
            { id: "word", left: "Change the word on a label", right: "Edit the text field" },
            { id: "tri", left: "A triangular prism", right: "Polygon with 3 sides" },
          ],
          explanation: "Parameters change the form without rebuilding the shape. Look in the shape panel first before stacking extra shapes.",
          competencyId: "B9",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Micro challenge",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Locker label",
          prompt: "Make a 70 × 25 × 3 mm label with a word of your choice raised 1 mm, and a hexagon (6-sided polygon) hole at one end for a cord.",
          requirements: ["Letters at least 6 mm tall", "Text raised 1 mm and touching the plate", "Hexagon hole cuts through", "Single grouped model"],
          skills: ["B10", "B9", "B3"],
        },
        {
          id: "floating-mc",
          type: "multipleChoice",
          prompt: "Your raised text looks fine, but in the slicer the letters print in mid-air. What happened?",
          options: [
            { id: "a", text: "The text was floating above the plate instead of touching it." },
            { id: "b", text: "Text can never be raised.", misconceptionId: "text-cant-raise" },
            { id: "c", text: "The font was too bold." },
          ],
          correctOptionIds: ["a"],
          explanation: "Raised text must sit exactly on the top face (or overlap it slightly). Check its Z position equals the plate's height.",
          competencyId: "B10",
          check: "practice",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Plant marker",
          prompt: "Design a garden plant marker: a 15 mm wide stake that comes to a point, with a 40 × 25 mm sign on top. Recess the plant's name 1 mm into the sign. Use a shape parameter (sides, bevel or segments) for at least one feature. Total thickness 3 mm. No steps.",
          requirements: [
            "Plant name recessed exactly 1 mm and does not cut through",
            "Letters at least 6 mm tall in a bold font",
            "At least one shape parameter changed on purpose",
            "Total thickness 3 mm",
            "Single grouped model",
          ],
          skills: ["B10", "B9", "B3", "B2"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a class design link or screenshot. In one sentence, say which shape parameter you changed and why.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["B10", "B9"],
          checklist: ["Text depth is visible or stated", "Letters are readable at full size", "Everything is one group"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Raised or recessed: which did you choose for your marker, and why is it better for an object that lives outside?",
          sentenceStarters: ["I chose…", "Outside, it would…"],
          competencyIds: ["B10"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students make raised and recessed text, change shape parameters, and size details with printing limits in mind.",
    preparation: [
      "If you have them, show one printed sample with tiny text and one with large bold text.",
      "Check which fonts are available in your Tinkercad Text shape; bold, simple fonts work best.",
    ],
    equipment: ["Student devices with Tinkercad", "Optional: printed text samples"],
    misconceptions: [
      { id: "screen-equals-print", text: "If it looks sharp on screen, it will print sharp.", response: "Compare the nozzle line width (about 0.4 mm) with the stroke of a 3 mm letter." },
      { id: "printer-fixes", text: "The printer or slicer will fix small details.", response: "Slicers drop details that are too thin — they never enlarge them." },
      { id: "text-cant-raise", text: "Text can only be cut in, not raised.", response: "Demo a Solid Text shape sitting on a plate; then show a floating one in the slicer." },
    ],
    discussionQuestions: ["Why are recessed letters often tougher than raised ones?", "Which shape parameters did you discover today?"],
    troubleshooting: [
      "Text won't cut in after grouping: the text is still Solid, or it doesn't reach above the plate's top surface.",
      "Text cuts all the way through: the hole starts at Z = 0. Raise it so only the top 1 mm overlaps the plate.",
      "Letters are squashed: Shift wasn't held while resizing, so the text was stretched on one axis.",
    ],
    answerGuidance: [
      "Plate demo: 4 mm plate, text hole 2 mm high with bottom at Z = 3 → 1 mm recess.",
      "Plant marker: stake point can be a rotated box, a Roof or a 3-sided Polygon; any intentional parameter change counts if the student can explain it.",
      "Size guidance (5–6 mm letters, ~1 mm depth) is a starting point; a fine nozzle or careful printer can do smaller.",
    ],
    alternatives: { touchDevice: "Tap the text field in the shape panel to bring up the on-screen keyboard." },
  },
};
