import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "tolerances",
  number: 21,
  title: "Tolerances",
  subtitle: "Why a 10 mm peg won't fit a 10 mm hole",
  domain: "C",
  kind: "lab",
  summary: "Run a Fit Lab to find how much clearance your class printer needs, and learn why that number belongs to your printer — not to everyone.",
  estimatedMinutes: 50,
  printLevel: "required",
  competencyIds: ["C5", "C6"],
  prerequisites: ["calipers"],
  vocabulary: [
    { term: "Clearance", definition: "The planned gap between a part and the hole it goes into." },
    { term: "Tolerance", definition: "How far a real size is allowed to be from the designed size and still work." },
    { term: "Sliding fit", definition: "A fit where the part slides in and out by hand without forcing or wobbling." },
    { term: "Press fit", definition: "A fit so tight the part has to be pushed in and stays put." },
    { term: "Calibration", definition: "Adjusting and testing a machine so its results match the design as closely as possible." },
  ],
  sections: [
    {
      phase: "discover",
      title: "The fit problem",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "10 mm + 10 mm = stuck.",
          hook: "You design a 10 mm peg and a 10 mm hole. On screen they match perfectly. On the printer, the peg often won't go in at all. Today you find out why — and how much gap your printer needs.",
          visual: { diagram: "clearance-fit" },
        },
        {
          id: "explain",
          type: "text",
          body: "A printer squishes melted plastic into lines. Those lines spread a little, so holes print **smaller** and pegs print **bigger** than designed. The extra gap you add to fix this is called **clearance**.",
        },
        { id: "fit-types", type: "diagram", name: "fit-types", caption: "Press fit, sliding fit, loose fit — same peg, different gaps.", alt: "Three fits: tight/press fit, sliding fit and loose fit, shown with different gaps." },
        {
          id: "predict-fit",
          type: "prediction",
          prompt: "Fit Lab: a 10.0 mm peg and four holes — 10.0, 10.1, 10.3 and 11.0 mm. Which hole do you think gives an easy sliding fit on our printer?",
          visual: { diagram: "clearance-fit" },
          options: [
            { id: "h100", text: "10.0 mm — same size as the peg", misconceptionId: "same-size-fits" },
            { id: "h101", text: "10.1 mm — just a hair bigger" },
            { id: "h103", text: "10.3 mm — a small gap" },
            { id: "h110", text: "11.0 mm — a big gap", misconceptionId: "bigger-is-better" },
          ],
          revealTitle: "It depends — that's the point",
          reveal: "There is no single right answer. On many school printers 10.0 mm is too tight and 11.0 mm wobbles, but the best hole depends on the printer, the plastic, the settings and how well the machine is calibrated. The only way to know is to print a test and try it. Keep your prediction — you'll check it in a few minutes.",
        },
        {
          id: "tolerance-range",
          type: "diagram",
          name: "tolerance-range",
          caption: "Tolerance: the range around a target size that still works.",
          alt: "A target size with a range above and below it that still counts as acceptable.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Run the Fit Lab",
      blocks: [
        {
          id: "lab-intro",
          type: "text",
          body: "Your teacher will print one 10 mm peg and three test plates: holes of **10.0**, **10.2** and **10.4 mm**. Same printer, same plastic, same settings for every piece — so the hole size is the only thing that changes.",
        },
        { id: "lab-files", type: "modelDownload", modelIds: ["peg-10mm", "hole-10mm", "hole-10-2mm", "hole-10-4mm"], showImportSteps: false },
        {
          id: "lab-steps",
          type: "showMe",
          title: "Test the fits",
          steps: [
            { text: "Measure the printed peg with calipers (or a ruler). Write down the real diameter — it may not be exactly 10.0 mm.", diagram: "caliper-parts" },
            { text: "Measure each printed hole the same way. Holes often come out a little small." },
            { text: "Try the peg in each hole by hand. Don't force it or hammer it." },
            { text: "Rate each hole: won't go in / press fit / sliding fit / loose. Compare with your prediction.", diagram: "fit-types" },
          ],
        },
        {
          id: "lab-safety",
          type: "callout",
          tone: "warning",
          title: "Don't force it",
          body: "If the peg won't go in, that is a test result, not a challenge. Forcing a peg can crack the plate or pinch fingers.",
        },
        {
          id: "clearance-math",
          type: "measurement",
          prompt: "A 10.0 mm peg goes into a 10.4 mm hole. How much clearance is there on EACH side of the peg?",
          answer: 0.2,
          tolerance: 0,
          unit: "mm",
          hint: "The extra 0.4 mm is shared between the left side and the right side.",
          explanation: "10.4 − 10.0 = 0.4 mm total, split across two sides = 0.2 mm per side. Always check whether a number means total or per side.",
          competencyId: "C5",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Our printer's clearance",
      blocks: [
        {
          id: "record-results",
          type: "uploadEvidence",
          prompt: "Record your Fit Lab results: a photo of the peg in its best hole plus your table of measured sizes and fit ratings. Finish the sentence: \"On our printer, a sliding fit needs about ___ mm of extra hole size.\"",
          accepts: ["physical_test", "screenshot"],
          competencyIds: ["C5", "C6"],
          checklist: ["Measured peg size recorded", "Measured size of each hole recorded", "Fit rating for each hole", "Our printer's clearance written down"],
        },
        {
          id: "extra-tests",
          type: "text",
          title: "Want more data?",
          body: "These optional community test prints check many clearances at once, including a snap-fit box. They are links to the original creators' pages.",
        },
        { id: "ext-files", type: "modelDownload", modelIds: ["ext-tolerance-test-viceroysyrup", "ext-snapfit-box-keosovandara"], showImportSteps: false, required: false },
        {
          id: "mc-friend",
          type: "multipleChoice",
          prompt: "A friend at another school says \"a 0.2 mm gap always fits.\" On your printer, the 10.2 mm hole was too tight. What is the best explanation?",
          options: [
            { id: "a", text: "Different printers, plastics and settings produce slightly different sizes, so each printer needs its own tested clearance." },
            { id: "b", text: "Your friend must have measured wrong.", misconceptionId: "one-true-number" },
            { id: "c", text: "Your printer is broken and must be replaced.", misconceptionId: "variation-means-broken" },
          ],
          correctOptionIds: ["a"],
          explanation: "Tolerance numbers are machine-specific. A clearance that works on one printer is a starting point for another, not a rule. Test, then use your own result.",
          competencyId: "C6",
          check: "skill",
        },
        {
          id: "mc-why",
          type: "multipleChoice",
          prompt: "Why does a printed hole usually come out a little smaller than designed?",
          options: [
            { id: "a", text: "Melted plastic spreads slightly as it is laid down, so it creeps into the hole." },
            { id: "b", text: "Tinkercad shrinks holes on purpose.", misconceptionId: "software-shrinks" },
            { id: "c", text: "The peg grows after printing." },
          ],
          correctOptionIds: ["a"],
          explanation: "Each line of plastic is squished and spreads a little. On the inside of a hole that spreading makes the opening smaller. Low-resolution circles can also make holes smaller.",
          competencyId: "C5",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Build a fit gauge for a pencil",
          prompt: "Design your own fit gauge for a pencil or pen you have in class. Measure it first. Your gauge should test three hole sizes so the class can find the best fit for that object.",
          requirements: [
            "Three holes: measured size + 0.0 mm, + your class clearance, and + double your class clearance",
            "Plate at least 4 mm thick",
            "At least 5 mm of material between holes and around the edge",
            "Each hole labelled (text, dots or notches) so you can tell them apart after printing",
            "Single grouped model",
          ],
          skills: ["C5", "C6", "B3"],
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Design your fit gauge",
          steps: [
            "Measure your pencil or pen and write the diameter down.",
            "Create a new design in Tinkercad.",
            "Tip: for round holes, raise the cylinder's Sides setting in the shape panel so the circle is smooth — rough circles print smaller.",
          ],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit your fit gauge (share link, screenshot showing the hole dimensions, or STL) and state which hole you predict will fit best and why.",
          accepts: ["design_url", "screenshot", "stl"],
          competencyIds: ["C5", "C6"],
          checklist: ["Object's measured size stated", "Three hole sizes visible", "Prediction with a reason"],
          allowPrintRequest: true,
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Why can't you just copy a clearance number from the internet? What would you do if you moved your design to a different printer?",
          sentenceStarters: ["A clearance number only works for…", "On a new printer I would first…"],
          competencyIds: ["C5", "C6"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students discover that designed size ≠ printed size, learn clearance and tolerance, and establish a class clearance value from real test data that they will reuse in Make It Fit.",
    preparation: [
      "Print one peg-10mm and one each of hole-10mm, hole-10-2mm and hole-10-4mm per group (about 4–5 groups). Print them all in one job with the same settings.",
      "Optional: print one set yourself before class to know what result to expect on your machine.",
      "Prepare a class chart: hole size | measured size | fit rating, plus a line for \"Our printer's clearance\".",
    ],
    equipment: ["Printed peg and hole plates (one set per group)", "Digital calipers or rulers", "Pencils or pens for the prove challenge"],
    misconceptions: [
      { id: "same-size-fits", text: "If the hole and peg are the same size, they will fit.", response: "Let them try the 10.0 mm plate. Then ask: where did the plastic go when it was squished?" },
      { id: "bigger-is-better", text: "A much bigger hole is always safest.", response: "Ask what happens to a wheel on a loose axle or a lid that rattles. Too loose is also a failed fit." },
      { id: "one-true-number", text: "There is one correct clearance number for all 3D printers.", response: "Compare class results with a second printer if you have one, or share results from another class. Variation is normal." },
      { id: "variation-means-broken", text: "If a print isn't exactly the designed size, the printer is broken.", response: "All manufacturing has tolerance — even factory parts. A printer is working well when its results are consistent and predictable." },
      { id: "software-shrinks", text: "Tinkercad changes the size of holes.", response: "Measure the hole in Tinkercad with the ruler — it is exact. The change happens during printing." },
    ],
    discussionQuestions: [
      "Which hole surprised you most?",
      "Did every group get the same result with the same printer? Why might they differ?",
      "Where else do things need a gap to fit — doors, drawers, lids?",
    ],
    printableObjects: ["peg-10mm", "hole-10mm", "hole-10-2mm", "hole-10-4mm"],
    slicerSettings: "Starting point: PLA, 0.2 mm layers, 15–20% infill, 2–3 walls, no supports, plates lying flat. Print all pieces in one job so settings match — adjust for your printer.",
    troubleshooting: [
      "If the peg fits none of the holes, check for elephant's foot at the base of the peg or a rough first layer inside the holes; trim with a deburring tool or sand lightly — and record that as part of the result.",
      "If every hole is loose, your printer may be under-extruding; still record it — the class clearance is whatever your printer actually does.",
      "Holes printed upright (on their side) come out less round than holes printed flat. Keep plates flat for this lab.",
    ],
    answerGuidance: [
      "Prediction: there is no expected answer. Praise reasoning (\"plastic spreads, so I need some gap\") over guessing the number.",
      "Clearance math: 0.4 mm total → 0.2 mm per side.",
      "Class clearance result: whatever hole gave a sliding fit, minus the peg size. Many machines land somewhere around 0.2–0.5 mm total, but use your own data.",
      "Fit gauge: three holes stepped by the class clearance; labelled; ≥ 4 mm plate; ≥ 5 mm spacing; grouped.",
    ],
    alternatives: {
      noPrinter: "Use a teacher-provided set printed elsewhere, or demonstrate with a single set passed around. Students still measure and rate fits.",
      noCalipers: "Measure with a ruler to the nearest 0.5 mm and rate fits by feel only. Discuss why calipers would give better data.",
      touchDevice: "Use the on-screen Group button and tap dimension values to type sizes.",
    },
  },
};
