import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "what-is-3d-printing",
  number: 1,
  title: "What Is 3D Printing?",
  subtitle: "Adding material one layer at a time",
  domain: "D",
  kind: "lesson",
  summary: "Compare subtractive and additive manufacturing, see how a filament printer works, and count the layers in a real part.",
  estimatedMinutes: 45,
  printLevel: "digital",
  competencyIds: ["D1"],
  prerequisites: [],
  vocabulary: [
    { term: "Subtractive manufacturing", definition: "Making a part by cutting material away from a bigger block (drilling, milling, carving)." },
    { term: "Additive manufacturing", definition: "Making a part by adding material only where it is needed, usually layer by layer." },
    { term: "FDM", definition: "Fused deposition modeling: a printer melts plastic filament and draws each layer with a hot nozzle." },
    { term: "Layer height", definition: "How thick each printed layer is, for example 0.2 mm." },
    { term: "Slicer", definition: "Software that cuts a 3D model into layers and writes the instructions the printer follows." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Two ways to make a thing",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "Carve it, or build it?",
          hook: "A sculptor starts with a block and removes everything that isn't the statue. A 3D printer starts with nothing and adds only the statue.",
          visual: { diagram: "subtractive-vs-additive", alt: "A block being carved compared with a part built up in layers." },
        },
        {
          id: "explain",
          type: "text",
          body: "**Subtractive** making removes material: a drill, a saw, a milling machine. **Additive** making adds material where it is needed. Most school 3D printers are additive.",
        },
        {
          id: "sort",
          type: "matching",
          prompt: "Match each way of making to an example.",
          hint: "Ask: is material being taken away, or added a bit at a time?",
          pairs: [
            { id: "p1", left: "Subtractive", right: "Drilling a hole through a wooden board" },
            { id: "p2", left: "Additive", right: "Printing a keychain layer by layer" },
            { id: "p3", left: "Subtractive", right: "Carving a pumpkin" },
            { id: "p4", left: "Additive", right: "Building a wall one row of bricks at a time" },
          ],
          explanation: "Ask one question: does the process start bigger and remove material, or start empty and add it?",
          check: "practice",
        },
        {
          id: "printer",
          type: "diagram",
          name: "fdm-printer",
          caption: "Filament is pushed into a hot nozzle (around 200 °C for PLA). The nozzle draws one thin layer, then the plate or nozzle moves up and it draws the next.",
          alt: "A spool feeds filament to a heated nozzle above a build plate.",
        },
        {
          id: "how-it-works",
          type: "showMe",
          title: "From idea to object",
          steps: [
            { text: "Design the object in CAD software, such as Tinkercad.", diagram: "group-hole" },
            { text: "Export the design as an STL file: a description of its outside surface." },
            { text: "A slicer cuts the model into hundreds of thin layers and plans the nozzle's path for each one.", diagram: "layers-stack" },
            { text: "The printer melts filament and draws layer 1 on the build plate, then layer 2 on top of it, and so on.", diagram: "fdm-printer" },
          ],
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "The nozzle reaches a part of the model that hangs in mid-air with nothing under it. What do you think happens?",
          options: [
            { id: "a", text: "The plastic droops or falls, because there is nothing underneath to build on" },
            { id: "b", text: "The plastic hardens instantly and floats in place", misconceptionId: "floats" },
            { id: "c", text: "The printer skips that part automatically", misconceptionId: "printer-knows" },
          ],
          expectedOptionId: "a",
          reveal: "Each layer needs something below it. Melted plastic laid on air sags. Later you'll learn three fixes: change the shape, change the orientation, or add supports.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Look at the layers",
      blocks: [
        {
          id: "viewer",
          type: "modelViewer",
          modelId: "axis-cube-20mm",
          caption: "A 20 mm cube. Drag the layer slider to watch it build from the plate up. The notches mark X (1), Y (2) and the top, Z (3).",
          showLayers: true,
        },
        {
          id: "count-layers",
          type: "measurement",
          prompt: "This cube is 20 mm tall. The printer uses 0.2 mm layers. How many layers does it print?",
          answer: 100,
          tolerance: 0,
          unit: "layers",
          hint: "Five 0.2 mm layers stack up to 1 mm (0.2 + 0.2 + 0.2 + 0.2 + 0.2). So how many layers make 20 mm? You can use the calculator.",
          explanation: "20 ÷ 0.2 = 100 layers. Thinner layers look smoother but take longer.",
          competencyId: "D1",
          check: "practice",
        },
        {
          id: "slide-layers",
          type: "slider",
          prompt: "This dome is 20 mm tall. Pick the layer height that builds it in exactly **100 layers**.",
          scene: "layers",
          min: 0.1,
          max: 0.4,
          step: 0.05,
          start: 0.4,
          unit: "mm",
          answer: 0.2,
          tolerance: 0.001,
          hint: "Layers × layer height = total height. What times 100 makes 20?",
          explanation: "20 ÷ 100 = **0.2 mm** — the most common layer height on school printers. Thinner layers = more layers = longer print.",
          competencyId: "D1",
        },
        {
          id: "order",
          type: "ordering",
          prompt: "Put the steps in the order they happen.",
          hint: "You can't slice something that hasn't been designed yet. Start with the computer, end at the printer.",
          items: [
            { id: "cad", text: "Design the model in CAD" },
            { id: "stl", text: "Export an STL file" },
            { id: "slice", text: "Slice the model into layers" },
            { id: "first", text: "Print the first layer on the build plate" },
            { id: "stack", text: "Print each next layer on top of the last" },
          ],
          explanation: "Design → export → slice → print. The slicer is the bridge between your design and the machine.",
          competencyId: "D1",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Think like a printer",
      blocks: [
        {
          id: "micro",
          type: "challenge",
          where: "offline",
          kind: "micro",
          title: "Faster or smoother?",
          prompt: "The same 30 mm tall part can print with 0.1 mm or 0.3 mm layers. Work out the number of layers for each, then decide which you'd choose for a quick test part.",
          requirements: ["Layer count for 0.1 mm", "Layer count for 0.3 mm", "One sentence explaining your choice"],
          skills: ["D1"],
        },
        {
          id: "layer-check",
          type: "multipleChoice",
          prompt: "Two copies of a part are printed: one at 0.1 mm layers and one at 0.3 mm. What is the main difference?",
          hint: "Think about a 30 mm tall part. How many 0.1 mm layers stack up to 30 mm? How many 0.3 mm layers?",
          options: [
            { id: "a", text: "The 0.1 mm copy has 3× as many layers: smoother sides, but much longer to print." },
            { id: "b", text: "The 0.1 mm copy comes out smaller.", misconceptionId: "layer-size" },
            { id: "c", text: "The 0.3 mm copy uses three times more plastic.", misconceptionId: "layer-material" },
          ],
          correctOptionIds: ["a"],
          explanation: "Layer height changes how many layers there are, not the part's size. More, thinner layers = smoother surface and longer print time.",
          competencyId: "D1",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          where: "offline",
          kind: "prove",
          title: "Layer plan for a mystery object",
          prompt: "Pick an object in this room that is not a cube: a cup, a phone stand, a game piece. Sketch how a printer would build it from the bottom up.",
          requirements: [
            "Side-view sketch with at least 5 layer lines drawn",
            "Estimated height in mm and number of layers at 0.2 mm",
            "Circle any part that would hang in mid-air",
            "Say whether the real object was made by adding or removing material, and why you think so",
          ],
          skills: ["D1"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Show your layer plan: upload a photo or screenshot, or write or say it.",
          accepts: ["screenshot", "written"],
          competencyIds: ["D1"],
          checklist: ["Layer lines are horizontal and start at the bottom", "Height and layer count are labelled", "Mid-air parts are circled"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "What is one object that would be easier to make by adding material, and one that would be easier by removing it?",
          sentenceStarters: ["Adding material works better for… because…", "Removing material works better for… because…"],
          competencyIds: ["D1"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students build a mental model of FDM printing as stacked layers, which every later design-for-printing decision depends on.",
    preparation: [
      "If you have a printer, start a short print (the 20 mm axis cube takes about 20–40 minutes) before class so students can watch layers form.",
      "Collect 3–4 everyday objects: one machined or drilled (wooden block, metal bracket), one molded (bottle cap), one 3D printed if available.",
    ],
    equipment: ["Student devices", "Paper and pencil for the layer plan", "Optional: a running 3D printer or any printed part with visible layer lines"],
    misconceptions: [
      { id: "floats", text: "Melted plastic can be placed in mid-air and stay there.", response: "Ask: what holds up the first bit of plastic in that spot? Show a droopy overhang if you have one." },
      { id: "printer-knows", text: "The printer understands the design and fixes problems on its own.", response: "Explain that the printer only follows the slicer's path, line by line. The designer and slicer settings make the decisions." },
      { id: "layer-size", text: "Thinner layers make a smaller part.", response: "The outside size comes from the design. Layer height only changes how the height is divided up." },
      { id: "layer-material", text: "Thicker layers use more plastic overall.", response: "The same part uses roughly the same plastic; it is just split into fewer, thicker slices." },
    ],
    discussionQuestions: [
      "Which objects in this room were made by removing material? Which by adding? Which were molded?",
      "Why might a factory still use molding for a million identical bottle caps instead of printing them?",
      "Where do you think a printed part is weakest?",
    ],
    troubleshooting: [
      "If the layer slider is hard to see on a small screen, rotate the viewer so the cube is side-on.",
      "If students think the cube prints as one solid lump, pass around any printed part and have them run a fingernail up the side.",
    ],
    answerGuidance: [
      "Micro challenge: 30 mm at 0.1 mm = 300 layers; at 0.3 mm = 100 layers. A quick test part is usually printed with thicker layers.",
      "Layer plan: look for horizontal layers starting at the plate, a sensible height estimate (height ÷ 0.2), and at least one overhang identified if the object has one.",
      "Molded objects (bottle caps, toys) are a reasonable third category; accept a student who argues that molding is neither adding nor removing.",
    ],
    alternatives: {
      noPrinter: "Use the layer slider in the model viewer and any printed object you can borrow. No printing is needed for this lesson.",
      touchDevice: "The model viewer works with one-finger drag to orbit and pinch to zoom.",
    },
  },
};
