import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "workspace-rescue",
  number: 9,
  title: "Workspace Rescue",
  subtitle: "BOSS: no tutorial, just a mess to fix",
  domain: "A",
  kind: "boss",
  summary: "Someone left a workspace in chaos. Use every Foundations skill — view, select, move, scale, size, rotate and workplanes — to rebuild it clean, with no step-by-step help.",
  estimatedMinutes: 90,
  printLevel: "digital",
  competencyIds: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11"],
  prerequisites: ["workplanes"],
  vocabulary: [
    { term: "Reference model", definition: "A file you look at and measure, but rebuild instead of editing." },
    { term: "Organized workspace", definition: "Every part rests where it should, at the right size, with nothing floating, sunk or overlapping by accident." },
    { term: "Verify", definition: "Check a result with numbers or a second view, not just by eye." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Mission briefing",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "This workspace is a disaster.",
          hook: "Shapes are floating, sinking and scattered. Two tools are turned at random angles next to their toolbox. There is no tutorial. You know enough to fix it.",
          visual: { modelId: "misplaced-shapes", alt: "Five scattered shapes, one floating and one sunk." },
        },
        {
          id: "rules",
          type: "text",
          title: "Boss rules",
          body: "- No Show Me steps in this lesson. Use what you already know.\n- Getting stuck is part of it. Try something, check it from another view, and adjust.\n- Imported files arrive as one locked shape, so treat them as **references**: look, measure, then rebuild clean with Tinkercad shapes.",
        },
        {
          id: "callout",
          type: "callout",
          tone: "tip",
          title: "Stuck?",
          body: "Ask yourself: Which view would show me the problem? Which skill fixes it — move, size, rotate or workplane?",
        },
      ],
    },
    {
      phase: "practice",
      title: "Recon",
      blocks: [
        {
          id: "recon-shapes",
          type: "hotspot",
          prompt: "Scene 1: click every shape that is NOT resting on the workplane.",
          modelId: "misplaced-shapes",
          hotspots: [
            { id: "cube", label: "Cube", position: [65, 45, 28], radius: 14, correct: true, feedback: "Floating: its bottom is 18 mm above the workplane." },
            { id: "sphere", label: "Sphere", position: [0, 0, 0], radius: 11, correct: true, feedback: "Sunk: its bottom is 13 mm below the workplane." },
            { id: "cylinder", label: "Cylinder", position: [-60, -40, 12], radius: 13, correct: false, feedback: "Far from the centre, but resting on the workplane." },
            { id: "cone", label: "Cone", position: [-25, 70, 10], radius: 11, correct: false, feedback: "Resting on the workplane." },
            { id: "bar", label: "Bar", position: [35, -65, 3], radius: 10, correct: false, feedback: "Low and flat, and resting on the workplane." },
          ],
          explanation: "Two shapes are off the floor: the cube floats and the sphere is sunk. The others are just scattered.",
          competencyId: "A7",
          check: "practice",
        },
        {
          id: "recon-toolbox",
          type: "hotspot",
          prompt: "Scene 2: click every part that must be rotated before it can lie inside the tray.",
          modelId: "toolbox-parts",
          hotspots: [
            { id: "rod", label: "Rod", position: [45, 90, 35], radius: 15, correct: true, feedback: "Tilted on two axes. It's 70 mm long, so it only fits lying flat along the tray's length." },
            { id: "block", label: "Block", position: [130, 25, 15], radius: 12, correct: true, feedback: "Turned at an odd angle. It needs a spin around Z so its 30 mm length runs across the tray." },
            { id: "tray", label: "Tray", position: [45, 22.5, 2], radius: 15, correct: false, feedback: "The tray is already flat on the workplane. It's the destination." },
          ],
          explanation: "The rod is tilted on two axes; the block is turned around Z. Decide which axis to fix first.",
          competencyId: "A10",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "Plan before you build",
      blocks: [
        {
          id: "space-check",
          type: "measurement",
          prompt: "The tray is 90 mm long on the outside with 2 mm walls. The rod is 70 mm long. How much spare room is left along the inside length?",
          answer: 16,
          tolerance: 0,
          unit: "mm",
          hint: "Inside length = outside length minus both walls.",
          explanation: "90 − 2 − 2 = 86 mm inside. 86 − 70 = 16 mm of spare room.",
          competencyId: "A9",
          check: "practice",
        },
        {
          id: "rim-check",
          type: "multipleChoice",
          prompt: "The block is 30 × 10 × 10 mm. The tray is 25 mm deep. Which way can the block go so it doesn't stick up above the rim?",
          options: [
            { id: "a", text: "Lying on a long side, so it is 10 mm tall" },
            { id: "b", text: "Standing on end, so it is 30 mm tall", misconceptionId: "size-not-orientation" },
            { id: "c", text: "It can't fit any way; it needs to be scaled down", misconceptionId: "scale-to-fit" },
          ],
          correctOptionIds: ["a"],
          explanation: "Lying down it's 10 mm tall, under the 25 mm rim. Rotating solves this — no need to change the part's size.",
          competencyId: "A10",
          check: "skill",
        },
        {
          id: "tinkercad",
          type: "tinkercadLaunch",
          title: "Open the scene",
          steps: [
            "Open Tinkercad and create a new design in your class.",
            "Import both reference files below.",
            "Read the boss requirements. Plan your order of attack before you click anything.",
          ],
        },
        { id: "files", type: "modelDownload", modelIds: ["misplaced-shapes", "toolbox-parts"], showImportSteps: true },
      ],
    },
    {
      phase: "prove",
      title: "The boss",
      blocks: [
        {
          id: "boss",
          type: "challenge",
          kind: "boss",
          title: "Workspace Rescue",
          prompt: "Rebuild the workspace so it's clean, exact and organized. Use the imported files only as references. No tutorial — every move is your decision.",
          requirements: [
            "Rebuild all five scattered shapes at their real sizes: cube 20 mm; cylinder 20 mm across × 25 mm tall; sphere 18 mm; cone 18 mm across × 22 mm tall; bar 30 × 10 × 6 mm",
            "All five rest on the workplane, in one straight row along X, not touching each other",
            "Build a rod 70 × 8 × 6 mm and a block 30 × 10 × 10 mm and lay both flat inside the tray: on its floor (2 mm up), not poking through a wall or above the 25 mm rim",
            "The rod's 70 mm length runs along the tray's length; the block's 30 mm length runs across the tray (along Y)",
            "A name tag 30 × 10 × 2 mm sits flat against the outside of the tray's front wall",
            "Use the imported tray, or build your own 90 × 45 × 25 mm tray with 2 mm walls and floor from boxes",
          ],
          skills: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11"],
        },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Submit a class share link, plus screenshots: one side view of the row of shapes, one top view of the packed tray, and one view of the name tag.",
          accepts: ["design_url", "screenshot"],
          competencyIds: ["A6", "A7", "A8", "A9", "A10", "A11"],
          checklist: [
            "Side view shows nothing floating or sunk",
            "Each rebuilt part's dimensions match the list",
            "Rod and block are inside the tray and below the rim",
            "Name tag is flat on the outside of the wall",
          ],
        },
        {
          id: "teacher-check",
          type: "teacherCheck",
          prompt: "Ask the student to give you a 60-second tour of their workspace while you watch them drive.",
          lookFors: [
            "Orbits, pans and zooms smoothly to show each requirement",
            "Uses Fit view or Home to recover the view",
            "Selects exactly the shape they want to show",
            "Can explain how they checked heights (side view, D, or the height number)",
            "Explains which rotations they used for the rod and block",
          ],
          competencyIds: ["A1", "A2", "A3", "A4", "A5"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Debrief",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "What was the hardest part of the rescue? What did you try first, and what made it finally work?",
          sentenceStarters: ["The hardest part was…", "My first try was… but…", "It worked when I…"],
          minWords: 20,
          competencyIds: ["A1", "A10", "A11"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "A no-tutorial checkpoint that shows whether students can choose and combine every Foundations skill (A1–A11) on their own.",
    preparation: [
      "Download misplaced-shapes.stl and toolbox-parts.stl and test importing both on a student device.",
      "Each STL imports as one locked shape. Students rebuild the parts with Tinkercad shapes; the imports are references. The imported toolbox includes the tilted originals — that's fine, they're the 'before' picture.",
      "Plan for two class periods. Period 1: recon, planning, rebuilding the five shapes. Period 2: packing the tray, name tag, evidence and tours.",
      "Decide how you'll run the 60-second tours (during work time, or a short line at the end of period 2).",
    ],
    equipment: ["Student devices with Tinkercad", "Mouse recommended", "Optional: scrap paper for planning"],
    misconceptions: [
      { id: "size-not-orientation", text: "A part's height is fixed, so if it's too tall it won't fit.", response: "Hold a pencil case upright, then lay it down. Same object, different height." },
      { id: "scale-to-fit", text: "If a part doesn't fit, shrink it.", response: "Ask: would a real tool still work at 80% size? Fix the position or angle, not the part." },
    ],
    discussionQuestions: [
      "Which skill did you use the most? Which did you forget you had?",
      "What did you check from a second view that you'd have missed from the first?",
      "If someone else opened your design, how would they know it's organized?",
    ],
    troubleshooting: [
      "If a rebuilt shape won't sit inside the imported tray, check it isn't sitting on the tray's floor at Z = 0 instead of Z = 2.",
      "If the name tag ends up tilted or inside the wall, the workplane was placed on the wrong face; place it again on the outer wall.",
      "If a student is stuck for more than five minutes, ask the Stuck? questions rather than showing steps.",
      "If imports appear the wrong size, re-import in millimetres.",
    ],
    answerGuidance: [
      "Rod: rotate 90° on X or Y to lie flat, then on Z if needed so 70 mm runs along X; drop into the tray and raise to Z = 2.",
      "Block: lie it on a long side (10 mm tall) and spin it so 30 mm runs along Y; the tray is 41 mm wide inside, so it fits with room to spare.",
      "Name tag: workplane on the tray's front outer wall, then a 30 × 10 × 2 box placed on it. Rotating a box and nudging it against the wall is also acceptable if it is flat and touching.",
      "Proficient: all requirements met and verified. Developing: most met, one or two parts float, overlap or are a few mm off. Independent: everything met with no help, and the student explains their checks clearly.",
      "Rows: any spacing is fine if shapes don't touch and they line up on Y.",
    ],
    alternatives: {
      touchDevice: "Students can type values for every move and size. Allow extra time; the tour can be done by pointing to the screen.",
    },
  },
};
