import type { LessonInput } from "../schema";

export const lesson: LessonInput = {
  id: "writing-constraints",
  number: 34,
  title: "Writing Constraints",
  subtitle: "Turn an interview into numbers you can design to",
  domain: "F",
  kind: "lesson",
  summary: "Separate constraints from wishes, rewrite vague requests as measurable requirements, and use them to generate and choose between three approaches.",
  estimatedMinutes: 50,
  printLevel: "digital",
  competencyIds: ["F2", "G2", "F3", "F4", "G3"],
  prerequisites: ["interviewing-a-user"],
  vocabulary: [
    { term: "Constraint", definition: "A must-have requirement. A solution that misses it fails." },
    { term: "Wish", definition: "A nice-to-have. Good if you can, fine if you can't." },
    { term: "Measurable", definition: "You can check it with a number or a clear pass/fail test." },
    { term: "Problem statement", definition: "One sentence: who has the problem, what goes wrong, and when." },
  ],
  sections: [
    {
      phase: "discover",
      title: "Why this matters",
      blocks: [
        {
          id: "hook",
          type: "hero",
          title: "'Make it small' is not a size.",
          hook: "Small to an elephant? Small to an ant? Your client gave you words. A designer turns words into numbers.",
          visual: { diagram: "constraint-vs-wish" },
        },
        {
          id: "explain",
          type: "text",
          body: "A **constraint** is a must, and you can check it: 'fits in a 60 mm wide drawer'. A **wish** is a nice-to-have: 'looks friendly'. Write constraints first. Keep wishes in a separate list.",
        },
        {
          id: "diagram",
          type: "diagram",
          name: "constraint-vs-wish",
          caption: "Constraints are musts you can measure. Wishes are nice-to-haves.",
          alt: "Two columns: constraints with numbers on the left, wishes on the right.",
        },
        {
          id: "predict",
          type: "prediction",
          prompt: "Your client said 'it should be sturdy'. Is that a constraint you can test yet?",
          options: [
            { id: "a", text: "Not yet — it needs a number, like 'holds 500 g without bending'." },
            { id: "b", text: "Yes — everyone knows what sturdy means.", misconceptionId: "words-are-measurable" },
          ],
          expectedOptionId: "a",
          reveal: "Sturdy for a pencil is not sturdy for a laptop. Ask your client what it needs to hold, then write that number down.",
        },
      ],
    },
    {
      phase: "practice",
      title: "Sort and sharpen",
      blocks: [
        {
          id: "sort-mc",
          type: "multipleChoice",
          prompt: "A coach needs a holder for a clipboard on the gym wall. Which of these are measurable constraints? Choose all that apply.",
          options: [
            { id: "a", text: "Holds a clipboard 230 mm wide and 12 mm thick" },
            { id: "b", text: "Mounts with the two screws already in the wall, 150 mm apart" },
            { id: "c", text: "Looks cool", misconceptionId: "wish-as-constraint" },
            { id: "d", text: "Sticks out no more than 40 mm from the wall" },
            { id: "e", text: "In the school colours, if possible" },
          ],
          correctOptionIds: ["a", "b", "d"],
          explanation: "Constraints have numbers or a clear pass/fail. 'Looks cool' and colours are wishes — keep them, but they don't decide pass or fail.",
          competencyId: "F2",
          check: "skill",
        },
        {
          id: "sort-match",
          type: "matching",
          prompt: "Sort the librarian's requests. Match each one to its label.",
          pairs: [
            { id: "s1", left: "Holds books up to 40 mm thick", right: "Constraint — fit" },
            { id: "s2", left: "Fits on a cart shelf 300 mm deep", right: "Constraint — size" },
            { id: "s3", left: "Doesn't slide when the cart rolls over a 15 mm bump", right: "Constraint — stability" },
            { id: "s4", left: "Has a fun shape kids will notice", right: "Wish — looks" },
            { id: "s5", left: "Same blue as the library sign", right: "Wish — colour" },
          ],
          explanation: "The first three have numbers and a pass/fail test, so they are constraints. Shape and colour are wishes: nice to have, but they don't decide if the design works.",
          competencyId: "F2",
          check: "practice",
        },
        {
          id: "match-rewrite",
          type: "matching",
          prompt: "Match each vague wish to a measurable constraint.",
          pairs: [
            { id: "small", left: "Should be small", right: "Fits inside a 60 × 40 mm drawer slot" },
            { id: "hold", left: "Holds a lot of pencils", right: "Holds at least 12 pencils, 8 mm across" },
            { id: "stay", left: "Shouldn't fall off", right: "Stays on a 5 cm ledge when bumped" },
            { id: "quick", left: "Easy to use", right: "Opens with one hand in under 3 seconds" },
          ],
          explanation: "Each rewrite gives you a number to design to and a way to test it later.",
          competencyId: "F2",
          check: "practice",
        },
        {
          id: "clearance-math",
          type: "measurement",
          prompt: "The drawer slot is 62 mm wide. You want 1 mm of space on each side. What is the maximum width of your design?",
          answer: 60,
          tolerance: 0,
          unit: "mm",
          hint: "Subtract space for the left side AND the right side.",
          explanation: "62 − 1 − 1 = 60 mm. Write it as 'width ≤ 60 mm' in your constraints.",
          competencyId: "F2",
          check: "practice",
        },
      ],
    },
    {
      phase: "apply",
      title: "From constraints to ideas",
      blocks: [
        {
          id: "sketch-diagram",
          type: "diagram",
          name: "sketch-concepts",
          caption: "Three approaches that solve the same problem in different ways.",
          alt: "Three different rough sketches for one problem.",
        },
        {
          id: "micro",
          type: "challenge",
          kind: "micro",
          title: "Three approaches for the coach",
          prompt: "Using the coach's three constraints, sketch three approaches that work in different ways: one that clips, one that hangs, one that slides in.",
          requirements: ["Each sketch shows the 230 mm and 40 mm limits", "Three different ways of holding", "One sentence per sketch: which constraint might be hardest?"],
          skills: ["G3", "F3"],
        },
        {
          id: "choose-mc",
          type: "multipleChoice",
          prompt: "Idea 1 sticks out 55 mm. Idea 2 sticks out 35 mm but needs new screw holes. Idea 3 sticks out 30 mm and uses the existing screws. Which should you build first?",
          options: [
            { id: "a", text: "Idea 3 — it meets every constraint." },
            { id: "b", text: "Idea 1 — it holds the clipboard most securely.", misconceptionId: "ignore-constraint" },
            { id: "c", text: "Idea 2 — it's the most interesting." },
          ],
          correctOptionIds: ["a"],
          explanation: "Idea 1 breaks the 40 mm limit and Idea 2 breaks the mounting constraint. A great idea that fails a constraint is still a fail.",
          competencyId: "F4",
          check: "skill",
        },
      ],
    },
    {
      phase: "prove",
      title: "Prove it",
      blocks: [
        {
          id: "prove",
          type: "challenge",
          kind: "prove",
          title: "Your capstone constraints",
          prompt: "Use your interview notes to write your capstone problem, constraints and wishes. Then sketch three different approaches and choose one using your constraints.",
          requirements: [
            "One-sentence problem statement (who, what goes wrong, when)",
            "At least four constraints, at least three with numbers and units",
            "At least one wish, labelled as a wish",
            "Three approaches that work in different ways",
            "Choice explained by naming the constraints it meets",
          ],
          skills: ["F2", "G2", "F3", "F4", "G3"],
        },
        { id: "journal", type: "journal", projectKey: "capstone", promptIds: ["problem", "constraints", "ideas", "first-idea", "why"] },
        {
          id: "submit",
          type: "uploadEvidence",
          prompt: "Upload a photo of your three sketches with your constraints list beside them.",
          accepts: ["screenshot"],
          competencyIds: ["F2", "G3", "F4"],
          checklist: ["Constraints have numbers and units", "Wishes are labelled separately", "Three different approaches", "Choice names constraints"],
        },
      ],
    },
    {
      phase: "reflect",
      title: "Reflect",
      blocks: [
        {
          id: "reflect",
          type: "reflection",
          prompt: "Which of your constraints will be the hardest to meet, and how will you know if you met it?",
          sentenceStarters: ["The hardest constraint is…", "I'll test it by…"],
          competencyIds: ["F2", "G2"],
        },
      ],
    },
  ],
  teacher: {
    purpose: "Students convert interview notes into a clear problem and measurable constraints, then use those constraints — not preference — to choose among multiple approaches.",
    preparation: [
      "Make sure students have their interview notes and measurements from the previous lesson.",
      "Prepare one example of your own: a vague request and its measurable rewrite.",
    ],
    equipment: ["Student devices", "Paper and pencils", "Ruler or tape measure for re-checking measurements"],
    misconceptions: [
      { id: "words-are-measurable", text: "Words like sturdy, small or easy are clear enough to design to.", response: "Ask three students to show 'small' with their hands. Different answers = not measurable." },
      { id: "wish-as-constraint", text: "Every request from the client is a must-have.", response: "Ask: if it missed this, would the client refuse to use it? If not, it's a wish." },
      { id: "ignore-constraint", text: "A strong idea can break one constraint.", response: "Remind students the client set the constraint. Breaking it means the product doesn't work for them." },
    ],
    discussionQuestions: [
      "How do constraints make design easier, not harder?",
      "What would you do if two constraints fight each other?",
      "When should you go back and ask your client a question?",
    ],
    troubleshooting: [
      "If a student has no numbers, send them back to the client (or the space) to measure — with permission.",
      "If three approaches are near-identical, ask for a different way of attaching, holding or stopping.",
    ],
    answerGuidance: [
      "Strong constraint set example: 'Holds 3 dry-erase markers 18 mm across; sits on a 50 mm ledge; sticks out no more than 30 mm; removable without tools.' Wish: 'matches the room colours'.",
      "Proficient: four or more constraints, three or more measurable with units; choice references constraints by name.",
    ],
    alternatives: {
      touchDevice: "Students can type constraints directly into the journal and photograph sketches.",
    },
  },
};
