/** Regenerates src/content/lessons/index.ts from the lesson files present.  npm run content:index */
import fs from "node:fs";
import path from "node:path";

const dir = path.join(process.cwd(), "src/content/lessons");
const files = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .sort();
const ident = (f: string) => "l_" + f.replace(/\.ts$/, "").replace(/[^a-z0-9]/gi, "_");
const out = `// GENERATED by scripts/build-lesson-index.ts — do not edit by hand.
import type { LessonInput } from "../schema";
${files.map((f) => `import { lesson as ${ident(f)} } from "./${f.replace(/\.ts$/, "")}";`).join("\n")}

/** Every lesson in the canonical curriculum. \`number\` sets display order. */
export const lessonInputs: LessonInput[] = [
${files.map((f) => `  ${ident(f)},`).join("\n")}
];
`;
fs.writeFileSync(path.join(dir, "index.ts"), out);
console.log(`Indexed ${files.length} lesson files.`);
