/**
 * Builds the GitHub Pages edition's generated inputs:
 *   apps-script/dist/   Code.js (small website loader) + appsscript.json — the only two files installed in a Sheet
 *   web/public/apps-script/bundle.js   engine + scoring + sidebar + fallback content loaded by Code.js
 *   web/src/generated/lessons.json   lessons with answer keys and teacher guides REMOVED (safe to publish)
 * npm run pages:prepare
 */
import fs from "node:fs";
import crypto from "node:crypto";
import { execSync } from "node:child_process";
import path from "node:path";
import { build } from "esbuild";
import { allBlocks, competencies, isRequiredBlock, journalPrompts, lessons, lessonsInPath } from "../src/content";
import { isScorable, redactBlock } from "../src/lib/scoring";
import { applyOverlay, type Overlay } from "../src/lib/i18n-content";
import { encodePack, packable } from "../src/lib/answer-pack";
import { encodeFeed, validateServerContent } from "../src/lib/content-feed";
import type { LessonBlock } from "../src/content/schema";

/** Redact for the public site, adding a scrambled copy of practice blocks for instant feedback. */
const publish = (b: LessonBlock) => (packable(b) ? { ...redactBlock(b), k: encodePack(b) } : redactBlock(b));

const root = process.cwd();
const dist = path.join(root, "apps-script/dist");
fs.rmSync(dist, { recursive: true, force: true });
fs.mkdirSync(dist, { recursive: true });

// Spanish overlays (src/content/i18n/es/lessons/<id>.json). Missing files/keys fall back to English.
const esDir = path.join(root, "src/content/i18n/es/lessons");
const esLessons: Record<string, Overlay> = {};
for (const l of lessons) {
  const f = path.join(esDir, `${l.id}.json`);
  if (fs.existsSync(f)) esLessons[l.id] = JSON.parse(fs.readFileSync(f, "utf8"));
}

// 1) Server-side content: only what the API needs to score and validate.
const serverLessons: Record<string, unknown> = {};
const serverEs: Record<string, Overlay> = {};
for (const l of lessons) {
  const blocks: Record<string, unknown> = {};
  for (const b of allBlocks(l)) if (isScorable(b) || b.type === "reflection" || b.type === "uploadEvidence") blocks[b.id] = b;
  serverLessons[l.id] = { title: l.title, prerequisites: l.prerequisites, required: allBlocks(l).filter(isRequiredBlock).map((b) => b.id), blocks };
  // only the Spanish text for blocks the server scores (feedback, explanations — kept off the public site)
  const ov = esLessons[l.id];
  if (ov) {
    const keep = Object.keys(blocks).filter((id) => isScorable(blocks[id] as never)).map((id) => `blocks:${id}.`);
    const sub = Object.fromEntries(Object.entries(ov).filter(([k]) => keep.some((m) => k.includes(m))));
    if (Object.keys(sub).length) serverEs[l.id] = sub;
  }
}
const content = {
  lessons: serverLessons,
  autoAssessable: Object.fromEntries(competencies.filter((c) => c.autoAssessable).map((c) => [c.id, true])),
  competencyIds: Object.fromEntries(competencies.map((c) => [c.id, true])),
  journalPrompts: journalPrompts.map((p) => p.id),
  paths: { "9-week": lessonsInPath("9-week").map((x) => x.lesson.id), "18-week": lessonsInPath("18-week").map((x) => x.lesson.id) },
  es: serverEs,
};
{
  const bad = validateServerContent(content);
  if (bad) throw new Error("Server content failed validation: " + bad);
}
const contentVersion = crypto.createHash("sha256").update(JSON.stringify(content)).digest("hex").slice(0, 10);
const feed = encodeFeed(content, contentVersion);
// Content.js is only the engine's built-in fallback (the same scrambled feed — no readable answer keys).
fs.writeFileSync(path.join(dist, "Content.js"), `// GENERATED by scripts/build-pages.ts — do not edit. Lessons for when the website can't be reached.\nvar CONTENT_FEED = ${JSON.stringify(feed)};\n`);

// 2) Shared scoring + mastery rules as a global `Lib`.
async function main() {
await build({
  entryPoints: [path.join(root, "apps-script/lib-entry.ts")],
  bundle: true,
  format: "iife",
  globalName: "Lib",
  target: "es2019",
  outfile: path.join(dist, "Lib.js"),
  alias: { "@": path.join(root, "src") },
  banner: { js: "// GENERATED by scripts/build-pages.ts from src/lib — do not edit." },
  logLevel: "warning",
});
// esbuild emits `var Lib = ...` which Apps Script shares across files.
fs.copyFileSync(path.join(root, "apps-script/src/Sidebar.html"), path.join(dist, "Sidebar.html"));
fs.writeFileSync(
  path.join(dist, "appsscript.json"),
  JSON.stringify(
    {
      timeZone: "America/Detroit",
      runtimeVersion: "V8",
      exceptionLogging: "STACKDRIVER",
      dependencies: {
        enabledAdvancedServices: [
          { userSymbol: "Classroom", serviceId: "classroom", version: "v1" },
          { userSymbol: "Drive", serviceId: "drive", version: "v3" },
        ],
      },
      oauthScopes: [
        "https://www.googleapis.com/auth/spreadsheets.currentonly",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/script.external_request",
        "https://www.googleapis.com/auth/classroom.courses.readonly",
        "https://www.googleapis.com/auth/classroom.rosters.readonly",
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/script.container.ui",
      ],
      webapp: { executeAs: "USER_DEPLOYING", access: "ANYONE_ANONYMOUS" },
    },
    null,
    2,
  ) + "\n",
);

// 3) Public lesson data for the static site: redacted, no teacher guide.
const publicLessons = lessons.map((l) => {
  const { teacher, ...rest } = l;
  void teacher;
  return { ...rest, sections: l.sections.map((s) => ({ ...s, blocks: s.blocks.map(publish) })) };
});
const gen = path.join(root, "web/src/generated");
fs.mkdirSync(gen, { recursive: true });
fs.writeFileSync(path.join(gen, "lessons.json"), JSON.stringify(publicLessons));
// Spanish lessons: translate first, then redact (so answer keys and their translations never reach the site)
const publicEs = lessons.map((l) => {
  const { teacher, ...rest } = applyOverlay(l, esLessons[l.id]);
  void teacher;
  return { ...rest, sections: rest.sections.map((s) => ({ ...s, blocks: s.blocks.map(publish) })) };
});
fs.writeFileSync(path.join(gen, "lessons.es.json"), JSON.stringify(publicEs));
// Model files are served by the static site too (single source: public/models).
fs.cpSync(path.join(root, "public/models"), path.join(root, "web/public/models"), { recursive: true });

// 4) Bake the site address + sign-in client ID into Code.js, and publish an update bundle the
//    teacher's sidebar can install with one click.
const conf = JSON.parse(fs.readFileSync(path.join(root, "apps-script/build.config.json"), "utf8")) as { site?: string; clientId?: string };
let site = process.env.PAGES_URL || conf.site || "";
if (!site && process.env.GITHUB_REPOSITORY) {
  const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
  site = `https://${owner.toLowerCase()}.github.io/${repo}/`;
}
if (!site) {
  try {
    const m = execSync("git config --get remote.origin.url", { stdio: ["ignore", "pipe", "ignore"] }).toString().match(/github\.com[:/]([^/]+)\/([^/.\s]+)/);
    if (m) site = `https://${m[1].toLowerCase()}.github.io/${m[2]}/`;
  } catch { /* no git */ }
}
if (site && !site.endsWith("/")) site += "/";
const clientId = cleanClientId(process.env.GOOGLE_CLIENT_ID || process.env.VITE_GOOGLE_CLIENT_ID || conf.clientId || "");
/** Accepts pasted values like "http://123-abc.apps.googleusercontent.com/" and returns just the ID; fails loudly on anything else. */
function cleanClientId(raw: string) {
  const id = raw.trim().replace(/^https?:\/\//i, "").replace(/\/+$/, "");
  if (id && !/^\d+-[a-z0-9]+\.apps\.googleusercontent\.com$/.test(id)) throw new Error(`Google client ID looks wrong: "${raw}". It should look like 1234-abcd.apps.googleusercontent.com`);
  return id;
}
const codeSrc = fs.readFileSync(path.join(root, "apps-script/src/Code.js"), "utf8");
const read = (f: string) => fs.readFileSync(path.join(dist, f), "utf8");
const [libJs, contentJs, sidebarHtml, manifestJson] = ["Lib.js", "Content.js", "Sidebar.html", "appsscript.json"].map(read);
const loaderSrc = fs.readFileSync(path.join(root, "apps-script/src/Loader.js"), "utf8");
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as { version: string };
const hash = crypto.createHash("sha256").update([codeSrc, loaderSrc, libJs, contentJs, sidebarHtml, manifestJson, site, clientId].join("\0")).digest("hex").slice(0, 7);
const version = `${pkg.version}-${hash}`;
const buildLine = /const BUILD = \{[^\n]*\}; \/\/ @build/;
if (!buildLine.test(codeSrc)) throw new Error("Code.js is missing the BUILD line");
const engine = codeSrc.replace(buildLine, `const BUILD = ${JSON.stringify({ version, site, clientId })}; // @build`);

const pub = path.join(root, "web/public/apps-script");
fs.rmSync(pub, { recursive: true, force: true });
fs.mkdirSync(pub, { recursive: true });

// Publish one versioned application bundle. A teacher's permanent Code.gs is only the loader below.
const libForBundle = libJs.replace(/^"use strict";\nvar Lib = \(\(\) => \{/m, 'var Lib = (() => {\n"use strict";');
if (libForBundle === libJs) throw new Error("Lib.js layout changed: update the bundle step in build-pages.ts");
const bundle = [
  `// 3D Design Academy bundle ${version}`,
  libForBundle,
  contentJs,
  engine,
  `var SIDEBAR_HTML = ${JSON.stringify(sidebarHtml)};`,
  "",
].join("\n");
fs.writeFileSync(path.join(pub, "bundle.js"), bundle);

const loaderLine = /var ACADEMY_LOADER = \{[^\n]*\}; \/\/ @loader/;
if (!loaderLine.test(loaderSrc)) throw new Error("Loader.js is missing the @loader line");
const loader = loaderSrc.replace(loaderLine, `var ACADEMY_LOADER = ${JSON.stringify({ site, loader: 1 })}; // @loader`);
fs.writeFileSync(path.join(dist, "Code.js"), loader);

const notes = fs.existsSync(path.join(root, "apps-script/release-notes.txt")) ? fs.readFileSync(path.join(root, "apps-script/release-notes.txt"), "utf8").trim() : "";
fs.writeFileSync(path.join(pub, "content.json"), JSON.stringify(feed));
fs.writeFileSync(path.join(pub, "version.json"), JSON.stringify({ version, notes, date: new Date().toISOString().slice(0, 10) }));
// The one-time migration page exposes exactly the two files that belong in Apps Script.
const pasteFiles = [
  { name: "Code", kind: "Replace everything in Code.gs", text: loader },
  { name: "appsscript.json", kind: "Manifest (Project Settings → Show appsscript.json)", text: manifestJson },
];
const helper = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Update your 3D Design Academy Sheet</title>
<style>body{font:16px/1.55 system-ui,sans-serif;max-width:680px;margin:32px auto;padding:0 16px;color:#0f1b2d}
h1{font-size:26px;margin:0 0 4px}ol.steps{padding-left:22px}ol.steps>li{margin:14px 0}
.f{border:1px solid #cfd8e3;border-radius:12px;padding:12px 14px;margin:8px 0;display:flex;align-items:center;gap:12px}
.f b{font-size:17px}.f span{color:#4a5a70;font-size:14px}button{margin-left:auto;background:#0b5cad;color:#fff;border:0;border-radius:9px;padding:10px 18px;font-weight:700;font-size:15px;cursor:pointer}
button.ok{background:#15803d}textarea{position:fixed;left:-9999px}.muted{color:#4a5a70;font-size:14px}code{background:#eef2f7;border-radius:4px;padding:0 4px}
.warn{background:#fdf6dc;border:1px solid #a16207;border-radius:10px;padding:10px 14px}</style></head><body>
<h1>Install the two-file loader</h1><p class="muted">This is a one-time change. Afterward, the app and lessons update from the website automatically. Your links and student work stay the same. Version ${version}.</p>
${clientId ? "" : '<p class="warn">No Google client ID is built in. Set <code>clientId</code> in <code>apps-script/build.config.json</code> and rebuild.</p>'}
<ol class="steps">
<li>In your class Google Sheet, click <b>Extensions → Apps Script</b>.</li>
<li>Delete any old <b>Lib</b>, <b>Content</b>, or <b>Sidebar</b> files. Apps Script should contain only <b>Code.gs</b> and <b>appsscript.json</b>.</li>
<li>Click <b>Code.gs</b>, select all, and paste:<div id="f0"></div></li>
<li>Click the gear ⚙ <b>Project Settings</b> → tick <b>Show "appsscript.json"</b>. Go back (&lt;&gt; Editor), click <b>appsscript.json</b>, select all, and paste:<div id="f1"></div></li>
<li>Click 💾 <b>Save</b>.</li>
<li>If this Sheet is already deployed: click <b>Deploy → Manage deployments</b>, click the pencil ✏, choose <b>New version</b>, and click <b>Deploy</b>. Your links stay the same.</li>
</ol>
<textarea id="t"></textarea>
<script>const F=${JSON.stringify(pasteFiles).replace(/</g, "\\u003c")};
const t=document.getElementById("t");
F.forEach(function(f,i){const d=document.createElement("div");d.className="f";d.innerHTML="<div><b></b><br><span></span></div><button>Copy</button>";
d.querySelector("b").textContent=f.name;d.querySelector("span").textContent=f.kind;
const b=d.querySelector("button");b.onclick=function(){t.value=f.text;t.select();let ok=false;try{ok=document.execCommand("copy")}catch(e){}
if(!ok&&navigator.clipboard){navigator.clipboard.writeText(f.text).then(function(){b.textContent="Copied ✓";b.className="ok"});return}
b.textContent=ok?"Copied ✓":"Copy failed — try Chrome";b.className=ok?"ok":""};document.getElementById("f"+i).appendChild(d)});</script></body></html>`;
fs.writeFileSync(path.join(pub, "paste.html"), helper);
// Lib, content and sidebar are bundle inputs, never Apps Script installation files.
for (const generated of ["Lib.js", "Content.js", "Sidebar.html"]) fs.rmSync(path.join(dist, generated), { force: true });
if (!clientId) console.warn("⚠ No Google client ID baked in: set clientId in apps-script/build.config.json (or GOOGLE_CLIENT_ID).");
}

main().then(() => console.log(`Apps Script → ${path.relative(root, dist)} · public lessons → web/src/generated/lessons.json`));
