/**
 * Builds the GitHub Pages edition's generated inputs:
 *   apps-script/dist/   Code.js + Lib.js (scoring/mastery bundled from src/lib) + Content.js (answer keys) + appsscript.json
 *   web/src/generated/lessons.json   lessons with answer keys and teacher guides REMOVED (safe to publish)
 * npm run pages:prepare
 */
import fs from "node:fs";
import crypto from "node:crypto";
import { execSync } from "node:child_process";
import path from "node:path";
import { build } from "esbuild";
import { allBlocks, competencies, isRequiredBlock, journalPrompts, lessons, lessonsInPath } from "../src/content";
import { isScorable, redactBlock } from "../src/lib/scoring";

const root = process.cwd();
const dist = path.join(root, "apps-script/dist");
fs.mkdirSync(dist, { recursive: true });

// 1) Server-side content: only what the API needs to score and validate.
const serverLessons: Record<string, unknown> = {};
for (const l of lessons) {
  const blocks: Record<string, unknown> = {};
  for (const b of allBlocks(l)) if (isScorable(b) || b.type === "reflection" || b.type === "uploadEvidence") blocks[b.id] = b;
  serverLessons[l.id] = { title: l.title, prerequisites: l.prerequisites, required: allBlocks(l).filter(isRequiredBlock).map((b) => b.id), blocks };
}
const content = {
  lessons: serverLessons,
  autoAssessable: Object.fromEntries(competencies.filter((c) => c.autoAssessable).map((c) => [c.id, true])),
  competencyIds: Object.fromEntries(competencies.map((c) => [c.id, true])),
  journalPrompts: journalPrompts.map((p) => p.id),
  paths: { "9-week": lessonsInPath("9-week").map((x) => x.lesson.id), "18-week": lessonsInPath("18-week").map((x) => x.lesson.id) },
};
fs.writeFileSync(path.join(dist, "Content.js"), `// GENERATED by scripts/build-pages.ts — do not edit.\nvar CONTENT = ${JSON.stringify(content)};\n`);

// 2) Shared scoring + mastery rules as a global `Lib`.
async function main() {
await build({
  entryPoints: [path.join(root, "apps-script/lib-entry.ts")],
  bundle: true,
  format: "iife",
  globalName: "Lib",
  target: "es2019",
  outfile: path.join(dist, "Lib.js"),
  alias: { "@": path.join(root, "src") },
  banner: { js: "// GENERATED by scripts/build-pages.ts from src/lib — do not edit." },
  logLevel: "warning",
});
// esbuild emits `var Lib = ...` which Apps Script shares across files.
fs.copyFileSync(path.join(root, "apps-script/src/Sidebar.html"), path.join(dist, "Sidebar.html"));
fs.writeFileSync(
  path.join(dist, "appsscript.json"),
  JSON.stringify(
    {
      timeZone: "America/Detroit",
      runtimeVersion: "V8",
      exceptionLogging: "STACKDRIVER",
      dependencies: {
        enabledAdvancedServices: [
          { userSymbol: "Classroom", serviceId: "classroom", version: "v1" },
          { userSymbol: "Drive", serviceId: "drive", version: "v3" },
        ],
      },
      oauthScopes: [
        "https://www.googleapis.com/auth/spreadsheets.currentonly",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/script.external_request",
        "https://www.googleapis.com/auth/classroom.courses.readonly",
        "https://www.googleapis.com/auth/classroom.rosters.readonly",
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/script.container.ui",
        "https://www.googleapis.com/auth/script.projects",
        "https://www.googleapis.com/auth/script.deployments",
      ],
      webapp: { executeAs: "USER_DEPLOYING", access: "ANYONE_ANONYMOUS" },
    },
    null,
    2,
  ) + "\n",
);

// 3) Public lesson data for the static site: redacted, no teacher guide.
const publicLessons = lessons.map((l) => {
  const { teacher, ...rest } = l;
  void teacher;
  return { ...rest, sections: l.sections.map((s) => ({ ...s, blocks: s.blocks.map(redactBlock) })) };
});
const gen = path.join(root, "web/src/generated");
fs.mkdirSync(gen, { recursive: true });
fs.writeFileSync(path.join(gen, "lessons.json"), JSON.stringify(publicLessons));
// Model files are served by the static site too (single source: public/models).
fs.cpSync(path.join(root, "public/models"), path.join(root, "web/public/models"), { recursive: true });

// 4) Bake the site address + sign-in client ID into Code.js, and publish an update bundle the
//    teacher's sidebar can install with one click.
const conf = JSON.parse(fs.readFileSync(path.join(root, "apps-script/build.config.json"), "utf8")) as { site?: string; clientId?: string };
let site = process.env.PAGES_URL || conf.site || "";
if (!site && process.env.GITHUB_REPOSITORY) {
  const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
  site = `https://${owner.toLowerCase()}.github.io/${repo}/`;
}
if (!site) {
  try {
    const m = execSync("git config --get remote.origin.url", { stdio: ["ignore", "pipe", "ignore"] }).toString().match(/github\.com[:/]([^/]+)\/([^/.\s]+)/);
    if (m) site = `https://${m[1].toLowerCase()}.github.io/${m[2]}/`;
  } catch { /* no git */ }
}
if (site && !site.endsWith("/")) site += "/";
const clientId = process.env.GOOGLE_CLIENT_ID || process.env.VITE_GOOGLE_CLIENT_ID || conf.clientId || "";
const codeSrc = fs.readFileSync(path.join(root, "apps-script/src/Code.js"), "utf8");
const files = ["Lib.js", "Content.js", "Sidebar.html", "appsscript.json"].map((f) => fs.readFileSync(path.join(dist, f), "utf8"));
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as { version: string };
const hash = crypto.createHash("sha256").update([codeSrc, ...files, site, clientId].join("\0")).digest("hex").slice(0, 7);
const version = `${pkg.version}-${hash}`;
const buildLine = /const BUILD = \{[^\n]*\}; \/\/ @build/;
if (!buildLine.test(codeSrc)) throw new Error("Code.js is missing the BUILD line");
const code = codeSrc.replace(buildLine, `const BUILD = ${JSON.stringify({ version, site, clientId })}; // @build`);
fs.writeFileSync(path.join(dist, "Code.js"), code);

const pub = path.join(root, "web/public/apps-script");
fs.mkdirSync(pub, { recursive: true });
const asFile = (name: string, type: string, source: string) => ({ name, type, source: Buffer.from(source).toString("base64") });
fs.writeFileSync(
  path.join(pub, "update.json"),
  JSON.stringify({
    version,
    files: [
      asFile("appsscript", "JSON", files[3]),
      asFile("Code", "SERVER_JS", code),
      asFile("Lib", "SERVER_JS", files[0]),
      asFile("Content", "SERVER_JS", files[1]),
      asFile("Sidebar", "HTML", files[2]),
    ],
  }),
);
const notes = fs.existsSync(path.join(root, "apps-script/release-notes.txt")) ? fs.readFileSync(path.join(root, "apps-script/release-notes.txt"), "utf8").trim() : "";
fs.writeFileSync(path.join(pub, "version.json"), JSON.stringify({ version, notes, date: new Date().toISOString().slice(0, 10) }));
// 5) A local copy-paste helper (never published: it contains the answer keys).
const pasteFiles = [
  { name: "Code", kind: "Script file", text: code },
  { name: "Lib", kind: "Script file", text: files[0] },
  { name: "Content", kind: "Script file", text: files[1] },
  { name: "Sidebar", kind: "HTML file", text: files[2] },
  { name: "appsscript.json", kind: "Manifest (Project Settings → Show appsscript.json)", text: files[3] },
];
const helper = `<!doctype html><html><head><meta charset="utf-8"><title>Apps Script files — copy & paste</title>
<style>body{font:16px/1.5 system-ui,sans-serif;max-width:720px;margin:32px auto;padding:0 16px;color:#0f1b2d}
.f{border:1px solid #cfd8e3;border-radius:12px;padding:14px 16px;margin:12px 0;display:flex;align-items:center;gap:12px}
.f b{font-size:18px}.f span{color:#4a5a70;font-size:14px}button{margin-left:auto;background:#0b5cad;color:#fff;border:0;border-radius:9px;padding:10px 18px;font-weight:700;font-size:15px;cursor:pointer}
button.ok{background:#15803d}textarea{position:fixed;left:-9999px}.warn{background:#fdf6dc;border:1px solid #a16207;border-radius:10px;padding:10px 14px}</style></head><body>
<h1>Apps Script files</h1><p>Version <b>${version}</b>. In the Apps Script editor, click a file (or <b>+</b> to add it with this exact name), select all, delete, then paste.</p>
${clientId ? "" : '<p class="warn">No Google client ID is built in. That’s fine for your own Sheet (it uses the CLIENT_ID in its Config tab), but set <code>clientId</code> in <code>apps-script/build.config.json</code> and rebuild before making the template for other teachers.</p>'}
<div id="list"></div><textarea id="t"></textarea>
<script>const F=${JSON.stringify(pasteFiles).replace(/</g, "\\u003c")};
const list=document.getElementById("list"),t=document.getElementById("t");
F.forEach(function(f){const d=document.createElement("div");d.className="f";d.innerHTML="<div><b></b><br><span></span></div><button>Copy</button>";
d.querySelector("b").textContent=f.name;d.querySelector("span").textContent=f.kind+" · "+Math.round(f.text.length/1024)+" KB";
const b=d.querySelector("button");b.onclick=function(){t.value=f.text;t.select();let ok=false;try{ok=document.execCommand("copy")}catch(e){}
if(!ok&&navigator.clipboard){navigator.clipboard.writeText(f.text).then(function(){b.textContent="Copied ✓";b.className="ok"});return}
b.textContent=ok?"Copied ✓":"Copy failed — try Chrome";b.className=ok?"ok":""};list.appendChild(d)});</script></body></html>`;
fs.writeFileSync(path.join(dist, "paste-helper.html"), helper);
if (!clientId) console.warn("⚠ No Google client ID baked in: set clientId in apps-script/build.config.json (or GOOGLE_CLIENT_ID).");
}

main().then(() => console.log(`Apps Script → ${path.relative(root, dist)} · public lessons → web/src/generated/lessons.json`));
