/**
 * Builds the GitHub Pages edition's generated inputs:
 *   apps-script/dist/   Code.js + Lib.js (scoring/mastery bundled from src/lib) + Content.js (answer keys) + appsscript.json
 *   web/src/generated/lessons.json   lessons with answer keys and teacher guides REMOVED (safe to publish)
 * npm run pages:prepare
 */
import fs from "node:fs";
import path from "node:path";
import { build } from "esbuild";
import { allBlocks, competencies, isRequiredBlock, journalPrompts, lessons, lessonsInPath } from "../src/content";
import { isScorable, redactBlock } from "../src/lib/scoring";

const root = process.cwd();
const dist = path.join(root, "apps-script/dist");
fs.mkdirSync(dist, { recursive: true });

// 1) Server-side content: only what the API needs to score and validate.
const serverLessons: Record<string, unknown> = {};
for (const l of lessons) {
  const blocks: Record<string, unknown> = {};
  for (const b of allBlocks(l)) if (isScorable(b) || b.type === "reflection" || b.type === "uploadEvidence") blocks[b.id] = b;
  serverLessons[l.id] = { title: l.title, prerequisites: l.prerequisites, required: allBlocks(l).filter(isRequiredBlock).map((b) => b.id), blocks };
}
const content = {
  lessons: serverLessons,
  autoAssessable: Object.fromEntries(competencies.filter((c) => c.autoAssessable).map((c) => [c.id, true])),
  competencyIds: Object.fromEntries(competencies.map((c) => [c.id, true])),
  journalPrompts: journalPrompts.map((p) => p.id),
  paths: { "9-week": lessonsInPath("9-week").map((x) => x.lesson.id), "18-week": lessonsInPath("18-week").map((x) => x.lesson.id) },
};
fs.writeFileSync(path.join(dist, "Content.js"), `// GENERATED by scripts/build-pages.ts — do not edit.\nvar CONTENT = ${JSON.stringify(content)};\n`);

// 2) Shared scoring + mastery rules as a global `Lib`.
async function main() {
await build({
  entryPoints: [path.join(root, "apps-script/lib-entry.ts")],
  bundle: true,
  format: "iife",
  globalName: "Lib",
  target: "es2019",
  outfile: path.join(dist, "Lib.js"),
  alias: { "@": path.join(root, "src") },
  banner: { js: "// GENERATED by scripts/build-pages.ts from src/lib — do not edit." },
  logLevel: "warning",
});
// esbuild emits `var Lib = ...` which Apps Script shares across files.
fs.copyFileSync(path.join(root, "apps-script/src/Code.js"), path.join(dist, "Code.js"));
fs.writeFileSync(
  path.join(dist, "appsscript.json"),
  JSON.stringify(
    {
      timeZone: "America/Detroit",
      runtimeVersion: "V8",
      exceptionLogging: "STACKDRIVER",
      dependencies: { enabledAdvancedServices: [{ userSymbol: "Classroom", serviceId: "classroom", version: "v1" }] },
      oauthScopes: [
        "https://www.googleapis.com/auth/spreadsheets.currentonly",
        "https://www.googleapis.com/auth/drive.file",
        "https://www.googleapis.com/auth/script.external_request",
        "https://www.googleapis.com/auth/classroom.courses.readonly",
        "https://www.googleapis.com/auth/classroom.rosters.readonly",
        "https://www.googleapis.com/auth/classroom.profile.emails",
        "https://www.googleapis.com/auth/userinfo.email",
      ],
      webapp: { executeAs: "USER_DEPLOYING", access: "ANYONE_ANONYMOUS" },
    },
    null,
    2,
  ) + "\n",
);

// 3) Public lesson data for the static site: redacted, no teacher guide.
const publicLessons = lessons.map((l) => {
  const { teacher, ...rest } = l;
  void teacher;
  return { ...rest, sections: l.sections.map((s) => ({ ...s, blocks: s.blocks.map(redactBlock) })) };
});
const gen = path.join(root, "web/src/generated");
fs.mkdirSync(gen, { recursive: true });
fs.writeFileSync(path.join(gen, "lessons.json"), JSON.stringify(publicLessons));
// Model files are served by the static site too (single source: public/models).
fs.cpSync(path.join(root, "public/models"), path.join(root, "web/public/models"), { recursive: true });
}

main().then(() => console.log(`Apps Script → ${path.relative(root, dist)} · public lessons → web/src/generated/lessons.json`));
