import type { Lesson, ModelAsset, Proficiency } from "@/content/schema";
import { modelAssetSchema, allBlocks } from "@/content/schema";
import { pathInputs } from "@/content/paths";
import { competencyInputs, domains, heatmapGroups } from "@/content/competencies";
import { modelAssetInputs } from "@/content/models";
import { journalPrompts } from "@/content/badges";
import lessonsJson from "./generated/lessons.json";

/** Public, redacted lesson data (no answer keys, no teacher guides). Generated by `npm run pages:prepare`. */
export const lessons = lessonsJson as unknown as Lesson[];
export const lessonById = new Map(lessons.map((l) => [l.id, l]));
export const competencies = competencyInputs;
export { domains, heatmapGroups, journalPrompts };
export const competencyTitle = Object.fromEntries(competencyInputs.map((c) => [c.id, c.title]));

/** Model files are relative to the site so it works under /<repo>/ on GitHub Pages. */
export const modelAssets: ModelAsset[] = modelAssetInputs.map((a) => {
  const m = modelAssetSchema.parse(a);
  return m.localFilePath ? { ...m, localFilePath: "." + m.localFilePath } : m;
});
const assetById = new Map(modelAssets.map((a) => [a.id, a]));

export function assetsFor(l: Lesson): Record<string, ModelAsset> {
  const ids = new Set<string>();
  for (const b of allBlocks(l)) {
    if (b.type === "modelDownload") b.modelIds.forEach((m) => ids.add(m));
    if (b.type === "modelViewer" || b.type === "hotspot") ids.add(b.modelId);
    if ("visual" in b && b.visual?.modelId) ids.add(b.visual.modelId);
  }
  return Object.fromEntries([...ids].map((id) => [id, assetById.get(id)!]).filter(([, a]) => a));
}

export function pathLessons(pathId: string) {
  const p = pathInputs.find((x) => x.id === pathId) ?? pathInputs[1];
  return p.weeks.flatMap((w) => w.lessonIds.map((id) => ({ lesson: lessonById.get(id)!, week: w.week, weekTitle: w.title }))).filter((x) => x.lesson);
}
export const pathTitle = (pathId: string) => (pathInputs.find((x) => x.id === pathId) ?? pathInputs[1]).title;

export type Me = {
  user: { email: string; name: string; role: "student" | "teacher" };
  cls: { name: string; pathId: string; tinkercadUrl: string | null; unlockAll: boolean };
  progress: Record<string, { status: string; blockState: Record<string, unknown>; startedAt?: string }>;
  levels: Record<string, Proficiency>;
  evidence: { id: string; lessonId: string; blockId: string; type: string; url: string | null; fileName: string | null; text: string | null; status: string; rating: number | null; comment: string | null; createdAt: string }[];
  journals: Record<string, Record<string, string>>;
};
