import type { Lesson, ModelAsset, Proficiency } from "@/content/schema";
import { modelAssetSchema, allBlocks } from "@/content/schema";
import { pathInputs } from "@/content/paths";
import { competencyInputs, domains, heatmapGroups } from "@/content/competencies";
import { modelAssetInputs } from "@/content/models";
import { journalPrompts } from "@/content/badges";
import type { Stats } from "@/lib/streaks";
import lessonsJson from "./generated/lessons.json";
import { getLocale, type Locale } from "@/lib/i18n";
import { localizedCourse } from "@/content/i18n/localize";

/** Public, redacted lesson data (no answer keys, no teacher guides). Generated by `npm run pages:prepare`. */
export const lessons = lessonsJson as unknown as Lesson[];
export const lessonById = new Map(lessons.map((l) => [l.id, l]));
export const competencies = competencyInputs;
export { domains, heatmapGroups, journalPrompts };
export const competencyTitle = Object.fromEntries(competencyInputs.map((c) => [c.id, c.title]));

/** Model files are relative to the site so it works under /<repo>/ on GitHub Pages. */
export const modelAssets: ModelAsset[] = modelAssetInputs.map((a) => {
  const m = modelAssetSchema.parse(a);
  return m.localFilePath ? { ...m, localFilePath: "." + m.localFilePath } : m;
});
const assetById = new Map(modelAssets.map((a) => [a.id, a]));

export function assetsFor(l: Lesson): Record<string, ModelAsset> {
  const ids = new Set<string>();
  for (const b of allBlocks(l)) {
    if (b.type === "modelDownload") b.modelIds.forEach((m) => ids.add(m));
    if (b.type === "modelViewer" || b.type === "hotspot") ids.add(b.modelId);
    if ("visual" in b && b.visual?.modelId) ids.add(b.visual.modelId);
  }
  const models = getLocale() === "en" ? null : new Map(localizedCourse(getLocale()).models.map((m) => [m.id, m]));
  return Object.fromEntries(
    [...ids]
      .map((id) => {
        const a = assetById.get(id);
        const t = models?.get(id);
        return [id, a && t ? { ...a, title: t.title, educationalPurpose: t.educationalPurpose } : a];
      })
      .filter(([, a]) => a),
  );
}

// ── Spanish (and future) lessons: a separate generated file, loaded only when needed ──
const localized: Partial<Record<Locale, Map<string, Lesson>>> = {};
export async function ensureLocaleContent(locale: Locale) {
  if (locale === "en" || localized[locale]) return;
  const mod = await import("./generated/lessons.es.json");
  localized[locale] = new Map((mod.default as unknown as Lesson[]).map((l) => [l.id, l]));
}
export const localeContentReady = (locale: Locale) => locale === "en" || !!localized[locale];
/** The lesson in the current language (falls back to English). */
export function lessonFor(id: string): Lesson | undefined {
  const l = getLocale();
  return (l !== "en" && localized[l]?.get(id)) || lessonById.get(id);
}
export const competencyTitleFor = () => (getLocale() === "en" ? competencyTitle : Object.fromEntries(localizedCourse(getLocale()).competencies.map((c) => [c.id, c.title])));
export const domainsFor = () => {
  if (getLocale() === "en") return domains;
  const t = new Map(localizedCourse(getLocale()).domains.map((d) => [d.id, d]));
  return domains.map((d) => ({ ...d, title: t.get(d.id)?.title ?? d.title, shortTitle: t.get(d.id)?.shortTitle ?? d.shortTitle }));
};
export const journalPromptsFor = () => (getLocale() === "en" ? journalPrompts : localizedCourse(getLocale()).journalPrompts);

const pathText = (pathId: string) => (getLocale() === "en" ? undefined : localizedCourse(getLocale()).paths.find((x) => x.id === pathId));
export function pathLessons(pathId: string) {
  const p = pathInputs.find((x) => x.id === pathId) ?? pathInputs[1];
  const t = pathText(p.id);
  return p.weeks
    .flatMap((w) => w.lessonIds.map((id) => ({ lesson: lessonFor(id)!, week: w.week, weekTitle: t?.weeks.find((x) => x.id === `w${w.week}`)?.title ?? w.title })))
    .filter((x) => x.lesson);
}
export const pathTitle = (pathId: string) => {
  const p = pathInputs.find((x) => x.id === pathId) ?? pathInputs[1];
  return pathText(p.id)?.title ?? p.title;
};

export type ClassInfo = { id: string; name: string; section: string; pathId: string; tinkercadUrl: string | null; unlockAll: boolean; googleCourseId: string | null };

export type Me = {
  user: { email: string; name: string; role: "student" | "teacher" };
  cls: ClassInfo | null;
  classes: ClassInfo[];
  progress: Record<string, { status: string; blockState: Record<string, unknown>; startedAt?: string }>;
  levels: Record<string, Proficiency>;
  evidence: { id: string; lessonId: string; blockId: string; type: string; url: string | null; fileName: string | null; text: string | null; status: string; rating: number | null; comment: string | null; createdAt: string }[];
  journals: Record<string, Record<string, string>>;
  /** XP / streak / daily goal (older backends don't send it) */
  stats?: Stats | null;
  prints?: { id: string; lessonId: string; evidenceId: string; fileName: string | null; status: string; note: string; teacherNote: string; createdAt: string; updatedAt: string }[];
};
